Stratis.Bitcoin/BlockPulling/BlockPuller.cs, Stratis.Bitcoin/BlockPulling/LookaheadBlockPuller.cs, Stratis.Bitcoin/BlockPulling/NodesBlockPuller.cs
I am working on BlockPulling for an other project, I'd like to keep my code in sync with you if possible.  
- Remove redundant qualifier
- Remove unnecessary whitespaces
- Use nameof expression
- Remove redundant ()
- Use explicit private modifiers
- Removed unused directives
=> BlockPulling

Stratis.BitcoinD/Program.cs
Mine Arg missing from Program.cs since recent revert of merges on testnet1 and master branches
=> Add "mine" arg to Program.cs

Stratis.Bitcoin/BlockStore/BlockStoreLoop.cs
First item in batch was not removed from pending store items
=> merge from master - Hotfix: store pending storage bug (#46)

Stratis.Bitcoin.Tests/AsyncLoopTest.cs, Stratis.Bitcoin.Tests/Logging/LogsTestBase.cs, Stratis.Bitcoin.Tests/PeriodicTaskTest.cs, Stratis.Bitcoin.Tests/Properties/AssemblyInfo.cs, Stratis.Bitcoin.Tests/SignalObserverTest.cs, Stratis.Bitcoin/AsyncLoop.cs, Stratis.Bitcoin/BlockStore/BlockStoreLoop.cs, Stratis.Bitcoin/BlockStore/BlockStoreSignaled.cs, Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/MemoryPool/MempoolSignaled.cs, Stratis.Bitcoin/PeriodicTask.cs
-Corrected repeateEvery typo in asyncloop.
-AsyncLoop/PeriodicTask tests
-Added stopping log message to Asyncloop and PeriodicTask classes.
-Added logging unit test base class
-Stopped parallel unit test because of instability of test runs see assembyinfo.
=> AsyncLoop and PeriodicTask tests

Stratis.Bitcoin/BlockStore/BlockRepository.cs, Stratis.Bitcoin/BlockStore/BlockStoreLoop.cs, Stratis.Bitcoin/Consensus/ConsensusLoop.cs, Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/Miner/Mining.cs, Stratis.BitcoinD/Program.cs
- LazyLoadingOn
- BlockStoreLoop handle reorg on start
- ConsensusLoop not crash on reorg
- Mining find a new block if chain has advanced
- FullNode set paramteres on Initialize (not start)
=> Bug fixing from simulations

Stratis.Bitcoin.Tests/ChainRepositoryTest.cs, Stratis.Bitcoin.Tests/DBreezeNoSqlRepositoryTest.cs, Stratis.Bitcoin.Tests/DBreezeSingleThreadSessionTest.cs, Stratis.Bitcoin.Tests/RPC/RPCAuthorizationTest.cs, Stratis.Bitcoin.Tests/RPC/RPCJsonMvcOptionsSetupTest.cs, Stratis.Bitcoin.Tests/RPC/RPCJsonOutputFormatterTest.cs, Stratis.Bitcoin.Tests/TestBase.cs, Stratis.Bitcoin/ChainRepository.cs, Stratis.Bitcoin/DBreezeNoSqlRepository.cs, Stratis.Bitcoin/DBreezeSingleThreadSession.cs, Stratis.Bitcoin/RPC/RPCAuthorization.cs, Stratis.Bitcoin/RPC/RPCJsonOutputFormatter.cs, Stratis.Bitcoin/SignalObserver.cs, Stratis.Bitcoin/Signaler.cs, Stratis.Bitcoin/Signals.cs
- I was wondering if I should add a second constructor on the ChainRepository and DBreezeNoSqlRepository that accepts an IDBreezeSingleThreadSession as a parameter. That would allow for even more isolated tests.
=> First set of RPC tests.

Stratis.Bitcoin/Builder/FullNodeBuilder.cs, Stratis.Bitcoin/Builder/FullNodeBuilderExtensions.cs, Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/MemoryPool/MempoolFeature.cs, Stratis.Bitcoin/MemoryPool/MempoolSignaled.cs
(MempoolFeature fix args) in the GitHub project
=> Moved the dependency on the FullNode out of the MemPool Feature

Documentation/getting-started.md
Added a 1.1 section for installation of .NET Core required version on Ubuntu 14.04, 16.04, 16.10 & Linux Mint 17 (64 bit).
=> Updated .NET Core required version installation

Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs, Stratis.Bitcoin/BlockPulling/LookaheadBlockPuller.cs, Stratis.Bitcoin/BlockStore/BlockStoreFeature.cs, Stratis.Bitcoin/Builder/FullNodeBuilder.cs, Stratis.Bitcoin/Builder/FullNodeBuilderExtensions.cs, Stratis.Bitcoin/Consensus/ConsensusFeature.cs, Stratis.Bitcoin/Consensus/ConsensusLoop.cs, Stratis.Bitcoin/Consensus/ConsensusStats.cs, Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/Logging/Logs.cs, Stratis.BitcoinD/Program.cs
Moved all the Consensus code to its own feature.
Added Consensus logger.
Moved blockStoreManager flushing out of the full node and into the feature.
=> Consensus feature

README.md, Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs, Stratis.Bitcoin/Builder/Feature/FullNodeFeature.cs, Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/RPC/RPCFeature.cs, Stratis.BitcoinD/Program.cs
Made suggested fixes from previous pull request. Sorry to create a separate pull request.
=> Refactoring for RPC "Feature"

Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/Logging/Logs.cs, Stratis.Bitcoin/Miner/MiningFeature.cs, Stratis.BitcoinD/Program.cs
Not really completes yet, this is just a move to the feature
=> Moved the mining process to its own feature

Stratis.Bitcoin.Tests/BlockStore/BlockStoreBehaviorTest.cs, Stratis.Bitcoin.Tests/BlockStore/BlockStoreCacheTest.cs, Stratis.Bitcoin.Tests/BlockStore/MemoryCacheStub.cs, Stratis.Bitcoin.Tests/Builder/Feature/FeatureCollectionTest.cs, Stratis.Bitcoin.Tests/Builder/Feature/FeatureRegistrationTest.cs, Stratis.Bitcoin/BlockStore/BlockRepository.cs, Stratis.Bitcoin/BlockStore/BlockStoreBehavior.cs, Stratis.Bitcoin/BlockStore/BlockStoreCache.cs, Stratis.Bitcoin/BlockStore/BlockStoreFeature.cs, Stratis.Bitcoin/Builder/Feature/FeatureCollection.cs, Stratis.Bitcoin/Builder/Feature/FeatureRegistration.cs, Stratis.Bitcoin/Builder/FullNodeBuilder.cs, Stratis.Bitcoin/Builder/IFullNodeBuilder.cs
Attempted testing of BlockStoreBehavior. I think testing of NodeBehavior implementers would become a lot easier if we wrap the Node class from NBitcoin.
=> BlockstoreCache, FeatureCollection, FeatureRegistration tests

Stratis.Bitcoin.FullNode.vs2017.sln, Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj, Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj, Stratis.Bitcoin/Stratis.Bitcoin.csproj, Stratis.StratisD/Stratis.StratisD.csproj, global.json
Switched from NBitcoin to NStratis nuget.
Compiles and test run successfully.
=> Added stratisd project to vs2017 solution. 

Stratis.Bitcoin/Connection/ConnectionManager.cs
Add   _Parameters.Version = NodeSettings.ProtocolVersion; To Nodesettings Connection Parameters for Setting Correct Protocol Version: 70000
Tested, and working.
=> Set Correct Protocol Version

Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj, Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj, Stratis.Bitcoin/Stratis.Bitcoin.csproj, Stratis.BitcoinD/Stratis.BitcoinD.csproj, Stratis.StratisD/Stratis.StratisD.csproj
=> Update NStratis project for VS2017 build.

Stratis.Bitcoin/Configuration/NodeSettings.cs, Stratis.Bitcoin/Stratis.Bitcoin.csproj, Stratis.Bitcoin/Utilities/ProtocolExtensions.cs
Also, update logger in 2017 project
=> Use GetDefaultConfigurationFilename to determine config file by network

Stratis.Bitcoin/BlockPulling/BlockPuller.cs
Fix collection modified bug in AssignPendingVectors
Code cleanup in separate commits.
Fixes: https://github.com/stratisproject/StratisBitcoinFullNode/issues/126
=> Fix collection modified bug in AssignPendingVectors 

Stratis.Bitcoin/Consensus/UnspentOutputSet.cs, Stratis.Bitcoin/MemoryPool/MemPoolCoinView.cs
This race condition is really hard to test but I believe I am correct in whats causing the bug.
https://github.com/stratisproject/StratisBitcoinFullNode/issues/87
=> Fix mempool duplicate trx bug

Stratis.Bitcoin/Wallet/Controllers/WalletController.cs, Stratis.Bitcoin/Wallet/Wallet.cs, Stratis.Bitcoin/Wallet/WalletManager.cs
=> new spending transaction model

Stratis.Bitcoin/Configuration/NodeSettings.cs, Stratis.Bitcoin/Configuration/TextFileConfiguration.cs, Stratis.Bitcoin/FullNode.cs, Stratis.Bitcoin/Wallet/Controllers/WalletController.cs, Stratis.Bitcoin/Wallet/IWalletManager.cs, Stratis.Bitcoin/Wallet/Models/RequestModels.cs, Stratis.Bitcoin/Wallet/WalletManager.cs
**you need to do the previous code review first, or do this one commit by commit.**
I removed the coinType that we can find in the wallet controller, manager etc...
@dangershony @dev0tion 
PJ: if you pass a coinType with your request, there will be no exception, so you can remove it in your own time.
=> Removed cointype

Stratis.Bitcoin/Wallet/Wallet.cs, Stratis.Bitcoin/Wallet/WalletManager.cs
=> adding BlockHash to the wallet tx object

Stratis.Bitcoin/Wallet/WalletManager.cs
making sure we don't do much work in process block if there's no wallet that's been created.
=> Better assessment of where the wallet tip should be

Stratis.Bitcoin.Tests/Converters/BtcDecimalJsonConverterTest.cs, Stratis.Bitcoin/RPC/Converters/BtcDecimalJsonConverter.cs
I didn't see any tests around the converter, I'm not 100% sure what it does yet but I thought it could use some tests :)
=> Add Tests for BtcDecimalJsonConverter

Stratis.Bitcoin.Tests/AsyncLoopTest.cs
These tests were sometimes failing, sometimes passing.
=> made tests that call async methods async

Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs, Stratis.Bitcoin/Builder/FullNodeBuilder.cs, Stratis.Bitcoin/Builder/FullNodeBuilderExtensions.cs
Small commit to remove null ref if settings are null.
=> removed NRE when nodesettings are null

README.md, Stratis.Bitcoin.FullNode.sln, appveyor.yml
build for nuget packages on AppVeyor
=> added appveyor CI build

Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs, Stratis.Bitcoin/Wallet/Controllers/WalletController.cs
Adjusted the GetHistory method so that it includes spent transactions from change addresses.
=> History doesn't show spending on change addresses

Stratis.Bitcoin/RPC/RPCFeature.cs, Stratis.Bitcoin/RPC/WebHostExtensions.cs
Add node DI services to RPC Feature DI services when configuring
the RPC feature. Technique taken from Breeze API to update
API DI services.
=> [RPC] Make RPC standalone

Stratis.Bitcoin/Stratis.Bitcoin.csproj
@NicolasDorier @dangershony Here is Nicolas' change in another shape.
=> Change version of System.ValueTuple to 4.3.1

Stratis.Bitcoin/Builder/BaseFeature.cs, Stratis.Bitcoin/Builder/Feature/FeatureCollection.cs, Stratis.Bitcoin/Builder/Feature/FeatureRegistration.cs, Stratis.Bitcoin/Builder/Feature/FullNodeFeature.cs, Stratis.Bitcoin/Builder/FullNodeBuilder.cs, Stratis.Bitcoin/Builder/FullNodeBuilderExtensions.cs, Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs, Stratis.Bitcoin/Builder/FullNodeServiceProvider.cs, Stratis.Bitcoin/Builder/IFullNode.cs, Stratis.Bitcoin/Builder/IFullNodeBuilder.cs, Stratis.Bitcoin/Stratis.Bitcoin.csproj
Adds XML documentation comments to all files in Stratis.Bitcoin\Builder and also fixes several violations of the code style (mostly use of TABs instead of spaces).
This PR should not change ANY functionality of the code at all, it is all about comments and code style.
=> Feature/xmldoc stratis.bitcoin.builder

Stratis.Bitcoin.Common/Hosting/NodeLifeTime.cs, Stratis.Bitcoin.Tests/TestBase.cs, Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs, Stratis.Bitcoin/Features/Wallet/Controllers/WalletController.cs, Stratis.Bitcoin/Features/Wallet/IWalletManager.cs, Stratis.Bitcoin/Features/Wallet/WalletManager.cs
First part of tests for the walletmanager. Continuing with the next batch. When the walletmanager class is fully tested I will refactor the tests and optimize to speed up wallet creation so they run faster.
=> First batch of wallet manager tests

Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs, Stratis.Bitcoin/Features/Wallet/Controllers/WalletController.cs, Stratis.Bitcoin/Features/Wallet/Helpers/SendTransactionComparer.cs, Stratis.Bitcoin/Features/Wallet/Helpers/SentTransactionItemModelComparer.cs
A fix for https://github.com/stratisproject/Breeze/issues/175
=> Fix breeze wallet issue #175 multiple transaction boxes

Stratis.Bitcoin.IntegrationTests/WalletTests.cs, Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs, Stratis.Bitcoin/Features/Miner/PosMinting.cs, Stratis.Bitcoin/Features/Wallet/IWalletManager.cs, Stratis.Bitcoin/Features/Wallet/WalletManager.cs, Stratis.StratisD/Program.cs
See https://trello.com/c/wurnrjhN/120-pos-add-walletname-to-getspendabletransactions-method
=> Add walletname to PosMining wallet methods

Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepBaseTest.cs, Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepCheckNextChainedBlockExistStepTest.cs, Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepDownloadBlocksTest.cs, Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepReorganiseTest.cs, Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepTryPendingTest.cs, Stratis.Bitcoin/Features/BlockStore/BlockPair.cs, Stratis.Bitcoin/Features/BlockStore/BlockStoreLoop.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/BlockStoreLoopStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/CheckNextChainedBlockExistStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/DownloadBlockStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/ProcessPendingStorageStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/ReorganiseBlockRepositoryStep.cs
Split BlockStoreLoop into 4 logical areas and add unit tests using a successor pattern.
Add Steps
CheckExists
Reorganise
TryPending
DownloadBlocks
=> [BlockStore] Split BlockStoreLoop #206

Stratis.Bitcoin/Settings.StyleCop
This adds an empty stylecop settings file.
I'm starting with all the rules disabled so that on subsequent commits it's easy to see which have been enabled.
@dangershony
=> Added empty StyleCop settings file

Stratis.Bitcoin/Features/BlockStore/LoopSteps/DownloadBlockStep.cs, Stratis.StratisD/Program.cs
Fixed a bug in BlockStoreLoop.DownloadBlock
=> BlockStoreLoop.DownloadBlocks threw an unhandled exception #266

Stratis.Bitcoin.IntegrationTests/RPCTEsts.cs, Stratis.Bitcoin/Features/RPC/Controllers/FullNodeController.cs, Stratis.Bitcoin/Features/RPC/Models/BlockHeaderModel.cs
Add the rpc method "getblockheader" with supporting integration unit test from NBitcoin.  Test CanGetBlockFromRPC() assertion is currently failing but not sure what I'm doing wrong - need another set of eyes to see what I missing.
=> add rpc method getblockheader

Stratis.Bitcoin.IntegrationTests/RPCTEsts.cs, Stratis.Bitcoin/Features/RPC/Controllers/ConnectionManagerController.cs, Stratis.Bitcoin/Features/RPC/Models/PeerNodeModel.cs
Initial implementation of RPC method getpeerinfo. Some RPC properties are not populated. In trello backlog https://trello.com/c/4SRyzKjI/59-connection-rpc-getpeerinfo 
@bokobza
=> RPC getpeerinfo

Stratis.Bitcoin.Tests/WatchOnlyWallet/WatchOnlyWalletControllerTest.cs, Stratis.Bitcoin.Tests/WatchOnlyWallet/WatchOnlyWalletManagerTest.cs, Stratis.Bitcoin/Features/WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs, Stratis.Bitcoin/Features/WatchOnlyWallet/IWatchOnlyWalletManager.cs, Stratis.Bitcoin/Features/WatchOnlyWallet/Models/WatchOnlyWalletModel.cs, Stratis.Bitcoin/Features/WatchOnlyWallet/WatchOnlyWallet.cs, Stratis.Bitcoin/Features/WatchOnlyWallet/WatchOnlyWalletFeature.cs, Stratis.Bitcoin/Features/WatchOnlyWallet/WatchOnlyWalletManager.cs
I'm writing the tests, but I'd appreciate some comments on this @dangershony.
=> Watch-only wallet

Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletTestsHelpers.cs, Stratis.Bitcoin.Tests/Wallet/WalletTransactionHandlerTest.cs, Stratis.Bitcoin/Features/Miner/PosMinting.cs, Stratis.Bitcoin/Features/Wallet/Controllers/WalletController.cs, Stratis.Bitcoin/Features/Wallet/FeeType.cs, Stratis.Bitcoin/Features/Wallet/IWalletManager.cs, Stratis.Bitcoin/Features/Wallet/Models/MaxSpendableAmountModel.cs, Stratis.Bitcoin/Features/Wallet/Models/RequestModels.cs, Stratis.Bitcoin/Features/Wallet/Wallet.cs, Stratis.Bitcoin/Features/Wallet/WalletAccountReference.cs, Stratis.Bitcoin/Features/Wallet/WalletManager.cs, Stratis.Bitcoin/Features/Wallet/WalletTransactionHandler.cs
Added a controller method to get the maximum spendable balance on an account, along with the fee required to spend it.
https://trello.com/c/VxsOrqcX/89-wallet-1-add-max-function-to-api
=> Max spendable amount

Stratis.Bitcoin.IntegrationTests/MinerTests.cs, Stratis.Bitcoin.Tests/MemoryPool/MempoolPersistenceTest.cs, Stratis.Bitcoin/Features/Miner/AssemblerFactory.cs, Stratis.Bitcoin/Features/Miner/PosBlockAssembler.cs, Stratis.Bitcoin/Features/Miner/PowBlockAssembler.cs
Also cleaned up compiler warnings in MinerTest.cs
=> Finish renaming of MempoolScheduler to MempoolAsyncLock.

Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs, Stratis.Bitcoin.Tests/Utilities/FileStorageTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs, Stratis.Bitcoin/Features/Wallet/Controllers/WalletController.cs, Stratis.Bitcoin/Features/Wallet/IWalletManager.cs, Stratis.Bitcoin/Features/Wallet/WalletManager.cs, Stratis.Bitcoin/Utilities/FileStorage.cs
Added FileStorage class, providing a set of methods that can be used to save/load objects in files.
=> Added FileStorage class

Stratis.Bitcoin.Tests/BlockStore/BlockRepositoryInMemory.cs, Stratis.Bitcoin.Tests/BlockStore/BlockRepositoryTest.cs, Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepBaseTest.cs, Stratis.Bitcoin.Tests/Features/MemoryPool/MempoolPersistenceTest.cs, Stratis.Bitcoin.Tests/Features/MemoryPool/MempoolValidatorTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletTest.cs, Stratis.Bitcoin.Tests/Wallet/WalletTestsHelpers.cs, update.bat
- Moved mempool unit tests to appropriate folder location/namespace inline with testing standards (caused some changes to other files do to usings being slightly different)
- Created test stubs for ~45 tests for testing different mempool validator scenarios. Added some comments about how to potentially test.
=> Stubs for mempool validator tests

Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs, Stratis.Bitcoin/Features/Notifications/BlockNotificationFeature.cs, Stratis.Bitcoin/Features/Wallet/Wallet.cs, Stratis.Bitcoin/Features/Wallet/WalletManager.cs
=> Added the Hex of receiving and spending transactions.

Stratis.Bitcoin.Tests/NodeConfiguration/TextFileConfigurationTests.cs, Stratis.Bitcoin/Configuration/TextFileConfiguration.cs
This relates to this Trello story
https://trello.com/c/tnh91zAa/123-nodesettings-textfileconfiguration-get-all-method
=> adding improvements on GetAll method in TextFileConfiguration

Stratis.Bitcoin.Tests/BlockStore/LoopTests/BlockStoreLoopStepFindBlocksTaskTest.cs, Stratis.Bitcoin/Features/BlockStore/BlockStoreLoop.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/BlockStoreInnerStepContext.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/BlockStoreInnerStepFindBlocks.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/BlockStoreInnerStepReadBlocks.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/CheckNextChainedBlockExistStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/DownloadBlockStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/ProcessPendingStorageStep.cs, Stratis.Bitcoin/Features/BlockStore/LoopSteps/ReorganiseBlockRepositoryStep.cs, Stratis.Bitcoin/Features/Consensus/ConsensusFeature.cs, Stratis.Bitcoin/Features/Consensus/StakeChainStore.cs, Stratis.StratisD/Properties/launchSettings.json
This PR is mostly for @dangershony to review as I took this branch over from him.
=> [BlockStore] Improve how BlockStoreLoopStepReadBlocks reads blocks from the puller and pushes to the block repository #377

Stratis.Bitcoin.Tests/Features/MemoryPool/MempoolValidatorTest.cs, Stratis.Bitcoin.Tests/Features/MemoryPool/TestChainFactory.cs
P2PKH/P2PK with multiple inputs/outputs, Multi-Sig, & P2SH tests with valid txs
Proper handling of data dir for mem pool validation tests
=> Add more valid transaction tests to mempool validator tests

Stratis.Bitcoin.Tests/Features/MemoryPool/MempoolValidatorTest.cs, Stratis.Bitcoin.Tests/Features/MemoryPool/TestChainFactory.cs
Seems a merge created some code that no longer builds in the unit test project. I corrected that and also fixed a couple of code review issues in the mempool unit tests.
=> Fix unit test build and code review issues.

Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
@fassadlr @dangershony @quantumagi
=> Fix for CacheSettings missing when running StratisD

Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/WatchOnlyWalletManagerTest.cs, Stratis.Bitcoin.Features.WatchOnlyWallet/Settings.StyleCop, Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs, Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs
@zeptin here is your change
@dangershony
=> [WatchOnlyWallet] Adding id and Merkle proof data in transactions

Stratis.Bitcoin.Features.Wallet/WalletManager.cs
Resolves: https://github.com/stratisproject/Breeze/issues/226
=> Fix logging in with wrong password bug

Stratis.Bitcoin.Features.Miner/PowMining.cs
Relates to https://github.com/stratisproject/StratisBitcoinFullNode/issues/397
=> Pow mining should also check the cancellation token when mining

Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, Stratis.Bitcoin.Features.Wallet/IWalletManager.cs, Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, Stratis.Bitcoin.Features.Wallet/WalletManager.cs
Resolves the API part of https://github.com/stratisproject/Breeze/issues/203 and https://github.com/stratisproject/Breeze/issues/202 .   
Two new endpint:  
`addresses`  
`extpubkey`
=> Add more ways to receive

Stratis.Bitcoin.Api.Tests/Postman requests/Node.postman_collection.json, Stratis.Bitcoin.Api.Tests/Postman requests/Wallet.postman_collection.json, Stratis.Bitcoin.Api/Properties/launchSettings.json, Stratis.Bitcoin/Configuration/NodeSettings.cs, Stratis.BreezeD/Program.cs
5000 -> 37220  
5105 -> 37221  
Tied to: https://github.com/stratisproject/Breeze/pull/242
Resolves: https://github.com/stratisproject/Breeze/issues/240
=> Change ports

Stratis.BreezeD/Launchers/launch main.bat, Stratis.BreezeD/Launchers/launch test.bat, Stratis.BreezeD/Program.cs, Stratis.BreezeD/Properties/AssemblyInfo.cs, Stratis.BreezeD/Properties/launchSettings.json, Stratis.BreezeD/Stratis.BreezeD.csproj
Removed the need to add light to start the daemons as BreezeD is light by default.
=> Made the BreezeD console app sexy and light again.

Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletFixedFeePolicyTest.cs, Stratis.Bitcoin.Features.LightWallet/LightWalletBitcoinExternalFeePolicy.cs, Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolManagerTest.cs, Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs, Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs, Stratis.Bitcoin.Features.MemoryPool/Fee/BlockPolicyEstimator.cs, Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs, Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs, Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs, Stratis.Bitcoin.Features.RPC.Tests/Controller/GetInfoActionTests.cs, Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, Stratis.Bitcoin.Features.Wallet/WalletFeePolicy.cs, Stratis.Bitcoin.IntegrationTests/FeeTests.cs, Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs, Stratis.Bitcoin.IntegrationTests/MinerTests.cs, Stratis.Bitcoin/Configuration/NodeSettings.cs, Stratis.Bitcoin/Utilities/NetworkExtensions.cs
- Default mintxfee and fallbackfee from network
- Make minrelayfee configurable and default to network value
- Remove mempool validator static field for minrelayfee
=> Transaction Fee Refactor

Stratis.Bitcoin.Features.Consensus/Checkpoints.cs, Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, Stratis.Bitcoin.Features.Consensus/StakeValidator.cs, Stratis.Bitcoin.Features.Miner/PowMining.cs, Stratis.Bitcoin.IntegrationTests/BlockStoreTests.cs, Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs, Stratis.Bitcoin.IntegrationTests/IndexerTests.cs, Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs, Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs, Stratis.Bitcoin.IntegrationTests/NodeSync.cs, Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, Stratis.Bitcoin.IntegrationTests/RPCTEsts.cs, Stratis.Bitcoin.IntegrationTests/WalletTests.cs, Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs
This will also fix the failing tests we had til now
=> Unit test that simulate a 500 block reorg

Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs, Stratis.Bitcoin.Features.MemoryPool/MempoolSignaled.cs
Refactor mempool features to properly dispose of async loops
=> Fix or better handle all async loops in the solution [Part 3 - Mempool]

Stratis.Bitcoin.Api/ApiFeature.cs, Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs, Stratis.BreezeD/Program.cs
Refactor Api feature to properly dispose of async loops
=> Fix or better handle all async loops in the solution [Part 4 - Api Feature]

Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs, Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, Stratis.Bitcoin.Features.Wallet/Broadcasting/FullNodeBroadcasterManager.cs, Stratis.Bitcoin.Features.Wallet/Broadcasting/LightWalletBroadcasterManager.cs, Stratis.Bitcoin.Features.Wallet/Broadcasting/SmartBitBroadcasterManager.cs, Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, Stratis.Bitcoin.Features.Wallet/WalletFeature.cs, Stratis.Bitcoin.Features.Wallet/WalletManager.cs, Stratis.Bitcoin.IntegrationTests/WalletTests.cs, Stratis.Bitcoin/Broadcasting/BroadcasterBehavior.cs, Stratis.Bitcoin/Broadcasting/BroadcasterManagerBase.cs, Stratis.Bitcoin/Broadcasting/State.cs, Stratis.Bitcoin/Broadcasting/Success.cs, Stratis.Bitcoin/Broadcasting/TransactionBroadcastEntry.cs, Stratis.Bitcoin/Interfaces/IBroadcasterManager.cs, Stratis.Bitcoin/Stratis.Bitcoin.csproj
Replaces: https://github.com/stratisproject/StratisBitcoinFullNode/pull/537, https://github.com/stratisproject/StratisBitcoinFullNode/pull/486
=> Implement send transaction 3 different ways

Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletFixedFeePolicyTest.cs, Stratis.Bitcoin.Features.LightWallet/LightWalletBitcoinExternalFeePolicy.cs, Stratis.Bitcoin.Features.LightWallet/LightWalletFixedFeePolicy.cs, Stratis.Bitcoin.Features.MemoryPool/Fee/BlockPolicyEstimator.cs, Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs, Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs, Stratis.Bitcoin.Features.RPC.Tests/Controller/GetInfoActionTests.cs, Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, Stratis.Bitcoin.Features.Wallet/WalletFeePolicy.cs, Stratis.Bitcoin/Configuration/NodeSettings.cs
Also Rename Fee to FeeRate when it's actually FeeRate
=> Fix Stratis minimum fee

Stratis.Bitcoin.Features.Miner/PosMinting.cs
=> Don't wait for peers when minting new POS block.

Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, Stratis.Bitcoin.Features.Wallet/Wallet.cs, Stratis.Bitcoin.Features.Wallet/WalletManager.cs
Addressing some of the issues described in https://github.com/stratisproject/StratisBitcoinFullNode/commit/61c3b92f12afd3fc2b3904af990f73781a6ede69#commitcomment-24845666
=> Improve code issues around thread safe wallet

Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs
Attempted to shorten the test names and add a summary providing an explanation of the test.
=> Add explanation to walletsyncmanager test

Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepContext.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepFindBlocks.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepReadBlocks.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/CheckNextChainedBlockExistStep.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/DownloadBlockStep.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/ProcessPendingStorageStep.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/ReorganiseBlockRepositoryStep.cs, Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs, Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs, Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs, Stratis.Bitcoin.Features.Consensus/StakeValidator.cs, Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs, Stratis.Bitcoin.Features.Miner/PosMinting.cs, Stratis.Bitcoin.Features.Wallet/WalletManager.cs, Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs, Stratis.Bitcoin/BlockPulling/StoreBlockPuller.cs, Stratis.Bitcoin/Connection/DropNodesBehaviour.cs
Cleaner logging of ChainedBlock and OutPoint.
Also couple of fixes and cleanups and logging improvements.
Fix #591
=> refactoring - ChainedBlock and OutPoint cleaner logging

Stratis.Bitcoin.Api/ApiFeature.cs, Stratis.Bitcoin.Api/Program.cs, Stratis.Bitcoin.Features.Consensus/ConsensusStats.cs, Stratis.Bitcoin.IntegrationTests/APITests.cs, Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs
This PR identifies issues leading to failing integration tests and provides the required fixes.
=> Fix failing integration tests

Stratis.Bitcoin.Features.Wallet/WalletManager.cs
=> Do case insensitive comparison when checking for existing wallet

Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
=> Replace node guard checks with logging in mempool peer messaging

Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepFindBlocks.cs, Stratis.Bitcoin.Features.BlockStore/LoopSteps/ProcessPendingStorageStep.cs, Stratis.Bitcoin.Features.Consensus/ConsensusController.cs, Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs, Stratis.Bitcoin.Features.Consensus/ConsensusManager.cs, Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs, Stratis.Bitcoin.Features.IndexStore/IndexStoreRPCController.cs, Stratis.Bitcoin.Features.Miner/PosMinting.cs, Stratis.Bitcoin.Features.Miner/PowMining.cs, Stratis.Bitcoin.Features.Notifications/BlockNotificationFeature.cs, Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, Stratis.Bitcoin.IntegrationTests/BlockStoreTests.cs, Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs, Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs, Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, Stratis.Bitcoin.IntegrationTests/TestHelper.cs, Stratis.Bitcoin/Base/BaseFeature.cs, Stratis.Bitcoin/Base/ChainHeadersBehavior.cs, Stratis.Bitcoin/Base/ChainState.cs
=> Reorg 413 test fix

Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs, Stratis.Bitcoin.Features.IndexStore.Tests/IndexRepositoryTest.cs, Stratis.Bitcoin/BlockPulling/BlockPullerBehavior.cs
This is what MSVS suggest to do in compiler messages (i.e. not errors, not warnings, but lowest level).
=> apply suggestions from MSVS

src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs, src/Stratis.Bitcoin.Tests/Utilities/DBreezeTest.cs
serializer has to be initialized
but there are still integration tests that fail on something else, we should look at it
=> fix some integration tests

src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
=> Throw exception if prune mode is attempted with mining or staking.

src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs, src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.Miner/PosMinting.cs, src/Stratis.Bitcoin.Features.Miner/PowMining.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
=> making consensus loop fully async

src/Stratis.Bitcoin.Features.Api/ApiFeature.cs, src/Stratis.Bitcoin.Features.Api/Program.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreCachePerformanceCounter.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoopStep.cs, src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepReadBlocks.cs, src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/ProcessPendingStorageStep.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs, src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs, src/Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs, src/Stratis.Bitcoin.Features.MemoryPool/MemPoolCoinView.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs, src/Stratis.Bitcoin.Features.Miner/Controllers/MinerController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs, src/Stratis.Bitcoin/Utilities/AsyncLoopFactory.cs, src/Stratis.Bitcoin/Utilities/Extensions/VersionExtensions.cs, src/Stratis.Bitcoin/Utilities/LoggingExtensions.cs
Most of the changes are ensuring following 'Code Commenting Policy' and 'C# Coding Style' guidelines
=> Minor code improvements based on static code analysis

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs, src/Stratis.Bitcoin/Builder/Feature/FeatureRegistration.cs
this is just removing one compiler warning and removing two things from staking code that are unused, no harm should be caused by this
=> minor cleanup

src/Stratis.Bitcoin.Cli/Program.cs, src/Stratis.StratisD/Program.cs, src/Stratis.StratisD/Stratis.StratisD.csproj
This PR:
- Extends the CLI to also call API methods
- Adds the API feature to StratisD
=> Extend the CLI to also call API methods

src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletSyncManagerTest.cs
The offending commit: https://github.com/stratisproject/StratisBitcoinFullNode/commit/34275331375894d40ba4f2dfe4b7c9439d5a36fa
=> Updated tests to match changes done in previous commit

src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletSyncManagerTest.cs, src/Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/IWatchOnlyWalletManager.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/Models/WatchOnlyWalletModel.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs
=> Upstream merge of TB changes

src/Stratis.Bitcoin.Features.Consensus.Tests/ConsensusSettingsTest.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusSettings.cs
Also added some unit tests for ConsensusSettings including one that validates this issue.
Fixes #755
=> Fix exception being thrown when attempting to turn off assumevalid flag.

src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs
=> Add get attribute on rpc controller method.

src/NBitcoin/ChainedBlock.cs
Basic styling and commenting - no real structural changes other than I removed
```
public ChainedBlock FindAncestorOrSelf(int height)
```
It was not referenced by anything and does exactly the same thing as ```GetAncestor()``` which is actually used.
=> Refactor ChainedBlock to add comments and styling.

src/Stratis.Bitcoin.Features.WatchOnlyWallet/Stratis.Bitcoin.Features.WatchOnlyWallet.csproj, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletFeature.cs
Fix for https://github.com/stratisproject/StratisBitcoinFullNode/issues/765
@zeptin
=> Fixed WatchOnlyWallet dependency on the Wallet feature

src/Stratis.Bitcoin/Base/ChainRepository.cs
Issue #747
Used to load for 14 sec (out of total 14.9 for node startup) on my PC, now 40% faster.
=> Optimization of ChainRepository.LoadAsync

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletSendTransactionModel.cs
(cherry picked from commit b237616409e9784f1bee5058176913a877d777b3)
=> Added some extra data to a successfully sent transaction. (#781)

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
Used same approach that was used in StratisX instead of the old one that implemented that functionality wrong. 
Fix #754
=> Changed implementation of PoS reserved balance

src/Stratis.Bitcoin/Connection/ConnectionManager.cs
=> Added handling for situation when default port is being used.

src/Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs, src/Stratis.Bitcoin.IntegrationTests/P2P/NodeConnectionTests.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
- Fix ExtendedLogger issues
- Fix CoreNode logging issue
- Implement WaitLoop for CanDiscoverAndConnectToPeersOnTheNetwork
- Fix NetworkPeer constructor with logger
- Improve CanDiscoverAndConnectToPeersOnTheNetwork test
=> Fix Build and Tests

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
This PR does the following:
- Fixes the missing GetOrDefault("apiuri",...) in NodeOptions.cs
=> Fix misplaced "apiuri'

src/Stratis.Bitcoin.Features.Consensus.Tests/MerkeRootComputationTest.cs, src/Stratis.Bitcoin.Features.Consensus/PowConsensusValidator.cs
This PR includes CountWitnessSignatureOperation and ComputeMerkleRoot refactoring and some MerkleRoot tests.
=> CountWitnessSignatureOperation and ComputeMerkleRoot refactoring.

src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
=> Removed Wallet dependency for the pow mining feature.

src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerTests.cs, src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs, src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs, src/Stratis.Bitcoin/Utilities/Extensions/IPExtensions.cs
This is to fix small bug as pointed out by @dangershony .
=> Fix small add connector bug

src/NBitcoin/ChainBase.cs
Also removed a confusing implementation of Contains which was not referenced anywhere. See #659 for details.
=> Comments and styling for ChainBase

src/NBitcoin/BitcoinCore/BlockStore.cs, src/NBitcoin/BitcoinCore/Coins.cs, src/NBitcoin/BitcoinCore/CoinsView.cs, src/NBitcoin/Payment/PaymentACK.cs, src/NBitcoin/RPC/RawFormatter.cs, src/NBitcoin/RPC/RestClient.cs
This PR fixes the coding style in the following files:
- BlockStore.cs
- Coins.cs
- CoinsView.cs
- PaymentACK.cs
- RawFormatter.cs
- RestClient.cs
=> Fix coding style in NBitcoin - Part 1

src/NBitcoin.Tests/pos_RPCClientTests.cs, src/NBitcoin.Tests/pos_RepositoryTests.cs, src/NBitcoin/RPC/RPCClient.Wallet.cs, src/NBitcoin/RPC/RPCClient.cs
This PR fixes the coding style in the following files:
- RPCClient.cs
- RPCClient.Wallet.cs
- pos_RPCClientTests.cs
- pos_RepositoryTests.cs
=> Fix coding style in NBitcoin - Part 2

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletGeneralInfoModel.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletHistoryModel.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/Models/WatchOnlyWalletModel.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs, src/Stratis.Bitcoin.Tests/Utilities/NetworkHelpersTest.cs, src/Stratis.Bitcoin/P2P/PeerAddress.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/ByteArrayConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/DateTimeOffsetConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/NetworkConverter.cs, src/Stratis.Bitcoin/Utilities/NetworkHelpers.cs
=> small change in peers json fields

src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs
=> Fixed wallet tests

src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs, src/Stratis.Bitcoin.Features.Miner/PosMinting.cs, src/Stratis.Bitcoin/Base/ChainState.cs
This was supposed to fix #896, but unfortunately, these things can't explain that, so it is improvement of the code, fixed that bug with missing continue, but overall, not a real fix for #896.
=> Some improvements and bugfix related to IBD and staking

src/Stratis.Bitcoin/Base/ChainState.cs
some tests were broken with lasts update of this code, this should fix them
the reason is that the chainstate is not constructed nicely and gets date time provider from full node which may not be initialized
=> fix availability of DTP for tests

src/Stratis.Bitcoin.Features.Miner/Controllers/MinerController.cs, src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
* I also tidied up a few bits in the WalletManager and in the MinerController.
* I'm also assigning null to the pos async loop after it's disposed. the way it is at the moment, before we start staking, we check for nulity of the async loop. So if it's not null, staking will never restart.
This PR is better reviewed commit by commit.
@dangershony @Aprogiena @fassadlr
=> Added iscoinStake in coinStake transactions 

Documentation/coding-style.md
=> Added a few coding style rules

src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
otherwise it seems we may have banned the node before it can inform us about its whole chain
=> only apply long reorg protection if we are dealing with longer chain

src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs, src/Stratis.Bitcoin/Connection/PeerBanning.cs, src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
this should make sure ban reason is filled, previously it was not filled anywhere (eh?)
=> always have ban reason filled

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
- transactionData that are outputs of stake transactions are excluded
- after spending details for staking transactions are processed, we keep processing in case the transaction being spent itself is not a stake transaction.
In any case, I think the logic in History need to be reviewed and simplified.
The way we currently decide whether a transaction should be shown or not could be made more flat and processed on a case-by-case basis, as opposed to the way we do it now, which feels a bit like we trying to "figure it out all at once".
=> Added a bit more logic to History

src/Stratis.Bitcoin.Features.BlockStore/BlockPair.cs
Added xmldoc for BlockPair and an assert that ensures that chained block was created from the block provided.
=> [BlockPair] Tiny PR that adds some comments and Assert to the BlockPair

src/NBitcoin.Tests/Bech32Test.cs, src/NBitcoin.Tests/ChainTests.cs, src/NBitcoin.Tests/ColoredCoinsTests.cs, src/NBitcoin.Tests/NetworkTests.cs, src/NBitcoin.Tests/NodeBuilder.cs, src/NBitcoin.Tests/NodeBuilderStratis.cs, src/NBitcoin.Tests/PaymentTests.cs, src/NBitcoin.Tests/RPCClientTests.cs, src/NBitcoin.Tests/RestClientTests.cs, src/NBitcoin.Tests/bip32_tests.cs, src/NBitcoin.Tests/bip39_tests.cs, src/NBitcoin.Tests/hash_tests.cs, src/NBitcoin.Tests/pos_hash_tests.cs, src/NBitcoin.Tests/pos_pow_tests.cs, src/NBitcoin.Tests/pos_transaction_tests.cs, src/NBitcoin.Tests/script_tests.cs, src/NBitcoin.Tests/sigopcount_tests.cs, src/NBitcoin.Tests/transaction_tests.cs, src/Stratis.StratisD/Properties/launchSettings.json
just to make cleaner compilations, but some are still unresolved
=> resolve some compiler warnings

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs, src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
- For Trello item: https://trello.com/c/5i8S6Zde
- Added the capability of re-ordering responses in a round-robin fashion to avoid same peer being queried every time.
- Added unit test.
=> [DNS] Added round-robin ordering of responses

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs, src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
Added the code to periodically save the DNS Master File to disk.
=> DNS Seed Server save master file

src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs, src/Stratis.Bitcoin/BlockPulling/LookaheadBlockPuller.cs
Fix https://github.com/stratisproject/StratisBitcoinFullNode/issues/981
=> Implement Dispose method on LBP

src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NetworkSimulator.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
Fixed test 'MiningNodeWithOneConnectionAlwaysSynced'
=> Fixed integration test

src/Stratis.Bitcoin.Tests/Utilities/AsyncManualResetEventTest.cs, src/Stratis.Bitcoin/Utilities/AsyncManualResetEvent.cs
AsyncManualResetEvent is an async version of ManualResetEventSlim
=> Added AsyncManualResetEvent

src/Stratis.Bitcoin.Features.Dns/README.md
Added a readme for the Stratis DNS daemon
=> Readme for the DNS daemon

src/NBitcoin.Tests/BitcoinUrlBuilder.cs
This PR moves the BitcoinUrlBuilder class to the NBitcoin.Tests.
=> Move BitcoinUrlBuilder to NBitcoin.Tests

src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, src/Stratis.Bitcoin/P2P/PeerConnector.cs, src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs, src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs, src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs
=> Fix requirement initialization for peer connectors

src/Stratis.Bitcoin.Features.Api/ApiFeature.cs, src/Stratis.Bitcoin.Features.Api/ApiSettings.cs, src/Stratis.Bitcoin.Features.Api/Program.cs, src/Stratis.Bitcoin.IntegrationTests/APITests.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.BreezeD/Program.cs
This PR adds a settings class to the Api Feature to be consistent with the other features.
=> Move ApiFeature-specific NodeSettings into ApiSettings class

src/NBitcoin.Tests/NBitcoin.Tests.csproj
Fixes warning "MSB3277: Found conflicts between different versions..."
=> Update NBitcoin Test nuget packages to latest version

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs, src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs, src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs, src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs, src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs, src/Stratis.Bitcoin.Features.Dns/DnsSettings.cs, src/Stratis.Bitcoin.Features.Dns/IFullNodeBuilderExtensions.cs, src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.StratisDnsD/Program.cs
This PR moves the settings related to the DNS feature from the NodeSettings class to a new DnsSettings class.
=> Move Dns settings into separate class

src/Stratis.Bitcoin.Features.Wallet/Broadcasting/BroadcasterManagerBase.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/FullNodeBroadcasterManager.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/LightWalletBroadcasterManager.cs
For the full node (where we have consensus and can validate the tx) changed propagation from 50% of the peers to 100%. 
Fix: #973
=> Propagate tx to 100% of the peers for the full node.

src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs
This PR standardizes the GetOrDefault usage for boolean settings in StoreSettings.cs.
=> Standardize GetOrDefault usage for boolean settings

src/NBitcoin.Tests/transaction_tests.cs, src/NBitcoin/BitcoinSegwitAddress.cs, src/NBitcoin/Coin.cs, src/NBitcoin/KeyId.cs, src/NBitcoin/NBitcoin.csproj, src/NBitcoin/RPC/SatoshiFormatter.cs, src/NBitcoin/TransactionBuilder.cs
Update NBitcoin to 4.0.0.39
These commits were not merged:
https://github.com/MetacoSA/NBitcoin/commit/d8ea26e205d1c96eecdc0dd0c319d9765b75a856
https://github.com/MetacoSA/NBitcoin/commit/a19f006ee7da2ee40fd89d325fa589de971f7632
https://github.com/MetacoSA/NBitcoin/commit/dcb47ab4b7573e4df25f8f0a84a455adf3d3dce5
https://github.com/MetacoSA/NBitcoin/commit/dfe386af569fe4811565e826a73e7edf79568b87
https://github.com/MetacoSA/NBitcoin/commit/56bfd1cbca535424b160d8a40688a79de4800630
https://github.com/MetacoSA/NBitcoin/commit/d1bd95e29c621ebcd3e2f233274887583184543c
https://github.com/MetacoSA/NBitcoin/commit/66b2839a72bd8b9aa8372ecdecb46408f9962335
https://github.com/MetacoSA/NBitcoin/commit/3ecb770990cb27ed9f8962e2fd7f2c05e689776f
https://github.com/MetacoSA/NBitcoin/commit/d6e603aabbb87aead …
=> Update NBitcoin part 1

src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs, src/Stratis.Bitcoin/P2P/PeerAddress.cs
=> [PeerAddress] Update peer address to correctly determine when the last peer connection or handshake was made

src/NBitcoin.Tests/transaction_tests.cs, src/NBitcoin/Transaction.cs, src/NBitcoin/TransactionBuilder.cs
This PR merges in the following commits which were identified as desirable in review of https://github.com/stratisproject/StratisBitcoinFullNode/pull/1009
https://github.com/MetacoSA/NBitcoin/commit/56bfd1cbca535424b160d8a40688a79de4800630
https://github.com/MetacoSA/NBitcoin/commit/d1bd95e29c621ebcd3e2f233274887583184543c
See Issue #1008
=> Update NBitcoin - Part 2

src/Stratis.Bitcoin.Tests/Utilities/AsyncLoopTest.cs, src/Stratis.Bitcoin/Utilities/AsyncLoop.cs
Plus added a test for this behavior.
=> Allow AsyncLoop.RepeatEvery interval to be changed after the loop was started. 

src/NBitcoin.Tests/util_tests.cs, src/NBitcoin/BitcoinSegwitAddress.cs, src/NBitcoin/BitcoinStream.Partial.cs, src/NBitcoin/ConcurrentChain.cs, src/NBitcoin/NBitcoin.csproj, src/NBitcoin/PubKey.cs, src/NBitcoin/RPC/RPCClient.cs
Update NBitcoin to 4.0.0.48 (Dec 6/17)
These commits were not merged:
https://github.com/MetacoSA/NBitcoin/commit/219bd1361595c125027d66a769f0fe447585de91
https://github.com/MetacoSA/NBitcoin/commit/2af3beb91750203c9d6acea010c94f93ccfd9420
https://github.com/MetacoSA/NBitcoin/commit/6a235c1f3b2fed8109ade3cdac7413c7be9a51a2
https://github.com/MetacoSA/NBitcoin/commit/1ec06602976fe19aba23d499e68a81d9ec3d613c
https://github.com/MetacoSA/NBitcoin/commit/1ee8e56f9970ead8a577151ada33edb721b2ee68
https://github.com/MetacoSA/NBitcoin/commit/1ee8e56f9970ead8a577151ada33edb721b2ee68 
These commits were merged:
https://github.com/MetacoSA/NBitcoin/commit/dc52fcd3b2e2ba607779d37f24102376c44043b1
https://github.com/MetacoSA/NBitcoin/commit/c0a5cc71fb9f797acf00a6f7c203057b951929c1 …
=> Update NBitcoin - Part 3

src/Stratis.Bitcoin/P2P/PeerConnector.cs
Fixes the bug with high threads usage.
=> Peer connector threads usage optimizations 

src/Stratis.Bitcoin.Tests/Utilities/AsyncManualResetEventTest.cs
Tests consistency improvement.
=> Tests consistency fix

src/NBitcoin/BIP9Deployments.cs, src/NBitcoin/Networks.cs, src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs, src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs, src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs
Fix #1028 
Fix #1027
Also added SegWit activation parameters for Bitcoin Mainnet as per bitcoin core.
=> Fix issue with SegWit not activating on Bitcoin RegTest and fix incorrect constant

src/Stratis.Bitcoin.IntegrationTests/P2P/PeerConnectionTests.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerFactory.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs, src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs
This just removes network peer's dependency on NetworkAddress + modifications in other components that were affected.
=> Node job part 22

src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs
=> Check that segwit activates on a c# node

src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs, src/Stratis.Bitcoin/P2P/PeerSelector.cs, src/Stratis.StratisD/Properties/launchSettings.json
=> [PeerSelector] Fix ConcurrentDictionary threading issues

src/Stratis.Bitcoin.Tests/Utilities/AsyncLoopTest.cs, src/Stratis.Bitcoin.Tests/Utilities/AsyncManualResetEventTest.cs
Don't merge it, I'd like to trigger travis running the tests a few times.
=> Tests environmental consistency

src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerTests.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs, src/Stratis.Bitcoin/P2P/PeerAddress.cs, src/Stratis.Bitcoin/P2P/PeerAddressManager.cs, src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs
=> [P2P] Remove LastSeen from NetworkPeer and create on PeerAddress

src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs, src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs, src/Stratis.Bitcoin.Features.Notifications/AssemblyInfo.cs
Added missing unit tests for the notification feature project.
=> Notification feature tests

src/Stratis.Bitcoin.Features.Consensus/ConsensusErrors.cs, src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs
=> Missing POS rule to check a user transaction output is valid

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
Checking if GetBlock() return null then set hashBlock as a uint256.Zero
=> BugFix: Prevent null exception if block for minting is null(#803)

src/NBitcoin.Tests/BitcoinUrlBuilder.cs, src/NBitcoin.Tests/NodeBuilder.cs, src/NBitcoin.Tests/RPCClientTests.cs, src/NBitcoin.Tests/RepositoryTests.cs, src/NBitcoin.Tests/RestClientTests.cs, src/NBitcoin/BitcoinCore/CoinsView.cs, src/NBitcoin/BitcoinCore/IndexedBlockStore.cs, src/NBitcoin/BitcoinCore/IndexedStore.cs, src/NBitcoin/ITransactionRepository.cs, src/NBitcoin/NBitcoin.csproj, src/NBitcoin/Network.cs, src/NBitcoin/NoSqlRepository.cs, src/NBitcoin/OpenAsset/ColoredTransaction.cs, src/NBitcoin/OpenAsset/Extensions.cs, src/NBitcoin/OpenAsset/IColoredTransactionRepository.cs, src/NBitcoin/RPC/RPCClient.Wallet.cs, src/NBitcoin/RPC/RPCClient.cs, src/NBitcoin/RPC/RPCOperations.cs, src/NBitcoin/RPC/RPCRequest.cs, src/NBitcoin/RPC/RestClient.cs, src/NBitcoin/TransactionBuilder.cs, src/NBitcoin/Utils.cs
Update NBitcoin to 4.0.0.51
These commits were not merged:
https://github.com/MetacoSA/NBitcoin/commit/0d683cef6356ad56d0b5385b7e00d24ee4b56458
https://github.com/MetacoSA/NBitcoin/commit/fce310152d379d2e37b55ddb505630506e7059d4
https://github.com/MetacoSA/NBitcoin/commit/c3ec3b81c42b4555a9aa18549b97949104471876
https://github.com/MetacoSA/NBitcoin/commit/7fae4c7b31d2d8cceb1c4cd4f6547d1899ff1a87
https://github.com/MetacoSA/NBitcoin/commit/3a0b9bd5b9768422b2dc2d55ec84a5f6f1d00fee
These commits were already done previously:
https://github.com/MetacoSA/NBitcoin/commit/e6b328463b92d16e194dd1aacc8d70138b315023
https://github.com/MetacoSA/NBitcoin/commit/684054b01e5c463779efaaa252c2c148ed30b5e9
https://github.com/MetacoSA/NBitcoin/commit/7fd1c358b920fdc6c75417f9f2646f2fc0f59585
These commits …
=> Update NBitcoin - Part 4

src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs, src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs, src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/P2P/PeerAddress.cs, src/Stratis.Bitcoin/P2P/PeerAddressManager.cs, src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs, src/Stratis.Bitcoin/P2P/PeerConnector.cs, src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs, src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs, src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs, src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs, src/Stratis.Bitcoin/P2P/PeerSelector.cs
This is part 1 to remove Network Address from the solution.
=> [P2P] Remove NetworkAddress from the solution Part #1

src/NBitcoin/RPC/IRPCClient.cs, src/NBitcoin/RPC/RPCClient.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/AddNodeActionTest.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/BaseRPCControllerTest.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/ConsensusActionTests.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/GetInfoActionTests.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/MempoolActionTests.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/RPCControllerTest.cs, src/Stratis.Bitcoin.Features.RPC.Tests/RPCSettingsTest.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Stratis.Bitcoin.Features.RPC.Tests.csproj, src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs, src/Stratis.Bitcoin.Features.RPC/RPCClientFactory.cs, src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs, src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/BaseRPCControllerTest.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/ConsensusActionTests.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/GetInfoActionTests.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/MempoolActionTests.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCSettingsTest.cs, src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj, src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs, src/Stratis.Bitcoin/IFullNode.cs
- Added missing unit tests for the RPC feature project.
- Moved RPC integration tests to the integration test project.
=> RPC Feature Tests

src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
This PR only cleans up more unit tests.
=> [P2P] Remove NetworkAddress from the solution part #2

src/Stratis.Bitcoin.Tests/Utilities/AsyncLoopTest.cs
Fixes https://github.com/stratisproject/StratisBitcoinFullNode/issues/1081
=> Fix tests in AsyncLoopTest

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs
=> [NetworkPeerServer] Limit maximum inbound connections and stall once it has been reached.

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs
This race condition was happening in this scenario:
1) New block from LookaheahBlockPuller is received
2) ConsensusTip is updated 
3) Loop iteration execution starts and we bump into 
```
if (this.StoreTip.Height >= this.ChainState.ConsensusTip?.Height)
break;
```
and continue to block steps execution => Find blocks step tells the StoreBlockPuller to download the missing block.
4) BlockStoreSignaled gets the block that was signaled by the ConsensusLoop and it is added to the PendingStorage
Fix: #599
=> Fix: BlockStore race condition

src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs, src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs
@345paul can you please take a look as well?
=> DNS seeder to use LastSeen instead of LastConnectionHandshake

src/NBitcoin/Policy/ITransactionPolicy.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs, src/Stratis.Bitcoin/Utilities/ValidationAttributes/MoneyFormatAttribute.cs, src/Stratis.StratisD/Properties/launchSettings.json
Added the option to set custom fees when building a transaction.
If both feeAmount and feeType are set, feeAmount is taken into account.
If none is set, the feeType defaults to "medium".
=> Added custom fees

src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/CoreNode.cs, src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeBuilder.cs, src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeRunners.cs, src/Stratis.Bitcoin/FullNode.cs, src/Stratis.Bitcoin/IFullNode.cs
State enum instead of flags. 
Fix: #826
=> Node state enum

src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/CoreNode.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerFactory.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs, src/Stratis.Bitcoin/P2P/PeerConnector.cs, src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs, src/Stratis.Bitcoin/P2P/Protocol/IncomingMessage.cs, src/Stratis.Bitcoin/P2P/Protocol/Message.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/Payload.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/PayloadAttribute.cs
A payload provider that allows to inject network payloads to the node, this will enable injection of different serialised message types and new payload message types.
Part of the work of moving away from static fields.
=> Payload factory

src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs, src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/Builder/FullNodeBuilder.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.BitcoinD/Program.cs, src/Stratis.BreezeD/Program.cs, src/Stratis.StratisD/Program.cs, src/Stratis.StratisDnsD/Program.cs
This PR refactors the PrintHelp method.
Provides a mechanism by which only the command-line help of the base feature and used features (".UseXXX") are displayed.
=> Refactor PrintHelp

src/Stratis.Bitcoin.Features.Api/ApiFeature.cs, src/Stratis.Bitcoin.Features.Api/ApiSettings.cs
This PR adds a PrintHelp method to the API feature to display command-line help related to the API feature when required.
=> Add PrintHelp method to API feature

src/Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolSettings.cs
This PR adds a PrintHelp method to the Mempool feature to print command-line help for the Mempool feature when required.
=> Add PrintHelp method to Mempool feature

src/NBitcoin/Network.cs, src/NBitcoin/NetworkBuilder.cs, src/NBitcoin/Networks.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TimeSyncBehaviorTest.cs, src/Stratis.Bitcoin/Base/TimeSyncBehavior.cs
Also updated the MaxTimeOffsetSeconds for bitcoin to be 70 minutes like in Bitcoin Core.
https://github.com/stratisproject/StratisBitcoinFullNode/issues/437
=> Moved MaxTimeOffsetSeconds to Network

src/Stratis.Bitcoin/Utilities/AsyncLoop.cs
=> AsyncLoop- increased logging level

src/NBitcoin/ScriptReader.cs
Please change the access for the Op constructor to **public**.
=> changed access modifier for Op ctor

src/Stratis.Bitcoin.Features.Api/Controllers/NodeController.cs, src/Stratis.Bitcoin.Features.Api/MvcBuilderExtensions.cs, src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs, src/Stratis.Bitcoin/FullNode.cs, src/Stratis.Bitcoin/IFullNode.cs, src/Stratis.Bitcoin/Models/ConnectedPeerModel.cs, src/Stratis.Bitcoin/Models/StatusModel.cs
https://github.com/stratisproject/StratisBitcoinFullNode/issues/770
=> Added Status endpoint

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
=> Fix: Staking exception because collection was modified

src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs, src/Stratis.Bitcoin/P2P/PeerAddress.cs, src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
Fix: #1153 
This is one for @345paul and @fassadlr
=> Store only IPv6 or IPv4 in embedded format

src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
=> Check the block that the stake coin was in did not reorg away

src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
=> PeerBanningBehavior detachment fix

src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
=> Fix: StakeValidator.CheckProofOfStake prevUtxo could be null

src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
=> Replace R/W lock with AsyncLock in CachedCoinView

src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
Removed redundant input variables from StakeValidator.CheckStakeKernelHash and updated the entry log
=> StakeValidator.CheckStakeKernelHash redundant variables removal

src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStoreTests.cs, src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/CoreNode.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, src/Stratis.Bitcoin.IntegrationTests/Program.cs, src/Stratis.Bitcoin.IntegrationTests/TestHelper.cs, src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs
With this PR the wallet tests are more stable, however more work will go in to this PR
=> Fixing integration tests

src/Stratis.Bitcoin/P2P/Protocol/Payloads/VersionPayload.cs
=> Fix: Transactions are not relayed to the C++ nodes 

src/Stratis.Bitcoin.Features.Consensus/ConsensusErrors.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderPosContextualRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderPowContextualRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockMerkleRootRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockSizeRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPosTransactionRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckSigOpsRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckpointsRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinbaseHeighRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/EnsureCoinbaseRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinstakeRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosFutureDriftRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/TransactionLocktimeActivationRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/WitnessCommitmentsRule.cs
Updated the consensus rule exception docmentation. Fixed some typo's.
=> Updated consensus rule documentation

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
Fixes a thread safety issue when building a transaction. 
Also fixes https://github.com/stratisproject/FullNodeUI/issues/39
=> Wallet Thread and error message fixes

src/NBitcoin/TransactionBuilder.cs
see [commit already approved into NBitcoin](https://github.com/MetacoSA/NBitcoin/commit/8a3e8924a2d66a975a3b6c9dfa1d4c747964a593).  Updating our copy to match.
=> Typo fix already approved into NBitcoin master

src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification.cs, src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs, src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj.DotSettings, src/Stratis.Bitcoin/Base/BaseFeature.cs
=> Test propagation of transactions

src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs
=> Flag to make sure GetAddrPayload is only sent once.

src/NBitcoin/TransactionBuilder.cs
This is already in master but is needed on release branch too.
=> nbitcoin typo fix already in master

Documentation/using-logging.md
=> Fixed file name

src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
This started after a couple of PR were committed today.
=> Fix Wallet namespace issue.

Documentation/NLog.config
This is an example logging config file that enables details logs for every part of the codebase. Logs are kept for 14 days.
=> Added example logfile

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosFutureDriftRule.cs
This pr is basically created by @Aprogiena
=> Future drift fix

src/Stratis.Bitcoin.Features.Consensus.Tests/CheckpointsTest.cs, src/Stratis.Bitcoin.Features.Consensus/Checkpoints.cs
Fix for https://github.com/stratisproject/StratisBitcoinFullNode/issues/1315 and unit tested the whole class.
=>  Checkpoints are always disabled (#1315)

src/Stratis.Bitcoin.Tests.Common/StaticFlagIsolator.cs
=> Static Flags Issue - Store previous value to restore things as they were before the test

src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/GenerateCoinsFastDateTimeProvider.cs, src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeRunners.cs, src/Stratis.Bitcoin.IntegrationTests/Extensions/CoreNodeExtensions.cs, src/Stratis.Bitcoin.IntegrationTests/Miners/ProofOfStakeMintCoinsSteps.cs, src/Stratis.Bitcoin.IntegrationTests/TestFramework/BddSpecification.cs, src/Stratis.Bitcoin.Tests.Common/StaticFlagIsolator.cs
Implement a fast coins date time provider thats more in line with the node's provider.
This PR ONLY fixes the POW/POS integration tests. I'm still looking into the others.
=> [Tests] Fix POW/POS integration test

src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepBaseTest.cs, src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs, src/Stratis.Bitcoin/Configuration/DataFolder.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs
This is in relation to https://github.com/stratisproject/StratisBitcoinFullNode/pull/1308 and https://github.com/stratisproject/StratisBitcoinFullNode/issues/1307.
@Aprogiena
=> Rooted datadir

src/Stratis.Bitcoin/Configuration/Logging/NLog.config, src/Stratis.StratisD/NLog.config, src/Stratis.StratisD/Stratis.StratisD.csproj
This way the file is more accessible to developers.
=> Added the NLog file to the solution

src/Stratis.Bitcoin/Utilities/FileStorage.cs
So File.Replace didn't really work because deleting the temp file created by Windows sometimes failed.
Now we do what File.Replace does, but manually. We ignore the exception thrown if the temporary file cannot be deleted.
By ignore, I mean we rename the temp file to be a *.del file so it can be picked up later for deletion. How and when is still TBD but this solution is the most defensive one we found.
=> Replace File.Replace 

src/Stratis.Bitcoin.Features.Consensus/ConsensusController.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolController.cs, src/Stratis.Bitcoin.Features.Miner/MiningRPCController.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs, src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs, src/Stratis.Bitcoin/Controllers/FeatureController.cs, src/Stratis.Bitcoin/Controllers/Models/ConnectedPeerModel.cs, src/Stratis.Bitcoin/Controllers/Models/StatusModel.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs
While working on tree header I noticed this blasphemy
=> Move FullnodeController to its correct folder.

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
This should fix #1357 and #1338
=> Fix some staking issues

src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs, src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs
This PR:
- adds `MaxOutboundConnections` to the `ConnectionManagerSettings` class. 
- updates the default configuration file.
- updates command-line help.
=> Add MaxOutboundConnections to ConnectionManagerSettings

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
This PR addresses the GetDepthInMainChain TODO in PosMinting.cs.
=> Address GetDepthInMainChain TODO in PosMinting.cs

src/Stratis.Bitcoin.Tests/Utilities/NetworkHelpersTest.cs
Test was getting argument exception when it was run on its own.
=> Fixed test to be order agnostic.

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreCacheTest.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreCache.cs, src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs, src/Stratis.Bitcoin/P2P/PeerConnector.cs
This PR:
- Adds MaxCacheBlocksCount to StoreSettings and refactors the associated code.
- Adds BurstModeTargetConnectons to ConnectionManagerSettings.
=> Move settings accessed via NodeSettings to appropriate settings classes

src/NBitcoin.Tests/NetworkTests.cs, src/NBitcoin/Block.cs, src/NBitcoin/ChainedHeader.cs, src/NBitcoin/Network.cs, src/NBitcoin/Networks.cs, src/NBitcoin/Networks/BitcoinMain.cs, src/NBitcoin/Networks/BitcoinRegTest.cs, src/NBitcoin/Networks/BitcoinTest.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CalculateStakeRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CalculateWorkRule.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs, src/Stratis.Bitcoin.Features.Miner/PowMining.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs, src/Stratis.Bitcoin.IntegrationTests/ChainBuilder.cs
Added a method to mine a genesis block. 🔢
=> Mine genesis block

src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs, src/Stratis.Bitcoin.Features.Miner/AssemblyInfo.cs, src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs, src/Stratis.Bitcoin.Features.Miner/PosMinting.cs, src/Stratis.Bitcoin.Tests.Common/ReflectionExtensions.cs
Tests that check that UTXOs with correct depth in the chain are eligible for staking.
=> Coinstaske age tests

src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs, src/Stratis.Bitcoin.Tests/Base/ChainRepositoryTest.cs, src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/Base/ChainRepository.cs, src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
=> Added finalized block height

src/NBitcoin.Tests/ChainTests.cs, src/NBitcoin.Tests/DeterministicSignatureTests.cs
This PR:
- Makes the build green again.
=> Make The Build Green Again

src/Stratis.Bitcoin.Features.Consensus/ConsensusController.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolController.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs, src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
Only 4 tests are failing due to a null reference exception.
=> fix rpc methods tests

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
**Fulfils the following tests supporting [RF] Create chained header tree component**
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1321
2) Supply headers that we already have, make sure no new ChainedHeaders were created
3) Supply some headers and after that supply some more headers and make sure that PeerTipsByHash is updated (at the total amount of items is the same)
6) Make sure checkpoints are off- supply some headers, CHT should return ToDownload array of the same size as the amount of headers.
=> Tests for chained header tree

src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
To prevent a possible race condition
=> CHT safety check

src/Stratis.Bitcoin.Features.Api/ApiSettings.cs, src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs, src/Stratis.Bitcoin.Features.Dns/DnsSettings.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolSettings.cs, src/Stratis.Bitcoin.Features.Miner/MinerSettings.cs, src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs, src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs, src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/ConsensusSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/LogSettings.cs, src/Stratis.Bitcoin/Configuration/TextFileConfiguration.cs
This PR:
- Adds an ILogger parameter to the TextFileConfiguration Get methods and updates the calling code.
This change was requested on https://github.com/stratisproject/StratisBitcoinFullNode/pull/1478.
=> Adds an ILogger parameter to the TextFileConfiguration Get methods

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Runners/CustomRunner.cs
This is needed for sidechains integration testing, where we need to pass known ports to localhost nodes to connect them together
=> Add possibility to start custom nodes with custom args

src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
Change block data availability if block store is disabled
=> CHT bugfix

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
BlockDataDownloaded called for some blocks. Make sure CH.Block is not null and for the first block true is returned and false for others
=> CHT test: BlockDataDownload for valid blocks - issue 24

src/Stratis.Bitcoin.Tests.Common/ReflectionExtensions.cs
Added 2 more reflection extensions
=> Reflection extensions

src/NBitcoin.Tests/NetworkTests.cs, src/NBitcoin/Networks.cs, src/NBitcoin/Networks/BitcoinMain.cs, src/NBitcoin/Networks/StratisMain.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TimeSyncBehaviorTest.cs
Moves network-specific static/const members into the appropriate Network classes
=> Separate Stratis and Bitcoin static/const members from Networks

src/NBitcoin/IBitcoinSerializable.cs, src/NBitcoin/JsonConverters/BitcoinSerializableJsonConverter.cs, src/NBitcoin/JsonConverters/Serializer.cs
Raised by PistolPete in discord
=> [Bug] Null reference in BitcoinSerializableJsonConverter

src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs, src/Stratis.Bitcoin/Utilities/FileStorage.cs
This PR:
- Adds support for passing JsonSerializerSettings to LoadByFileName
- Adds support for deserialization of PosTransaction in WatchOnlyWallet
=> Support deserialization of PosTransaction in WatchOnlyWallet

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
Gap limit is now configurable via Wallet Settings
PR level lowish
=> Gap limit configurable

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility.cs
=> Wallet to use address buffer on startup

src/Stratis.Bitcoin.Tests.Common/ReflectionExtensions.cs, src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTests.cs, src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTestsHelper.cs, src/Stratis.Bitcoin/BlockPulling2/BlockPuller.cs, src/Stratis.Bitcoin/BlockPulling2/BlockPullerBehavior.cs, src/Stratis.Bitcoin/BlockPulling2/DownloadJob.cs
Tests for the new block puller
=> BlockPuller tests

tash show p
@thefazzer was this pushed in by mistake?
=> remove-stash-file

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs, src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
Check if fork-point is below finalized block, not the same.
=> CHT finalized height bugfix

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
**Initial commit Issue 35 (#1321)**
- (first header in the message is HEADERS_START and last is HEADERS_END).
- AV = assume valid header, CP1,CP2 - checkpointed headers. '---' some headers.
- LAST_CP = last checkpoint.
- ----CP1-----HEADERS_START----LAST_CP----AV-----HEADERS_END
- All headers until HEADERS_END (including it) are marked for download.
Preferred: @Aprogiena @noescape00
=> Issue 35 Initial check in (#1321)

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
**Initial commit Issue 34 (#1321)**
_(first header in the message is HEADERS_START and last is HEADERS_END).
AV = assume valid header, CP1,CP2 - checkpointed headers. '---' some headers._
- CP1---HEADERS_START---AV---HEADERS_END---CP2---
- Check that headers till AV(including AV) are marked for download.
- Headers after AV are not marked for download.
Preferred: @Aprogiena @noescape00
=> Initial commit Issue 34 (#1321)

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
**Initial commit Issue 31 (#1321)**
- Chain is 2 blocks long.
- CT is header 1.
- Call PartialValidationSucceeded on header 2.
- Make sure that reorg that is returned is true.
=> Initial commit Issue 31 (#1321)

src/NBitcoin.Tests/util_tests.cs, src/NBitcoin/Coin.cs, src/Stratis.Bitcoin.Features.Api/Startup.cs, src/Stratis.Bitcoin.Features.RPC/Startup.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RemovedTransactionModel.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletHistoryModel.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs, src/Stratis.Bitcoin.Tests/Utilities/JsonConverterTests.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/AssetIdJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/BitcoinSerializableJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/BitcoinStringJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/CoinJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/DateTimeOffsetConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/DateTimeToUnixTimeConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/HexJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/IPEndPointConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/JsonObjectException.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/KeyJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/KeyPathJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/LockTimeJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/MoneyJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/NetworkJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/ScriptJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/Serializer.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/SignatureJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/TxDestinationJsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/UInt160JsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/UInt256JsonConverter.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/UIntJsonConverter.cs
Moving these because they're sitting at the top of NBitcoin but can easily be moved to Stratis.Bitcoin.
=> Moved Json converters to the Stratis.Bitcoin project

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
**Cht tests fazzdev #1321 47**
- CT is at 5. Checkpoints are at 10 and 20.
- ConnectNewHeaders called with 9 new headers (from peer1).
- After that ConnectNewHeaders called with headers 5 to 15 (from peer2).
- Make sure 6 - 10 are requested for download.
**_Note: Need feedback on line @ 2320_**
Preferred: @Aprogiena @noescape00
=> Cht tests fazzdev #1321 47

src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs, src/Stratis.Bitcoin.Features.Miner/BlockProvider.cs, src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs, src/Stratis.Bitcoin.Features.Miner/PosPowBlockDefinition.cs, src/Stratis.Bitcoin.Features.Miner/PowMining.cs, src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
=> [Mining] Add the ability to create proof of work blocks on a proof of stake network.

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs, src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs, src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs
Slightly optimized CHB. This is the 1st PR to get CHB ready for the CHT and CM activation. 
Tests pass, networks synced
=> CHB optimization

src/NBitcoin/QBitNinjaTransactionRepository.cs
This should be the last part before we start moving the network classes.
=> Cleanup network usage in NBitcoin #7

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
=> CHT tests: Sorted tests by issue #

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowApiRunner.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs, src/Stratis.Bitcoin/Utilities/FileStorage.cs
This PR:
- Fixes issue #1554 and updates associated unit tests.
- Adds integration tests for API endpoints, noted to be missing in #1554.
- Added CreateStratisPowApiNode to facilitate testing API functions with transactions/mining. 
- Adds an exception handler to FileStorage. This [unhandled exception](https://msdn.microsoft.com/en-us/library/system.io.file.delete(v=vs.110).aspx) was thrown when SaveWallet was attempting to delete a file.
All added integration test pass. Some unrelated tests (Wallet integration tests, mostly) not touched by this PR are failing when I run locally.
=> Fix for issue #1554 + missing API integration tests

src/Stratis.Bitcoin.Features.RPC/RPCClient.cs
@monsieurleberre please make sure you run integration tests next time.
=> Role back a commit

src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChain.cs, src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChainNode.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
This PR was sitting in VSTS for a while. 
Significantly simplifies our SmartContractWalletTests, and will allow us to spec out more contracts + functionality without the clutter of setting up new nodes in the same way every time.
May be used locally by developers looking to run a local development chain in the future - we could expose it publicly via NuGet.
=> [SC] MockChain for simpler integration testing and public use in future

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
As requested in issue https://github.com/stratisproject/StratisBitcoinFullNode/issues/1391
=> Made block signature validation rule non-skippable

src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
=> Fixed sorting issue with concurrent dictionary

src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Tests.Common/ChainedHeadersHelper.cs, src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs, src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTestsHelper.cs, src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTests.cs, src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTestsHelper.cs, src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs, src/Stratis.Bitcoin/Base/ConsensusManagerBehavior.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
=> CMB tests. Part1

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnectionParameters.cs
Reference NBitcoin commit:
https://github.com/MetacoSA/NBitcoin/commit/6ae1452e8e5252f3ea7aee3028d882199fe8e66a
Fixes #1173
=> Merge NBitcoin fix for MacOSX buffer sizes

src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
=> Assign SmartContracts Consensus settings directly

src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs, src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
=> Fixes for comments and warnings

src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/MinerControllerTest.cs, src/Stratis.Bitcoin.Features.Miner.Tests/MiningRPCControllerTest.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs, src/Stratis.Bitcoin.Features.Miner/Interfaces/IPosMinting.cs, src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs, src/Stratis.Bitcoin.Features.Miner/PosMinting.cs, src/Stratis.Bitcoin.Features.Miner/Staking/CoinstakeContext.cs, src/Stratis.Bitcoin.Features.Miner/Staking/CoinstakeWorkerContext.cs, src/Stratis.Bitcoin.Features.Miner/Staking/CoinstakeWorkerResult.cs, src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs, src/Stratis.Bitcoin.Features.Miner/Staking/UtxoStakeDescription.cs, src/Stratis.Bitcoin.Features.Miner/Staking/WalletSecret.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/GenerateCoinsFastDateTimeProvider.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
Split the big PosMinting class before more changes
=> Split posminting class

src/Stratis.Bitcoin.Features.Miner/Controllers/MiningApiController.cs
I noticed when I created the `MiningApiController` based on the `MiningRPCController` it was still throwing RPC type exceptions, which is wrong.
This small PR is to throw a normal exception.
Related to work carried out in #1691.
=> GetAccount was throwing a RPCServerException which is not correct.

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
Need to add functionality to this method in other PRs to write more tests for the WalletTransactionHandler. Not keen on adding to that multiple return.
=> Extendable 'SetupWallet' method. 

src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
=> fix-staking-api-test: name of the controller has changed

Documentation/commenting-policy.md
To stop long discussions about commenting this will relax a bit the commenting policy.
=> Update to commenting policy

src/NBitcoin/Consensus.cs, src/NBitcoin/Network.cs, src/NBitcoin/Rules/IConsensusRule.cs, src/NBitcoin/Rules/IRuleRegistration.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/PosConsensusRulesRegistrationTests.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/PowConsensusRulesRegistrationTests.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRulesExtension.cs, src/Stratis.Bitcoin.Features.MemoryPool.Tests/FullNodeBuilderTest.cs, src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs, src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/ReflectionRuleRegistrationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TestRulesContext.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/ReflectionRuleRegistration.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/ReflectionVirtualMachineFeature.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractRuleRegistration.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs, src/Stratis.Bitcoin/Consensus/Rules/ConsensusRule.cs, src/Stratis.Bitcoin/Consensus/Rules/ConsensusRules.cs, src/Stratis.Bitcoin/Consensus/Rules/IConsensusRules.cs, src/Stratis.Bitcoin/Consensus/Rules/IRuleRegistration.cs
=> [RF] Move rules to NBitcoin.Consensus

src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
Added coverage over existing method that was missing the coverage
=> Added coverage to ban and disconnect peer

src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs
* Adds test for multiple GetAddr calls.
* Adds test for Outbound GetAddr requests.
* Adds logic for Outbound denial.
* Adds logging for above cases inside Behaviour.
Fixes #637
=> Test for and prevent fingerprint attack

src/NBitcoin/BlockStake.cs, src/Stratis.Bitcoin/Mining/BlockTemplate.cs
Hey guys, we have a big merge coming into master from sc-dev soon. 
The only changes to the FN are the ones in here - so you won't have to worry about reviewing that PR.
Plan going forward is to always separate core FN changes and SC changes, so you can review everything important to the FN :)
Would be great to get this merged in straight away, as mentioned changes are pretty trivial
=> Trivial changes to set up for another sc-dev merge to master

src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletOnPosNetworkTests.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs, src/Stratis.SmartContracts.Core/NewContractAddressExtension.cs, src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs, src/Stratis.SmartContracts.Executor.Reflection/NewContractAddressExtension.cs, src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs, src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionContext.cs
Precursor to the rest of contract creation.
Closes #1864.
=> [SC] Addresses generated with nonce that increments with each create.

src/NBitcoin/Block.cs, src/NBitcoin/BlockHeader.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin.Tests/Base/ChainRepositoryTest.cs, src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs, src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/Base/ChainRepository.cs, src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs, src/Stratis.Bitcoin/Utilities/DBreezeSerializer.cs, src/Stratis.Bitcoin/Utilities/HashHeightPair.cs
=> [Activation] save hash and height for block store and finalized block

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs
=> [Activation] block store behavior todos

src/Stratis.Bitcoin.Features.SmartContracts/SmartContractVersionProvider.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.SmartContracts.Tools.Sct/Properties/launchSettings.json, src/Stratis.SmartContracts/Stratis.SmartContracts.csproj
* Update versions for v0.11.0-alpha
* Also includes a hotfix for agentprefix
=> Version updates for SC v0.11.0-alpha

src/Stratis.Bitcoin.Features.MemoryPool/Interfaces/ITxMempool.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolPersistence.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs, src/Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs
This is related to issue #1818 
I was unable to reproduce the issues reported in the above issue so added some trace logging which hopefully will give us a way to debug if it happens again in production.
=> Add trace logging to mempool feature

src/Stratis.Bitcoin.Features.MemoryPool/Interfaces/ITxMempool.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolPersistence.cs, src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs, src/Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs, src/Stratis.Bitcoin.Features.Miner/Models/GetStakingInfoModel.cs, src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs, src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractPosRegTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs, src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
I need @codingupastorm @rowandh @ferdeen @mikedennis and @kogot to look at this as it's their code that has moved to the activation branch.
@noescape00 @fassadlr The code compiles, that's all I can say.
=> [Activation] Merge from master

src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
Closes #1848
2 lines of code,  nothing outstanding.
=> PeerBanningBehaviour is peer whitelisted.

src/NBitcoin/BitcoinCore/CoinsView.cs, src/NBitcoin/BlockHeader.cs, src/NBitcoin/ChainedHeader.cs, src/NBitcoin/Network.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreControllerTests.cs, src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs, src/Stratis.Bitcoin.Features.BlockStore/Models/BlockTransactionDetailsModel.cs, src/Stratis.Bitcoin.Features.BlockStore/Models/SearchByHashRequest.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs, src/Stratis.Bitcoin.Features.Consensus/Interfaces/IStakeValidator.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinviewRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PowCoinviewRule.cs, src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractPosCoinviewRule.cs, src/Stratis.Bitcoin/Base/Deployments/DeploymentFlags.cs, src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs, src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs, src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs
@noescape00 @fassadlr should be pretty straight-forward.
=> Merge from master - 3 PRs of 15/08/2018

src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs, src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs
=> [SC] Closes #1942 reuse ModuleDefinition

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismErrorMessageTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/FormatValidationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractCompilerTests.cs, src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs, src/Stratis.SmartContracts.Core.Validation/ISmartContractValidator.cs, src/Stratis.SmartContracts.Core.Validation/SmartContractDeterminismValidator.cs, src/Stratis.SmartContracts.Core.Validation/SmartContractFormatValidator.cs, src/Stratis.SmartContracts.Core.Validation/SmartContractValidator.cs, src/Stratis.SmartContracts.Core.Validation/SmartContractWarningValidator.cs, src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs, src/Stratis.SmartContracts.Executor.Reflection/ISmartContractDecompilation.cs, src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs, src/Stratis.SmartContracts.Executor.Reflection/SmartContractDecompilation.cs, src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs, src/Stratis.SmartContracts.Tools.Sct/SctDeterminismValidator.cs, src/Stratis.SmartContracts.Tools.Sct/Validation/Validator.cs, src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
* Change validator signature to accept ModuleDefinition
* Move SmartContractDecompilation to Executor.Reflection
* Move injection, validation, and type responsibilities to SmartContractDecompilation
* Extract ISmartContractDecompilation interface
=> [SC] SmartContractDecompilation refactoring

src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs
Closes #1941. Injects all overloads of a method with that name. 
This approach was chosen as it's easier and quicker to inject all overloads rather than match the correct overload by parameters. Matching the overload requires mapping parameter types from SR -> Cecil and handling inheritance hierarchies etc. which becomes reflection expensive.
=> [SC] Inject all overloads of a method with gas metering

src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
Fixed: CreateExtPubKeyOnlyWallet_creates_wallet_with_extra_flag & AddNewAccount_for_xpub_only_wallet_informs_user_to_create_new_wallet_
=> [Integration tests] API.ApiSpecification

src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
=> [Activation] Merge from master - 20082018

src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
Reated to https://github.com/stratisproject/StratisBitcoinFullNode/issues/1936
Fixed 9 PosBlockAssemblerTest tests.
@noescape00 @fassadlr
=> [Activation] Fixed PosBlockAssemblerTest tests

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismErrorMessageTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/FormatValidationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractCompilerTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs, src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs, src/Stratis.SmartContracts.Executor.Reflection/Compilation/ContractModuleDefinitionReader.cs, src/Stratis.SmartContracts.Executor.Reflection/Compilation/IContractModuleDefinitionReader.cs, src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs, src/Stratis.SmartContracts.Executor.Reflection/ContractModuleDefinition.cs, src/Stratis.SmartContracts.Executor.Reflection/IContractModuleDefinition.cs, src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs, src/Stratis.SmartContracts.Tools.Sct/SctDeterminismValidator.cs, src/Stratis.SmartContracts.Tools.Sct/Validation/Validator.cs, src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
* Rename `ISmartContractDecompilation` to `IContractModuleDefinition`
* Extract module definition reader interface
* Add module definition reader implementation
=> [SC] Introduce IContractModuleDefinitionReader

src/Stratis.Bitcoin/P2P/PeerConnector.cs, src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs, src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs
=> Add delay & parallelise node connections

src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs, src/Stratis.SmartContracts.Executor.Reflection/ContractModuleDefinition.cs, src/Stratis.SmartContracts.Executor.Reflection/IContractModuleDefinition.cs, src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
=> [SC] Dispose of ContractModuleDefinition

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractExecutorTestContext.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
Makes it easier to update tests when execution classes change.
=> [SC] TestContext when testing all instantiated types

src/Stratis.Bitcoin.Features.MemoryPool/BlocksDisconnectedSignaled.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
=> [Activation] Signal on block disconnected from CM

src/Stratis.Bitcoin.Features.Consensus/ConsensusController.cs, src/Stratis.Bitcoin/Controllers/FeatureController.cs
Consensus Manager wasn't set in the ConsensusController.
=> [Activation] Fix a few API integration tests

src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
As reading the documentation to try to understand it, noticed a couple of sentence improvements
=> A couple of typo/sentencing corrections

src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
Removed 45 unimplemented tests.
Added them to Issue #2027 so they can be implemented when it is a priority.
=> [Activation] Removed mempool validator tests that aren't implemented

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CoinbaseHeightRuleTest.cs
**Fix failing tests in CoinbaseHeightRuleTest**
_Populates ChainedHeaderToValidate._
=> Fix failing tests in CoinbaseHeightRuleTest

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs, src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs, src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
=> [Activation] Do BlockIntegrity check outside of lock

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/PersistentReceiptRepositoryTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/ReceiptSerializationTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/ReceiptResponse.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs, src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChainNode.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs, src/Stratis.SmartContracts.Core/Receipts/Receipt.cs
=> [SC] Receipt retrieval via controller

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/TransactionLocktimeActivationRuleTest.cs
Fix failing unit tests - `TransactionLocktimeActivationRuleTest`.
=> [Activation] Fix failing tests - TransactionLocktimeActivationRuleTest.

src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs, src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
Linked to https://github.com/stratisproject/StratisBitcoinFullNode/issues/2020
=> [Activation] Fixed Notifications tests

src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractResultTransferProcessorTests.cs, src/Stratis.SmartContracts.Executor.Reflection/SmartContractResultTransferProcessor.cs
=> [SC] Transfer processor tests fix

src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/WitnessCommitmentsRule.cs, src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs, src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTests.cs, src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTestsHelper.cs, src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs, src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs, src/Stratis.Bitcoin/Consensus/ValidationContext.cs
=> [Activation] Witness requirments

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ByteArrayConversionTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractLogHolderTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/PersistentStateSerializerTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/ByteArrayConversion.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/StorageDemo.cs, src/Stratis.SmartContracts.Executor.Reflection/Exceptions/PersistentStateSerializationException.cs, src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/ContractPrimitiveSerializer.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/IContractPrimitiveSerializer.cs, src/Stratis.SmartContracts.Executor.Reflection/SmartContractState.cs, src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs, src/Stratis.SmartContracts/ISerializer.cs, src/Stratis.SmartContracts/ISmartContractState.cs, src/Stratis.SmartContracts/SmartContract.cs
=> [SC] Byte serialization

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/ReflectionRuleRegistrationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/ISmartContractCoinviewRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/SmartContractPosConsensusRuleEngine.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/SmartContractPowConsensusRuleEngine.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractPosPowBlockDefinition.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs, src/Stratis.SmartContracts.Core/Util/GetSenderResult.cs, src/Stratis.SmartContracts.Core/Util/ISenderRetriever.cs, src/Stratis.SmartContracts.Core/Util/SenderRetriever.cs
This makes it much simpler to test the BlockDefinitions and SmartContractRules
=> [SC] Injection of ISenderRetriever

src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerBehaviorTests.cs, src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTests.cs, src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTestsHelper.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs, src/Stratis.Bitcoin/BlockPulling/BlockPullerBehavior.cs
=> [Activation] block puller peers speed estimation

src/NBitcoin/BlockLocator.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreBehaviorTest.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs
=> Disconnect peers that send large locators

src/Stratis.Bitcoin.Features.SmartContracts.Tests/P2PKHNotContractRuleTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/P2PKHNotContractRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractMempoolValidator.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractPosRuleRegistration.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractPowRuleRegistration.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMemoryPoolTests.cs
=> [SC] No P2PKH to contracts

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractLogHolderTests.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/Auction.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ContractCreation.cs, src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs, src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/RawLog.cs, src/Stratis.SmartContracts/DeployAttribute.cs, src/Stratis.SmartContracts/IndexAttribute.cs
=> [SC] Index for logs

src/NBitcoin/UInt256.cs
Fix: #2092
also see https://github.com/stratisproject/StratisBitcoinFullNode/pull/2122
=> speedup uint256 and uint160 GetHashCode

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
=> [Activation] Fix MempoolReceiveFromManyNodes

src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
=> initialize the fileStorage for peers only once in the ctor

src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
=> [SC] Fix smart contract daemon version

src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasPriceListTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ObserverTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs, src/Stratis.SmartContracts.Executor.Reflection/GasPriceList.cs, src/Stratis.SmartContracts.Executor.Reflection/MeteredPersistenceStrategy.cs
=> [SC] Cost for storage retrieval

src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin.Tests.Common/ConsensusManagerHelper.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContractMinerTests.cs, src/Stratis.SmartContracts.IntegrationTests/xunit.runner.json
Our miner tests were broken somewhere along the way, this fixes
All Miner Tests passing.
=> Fix SC integration tests and allow shared ConsensusManagerHelper

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractPrimitiveSerializerTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs
=> [SC] Tests around Nullable Types

src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs, src/Stratis.Bitcoin/FullNode.cs
this one is pretty small
Fix: #2237
=> FullNode.cs disposable resources

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/LoadCoinviewRule.cs, src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
This PR will improve test speed by up to 50%
Before
```
start time = 2906ms
mine time = 8284ms
connet time = 13960ms
sync time = 19ms
shut down time = 4293ms
total = 29462ms
```
After
```
start time = 5121ms
mine time = 1047ms
connect time = 649ms
sync time = 1359ms
shut down time = 7102ms
total = 15278ms
```
=> Improve test speed

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorFixture.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
=> [SC] Add remaining Executor specification tests

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
Logs have been accumulated for each tests (as its a static collection so each node start will create logs)
=> Disable logs for testing

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/Inheritance.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
Specifies currently expected behaviour when contracts inherit from one another.
=> [SC] Inheritance determinism test

src/Stratis.Bitcoin.Features.SmartContracts.Tests/InternalExecutorSpecification.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/InternalExecutorTestFixture.cs, src/Stratis.SmartContracts.Executor.Reflection/InternalExecutor.cs
=> [SC] Add internal executor specification tests

src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractScriptTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/MempoolOpSpendRule.cs, src/Stratis.SmartContracts.Core/SmartContractScript.cs
=> [SC] Fix mempool op spend rule and stop using ToOps

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
This is a proposed fix to simplify the condition when partial validation completes.
This is to be discussed on the PR and not merged yet.
=> Simplify conditions when PV success

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
MaxBlocksToAskFromPuller changed from 30k to 10k
=> CM: changed constant

src/Stratis.Bitcoin/Consensus/PerformanceCounters/ConsensusManager/ConsensusManagerPerformanceCounter.cs, src/Stratis.Bitcoin/Consensus/PerformanceCounters/ConsensusManager/ConsensusManagerPerformanceSnapshot.cs
simplified the ConsensusManagerPerformance Counter/Snapshot
fixed a bug in Tick to MS conversion
=> changes to ConsensusManagerPerformance Counter/Snapshot

src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs, src/Stratis.SmartContracts.Core.Validation/FormatPolicy.cs, src/Stratis.SmartContracts.Core.Validation/Validators/Module/ContractToDeployValidator.cs, src/Stratis.SmartContracts.Executor.Reflection/Compilation/ContractCompiler.cs
=> [SC] Deploy Attribute validator

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
using this.network.Consensus.Options.MaxBlockBaseSize instead of Block.MaxBlockSize
=> Changed MaxBlockSize property

src/Stratis.SmartContracts.IntegrationTests/ContractInternalTransferTests.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/MultipleNestedCalls.cs, src/Stratis.SmartContracts.IntegrationTests/Stratis.SmartContracts.IntegrationTests.csproj
=> [SC] Demo test that internal transfer ordering issue is fixed

src/Stratis.Bitcoin.Features.SmartContracts.Tests/CallDataSerializerTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodParameterStringSerializerTests.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/MethodParameterDataType.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/MethodParameterStringSerializer.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContractWalletTests.cs
* Remove short and sbyte datatypes
* Reorder other data types logically
Part of #1830.
=> [SC] Remove and reorder method parameter data types

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractPrimitiveSerializerTests.cs, src/Stratis.SmartContracts.Executor.Reflection/PersistentState.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/ContractPrimitiveSerializer.cs, src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs, src/Stratis.SmartContracts/IPersistentState.cs, src/Stratis.SmartContracts/ISerializer.cs
=> [SC] Array serialization methods in PersistentState

src/Stratis.Bitcoin.Features.Miner/Controllers/MiningController.cs, src/Stratis.Bitcoin.IntegrationTests/API/AllControllersTests.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs, src/Stratis.Bitcoin.IntegrationTests/CustomNodeBuilderTests.cs, src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj, src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContractWalletOnPosNetworkTests.cs
Please don't shout, I am just doing this PR as a test to see if the CI gives better results
=> try xUnit retry package

src/Stratis.Bitcoin.Features.PoA/ConsensusRules/PoACoinviewRule.cs, src/Stratis.Bitcoin.Features.PoA/FederationManager.cs, src/Stratis.Bitcoin.Features.PoA/PoABlockDefinition.cs, src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs, src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.Bitcoin.Features.PoA/Stratis.Bitcoin.Features.PoA.csproj
This PR is needed for testing https://github.com/stratisproject/StratisBitcoinFullNode/issues/2310
Later we will fix the miner to produce blocks according to poa consensus rules.
=> Dummy miner that will be needed to check syncing and payloads

src/Stratis.Bitcoin.Features.PoA/PoAConsensusManagerBehavior.cs, src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs, src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs
Partially fixes https://github.com/stratisproject/StratisBitcoinFullNode/issues/2310
There will be 1-2 PRs for that issue
__
Update: or not
=> [PoA] PoA consensus manager behavior

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AddressTests.cs, src/Stratis.SmartContracts/Address.cs
=> [SC] Fix Address equality

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTests.cs, src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs, src/Stratis.SmartContracts.Core.Validation.Tests/ValidationTests.cs, src/Stratis.SmartContracts.Core.Validation/Validators/Method/MethodParamValidator.cs, src/Stratis.SmartContracts.Executor.Reflection/Contract.cs
* Tests for optional param behaviour
* Add validator to prevent optional params being used
Closes #2353.
=> [SC] Validate optional params

src/Stratis.SmartContracts.IntegrationTests/ContractExecutionFailureTests.cs
=> [SC] Add test for an empty module

src/Stratis.Bitcoin.Features.Wallet/Models/GetTransactionModel.cs, src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs
RPC methods for:
**gettransaction** - Returns a wallet transaction
**getbalance** - Returns wallet balance
Partially fixes #1356
=> Add RPC methods gettransaction and getbalance

src/Stratis.SmartContracts.IntegrationTests/ContractInternalTransferTests.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/NestedCallsReceiver.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/NestedCallsStarter.cs, src/Stratis.SmartContracts.IntegrationTests/Stratis.SmartContracts.IntegrationTests.csproj
=> [SC] Nested calls integration test

src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
=> [SC] I broke the build! Add Clear to IPersistentState implementation

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/BlockBuilder.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs, src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerFailedReorgTests.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
These tests will currently fail until @dangershony's submit his bug fix.
=> [Integration Tests] Reorg tests for consensus part 1

src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/ContractLogHolder.cs, src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/MeteredContractLogger.cs, src/Stratis.SmartContracts/IContractLogger.cs
Getting those contrived commits up
Closes #2448
=> [SC] Where T : struct

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
=> Use supplied Wallet/Account/Password in SetMinerSecret

src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
Putting this PR in so that these can start getting reviewed while I finish the remaining tests (some of which are being blocked by apparent bugs in the mempool logic).
=> [Mempool] Additional tests

src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinViewStackTest.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinViewTest.cs, src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs, src/Stratis.Bitcoin.Features.Consensus/CoinViews/CoinView.cs, src/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs, src/Stratis.Bitcoin.Features.Consensus/CoinViews/InMemoryCoinView.cs, src/Stratis.Bitcoin.Features.Consensus/UnspentOutputSet.cs, src/Stratis.Bitcoin.Features.MemoryPool/MemPoolCoinView.cs
=> Performance enhancment on SaveChangesAsync

src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
These 2 tests are failing regularly so I'm marking them as unstable.
=> Marked WalletCanReceiveAndSendCorrectly and WalletCanReorg as Unstable.

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs, src/Stratis.SmartContracts.Executor.Reflection/GasPriceList.cs, src/Stratis.SmartContracts.Executor.Reflection/IPersistenceStrategy.cs, src/Stratis.SmartContracts.Executor.Reflection/MeteredPersistenceStrategy.cs, src/Stratis.SmartContracts.Executor.Reflection/PersistentState.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/ContractCreationTests.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/ContractCreation.cs, src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs, src/Stratis.SmartContracts/IPersistentState.cs
=> [SC] Add ContractExists to PersistentState

src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
=> Add sign option to WalletContext

src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj, src/Stratis.Bitcoin.Features.Api/Stratis.Bitcoin.Features.Api.csproj, src/Stratis.Bitcoin.IntegrationTests.Common/Stratis.Bitcoin.IntegrationTests.Common.csproj, src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj, src/Stratis.BreezeD/Stratis.BreezeD.csproj, src/Stratis.StratisD/Stratis.StratisD.csproj, src/Stratis.StratisDnsD/Stratis.StratisDnsD.csproj
Read more about it here:
https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.4/2.1.4.md#cve-2018-8409-net-core-denial-of-service-vulnerability
All uynit tests are passing. 
Some integration tests are giving me trouble but nothing related to this upgrade.
=> Updated Microsoft.AspNetCore.App from 2.1.1 to 2.1.5 due to CVE. 

src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs
This PR improves the comments on ThresholdConditionCache.cs
=> [ColdStaking] Bip9 comments

src/Stratis.SmartContracts.IntegrationTests/PoW/ContractParameterSerializationTests.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/CreateWithAllArrays.cs, src/Stratis.SmartContracts.IntegrationTests/Stratis.SmartContracts.IntegrationTests.csproj
=> [SC] Serializing Arrays Integration Test

src/Stratis.Bitcoin.IntegrationTests/Connectivity/ConnectivityTests.cs
Related to #2390.
When connecting with addnode connect to peer and any peers in the address manager database.
=> [Integration Tests] TS101_Connectivity_CallAddNode

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs, src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersReservedSlotsBehavior.cs
moved ProvenHeadersConsensusManagerBehavior.cs to Stratis.Bitcoin.Features.Consensus project
=> moved ProvenHeadersConsensusManagerBehavior

src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreSignaledTests.cs
These tests primarily relate to detecting the presence or absence of messages getting exchanged between nodes.
=> [Integration Tests] [BlockStoreSignaled] Additional tests

src/Stratis.Bitcoin.Features.PoA.IntegrationTests/Tools/TestPoAMiner.cs, src/Stratis.Bitcoin.Features.PoA.IntegrationTests/Tools/TestPoANetwork.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/HeaderTimeChecksPoARuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoARulesTestsBase.cs, src/Stratis.Bitcoin.Features.PoA.Tests/SlotsManagerTests.cs, src/Stratis.Bitcoin.Features.PoA/FederationManager.cs, src/Stratis.Bitcoin.Features.PoA/PoAConsensusOptions.cs, src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs, src/Stratis.Bitcoin.Features.PoA/SlotsManager.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs
=> PoA - added periodic log and moved fed keys and target spacing to PoAConsensusOptions

src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
Just a small fix, this is related to issue #2579 but does not fix it.
=> [Mempool] Don't send getdata unnecessarily in response to inv

src/Stratis.Bitcoin.Features.SmartContracts/SmartContractMempoolValidator.cs, src/Stratis.SmartContracts.IntegrationTests/MockChain/MockChainNode.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMemoryPoolTests.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
=> [SC] Min gas price in mempool validator

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTransferProcessorTests.cs, src/Stratis.SmartContracts.Executor.Reflection/ResultProcessors/ContractTransferProcessor.cs
=> [SC] Don't generate internal transaction if reversion required

Documentation/smart-contracts-architecture.md
=> [SC] Begin architecture docs

src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildCallContractTransactionRequest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildCreateContractTransactionRequest.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/ContractExecutionFailureTests.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
=> [SC] Create transactions must have enough gas for create

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.BlockStore/ProvenHeadersBlockStoreBehavior.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/ProvenHeadersPayload.cs
Created ProvenHeadersBlockStoreBehavior as per #2588.
=> PHBSB - ProvenHeadersBlockStoreBehavior (#2588)

src/Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs, src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
=> Use lock when calling mempool

Documentation/PoA_manual.md
Manual covers new poa blockchain creation, wallet creation, blocks generations, fed keys creation, premine, network creation.
=> Added PoA manual to documentation

src/Stratis.Bitcoin.Features.SmartContracts/Models/GetStorageRequest.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/MethodParameterStringSerializer.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
=> [SC] Fix storage Type enum in controller

src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodParameterByteSerializerTests.cs, src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodParameterStringSerializerTests.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/MethodParameterStringSerializer.cs, src/Stratis.SmartContracts.IntegrationTests/PoA/ContractInternalTransferTests.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/ContractInternalTransferTests.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/ContractParameterSerializationTests.cs, src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
=> [SC] Method param string deserialization should expect base58 encoded Address

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ProvenHeaderRules/ProvenBlockHeaderCoinstakeRuleTest.cs
=> Fixed build temporarily

src/Stratis.Bitcoin.Features.MemoryPool/MempoolSettings.cs
=> Correct tx logic assigning RequireStandard mempool setting (#2474).

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/AllowedScriptTypeRuleTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Rules/AllowedScriptTypeRule.cs
=> [SC] Allow multisig through SC network

src/Stratis.Bitcoin.Features.SmartContracts/ISmartContractBlockHeader.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoS/SmartContractPosPowBlockDefinition.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinviewRule.cs
=> [SC] Query smart contract block header fields by interface

src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinviewRule.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/ContractExecutionFailureTests.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/InfiniteLoop.cs, src/Stratis.SmartContracts.IntegrationTests/Stratis.SmartContracts.IntegrationTests.csproj
=> [SC] Don't validate null refund

src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodParameterStringSerializerTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/MethodParameterStringSerializer.cs
=> [SC] Fix method param string serialization for Address

src/Stratis.Bitcoin/Connection/ConnectionManager.cs
This is a partial resolution of #2720, specifically the protocol version portion.
=> [P2P] Use correct protocol version for inbounds

src/Stratis.Bitcoin/Connection/ProvenHeadersConnectionManagerBehavior.cs
=> PH backward compatibility on handshake

Documentation/PoA_manual.md, Documentation/PoA_overview.md, Documentation/ProvenHeaders.md, Documentation/clr-execution-and-validation.md, Documentation/coldstaking.md
Went through the documentation and corrected some typos and made some sentences easier to read.
=> Updated FN documentation

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs, src/Stratis.SmartContracts.Core.Validation/FormatPolicy.cs, src/Stratis.SmartContracts.Core.Validation/Validators/Method/GenericMethodValidator.cs, src/Stratis.SmartContracts.Core.Validation/Validators/Type/GenericTypeValidator.cs
=> [SC] Generic Validation

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractWalletControllerTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/ContractTransactionItem.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/ISmartContractTransactionService.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletFeature.cs
* Add Create/Call API
* Remove unnecessary APIs
* Move common BuildCreateTx and BuildCallTx functionality into SmartContractTransactionService
=> [SC] Wallet API Part 2

src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
Ay, was working on some related things and punched this out - figure any test coverage is useful so feel free to accept or decline.
=> Oversize tx rejected by mempool integration test

src/Stratis.Bitcoin.Features.SmartContracts.Tests/SerializerTests.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/Serializer.cs, src/Stratis.SmartContracts/ISerializer.cs
=> [SC] Serializer changes

src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
=> [RPC] Use correct data for getpeerinfo response

src/Stratis.Bitcoin.Features.PoA.IntegrationTests/Tools/TestPoAMiner.cs, src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.SmartContracts.IntegrationTests/PoA/ContractExecutionFailureTests.cs, src/Stratis.SmartContracts.IntegrationTests/PoA/ContractInternalTransferTests.cs, src/Stratis.SmartContracts.IntegrationTests/PoA/MockChain/PoAMockChain.cs, src/Stratis.SmartContracts.IntegrationTests/PoA/MockChain/PoAMockChainFixture.cs, src/Stratis.SmartContracts.IntegrationTests/PoA/MockChain/TargetSpacingDateTimeProvider.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContractNodeBuilder.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContractPoARunner.cs
Allows the SC integration tests to run "synchronously" on PoA.
Should fix the CI also.
=> [SC] PoA Spacing DateTimeProvider

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/UnspentCoinModel.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs, src/Stratis.Bitcoin/Utilities/JsonConverters/MoneyJsonConverter.cs
Part of #2758
See https://bitcoin.org/en/developer-reference#listunspent for relevant documentation.
=> [RPC] Add listunspent

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs, src/Stratis.SmartContracts.Executor.Reflection/Serialization/MethodParameterStringSerializer.cs
=> [SC] Add method string parameter exception handling

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs
=> Bugfix- ph payload construction

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs, src/Stratis.Bitcoin.Features.BlockStore/ProvenHeadersBlockStoreSignaled.cs
Minor fix of a bug that basically was disabling batching
=> Concurrent chain wrong tip usage fix

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractCompilerTests.cs, src/Stratis.Bitcoin.FullNode.sln, src/Stratis.SmartContracts.Core.Validation/FormatPolicy.cs, src/Stratis.SmartContracts.Core.Validation/Stratis.SmartContracts.Core.Validation.csproj, src/Stratis.SmartContracts.Executor.Reflection/Compilation/ReferencedAssemblyResolver.cs, src/Stratis.SmartContracts.Executor.Reflection/Stratis.SmartContracts.Executor.Reflection.csproj, src/Stratis.SmartContracts.IntegrationTests/ContractInternalTransferTests.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/StandardToken.cs, src/Stratis.SmartContracts.IntegrationTests/Stratis.SmartContracts.IntegrationTests.csproj, src/Stratis.SmartContracts.Standards/IStandardToken.cs, src/Stratis.SmartContracts.Standards/Stratis.SmartContracts.Standards.csproj
=> [SC] Add Standards library to contract execution

src/Stratis.SmartContracts/Stratis.SmartContracts.csproj
Updated here:
https://www.nuget.org/packages/Stratis.SmartContracts
=> [SC] Stratis.SmartContracts Version

src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderStore.cs, src/Stratis.Bitcoin/Base/BaseFeature.cs, src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs
If `ProvenHeaderBlockStore`'s tip is ahead of `chain.Tip` we need to set it's tip to `chain.Tip`.
=> [ProvenHeaders] Set PHBS tip to ChainTip if its ahead

src/NBitcoin/BitcoinCore/Coins.cs, src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs, src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/RewindDataIndexStore.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/ProvenHeaderRules/ProvenHeaderCoinstakeRule.cs, src/Stratis.Bitcoin/Utilities/UnspentOutputs.cs
And correctly look up for  utxo spent on another chain.
=> Correctly store and load rewind data index, 

src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/P2P/PeerConnector.cs
Quick and dirty fix for https://github.com/stratisproject/StratisBitcoinFullNode/issues/2864
=> Disconnect after handshake if already have a peer on the same group

src/Stratis.Bitcoin.Features.BlockStore/ProvenHeadersBlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs, src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs
=> Fix bug when PH would be serialized instead of BlockHeader

src/Stratis.Bitcoin/P2P/PeerSelector.cs
=> [P2P] Fix peer selector Random logic error.

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs, src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs, src/Stratis.Bitcoin/Consensus/ConsensusExceptions.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs, src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs
=> CMB logs and bugfix

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs
Set the transaction fee to the network defined minimum fee if the transaction fee is too low.
Unit tests are passing, waiting for integration tests to finish.
=> Set the transaction fee to the network defined minimum fee 

src/NBitcoin/FeeRate.cs
=> FeeRate constructor in Overflow when paying a huge amount of fee

src/NBitcoin.Tests/util_tests.cs, src/NBitcoin/FeeRate.cs
=> fixed FeeRate rounding issue 

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreBehaviorTest.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueueFlushCondition.cs, src/Stratis.Bitcoin.Features.BlockStore/ProvenHeadersBlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin/Base/ChainState.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/Interfaces/IBlockStoreQueue.cs, src/Stratis.Bitcoin/Interfaces/IBlockStoreQueueFlushCondition.cs
Attempting to fix the delay in X nodes that can happen sometimes on IBD
=> Adding BlockStoreCacheTip property and more debug logs

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractParametersJsonResolverTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/AddressJsonConverter.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/ContractParametersContractResolver.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
=> [SC] Address json resolver

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs, src/Stratis.Bitcoin/Consensus/ScriptAddressReader.cs
Fixes https://github.com/stratisproject/FederatedSidechains/issues/248
=> Parse P2SH in wallet

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs
Fixes https://github.com/stratisproject/FederatedSidechains/issues/258
=> Fix for: Missed POA slots show too many items

src/FodyNlogAdapter/FodyNlogAdapter.csproj, src/NBitcoin/NBitcoin.csproj, src/Stratis.Bitcoin.Features.Api/Stratis.Bitcoin.Features.Api.csproj, src/Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.Features.BlockStore.csproj, src/Stratis.Bitcoin.Features.Consensus/Stratis.Bitcoin.Features.Consensus.csproj, src/Stratis.Bitcoin.Features.Dns/Stratis.Bitcoin.Features.Dns.csproj, src/Stratis.Bitcoin.Features.LightWallet/Stratis.Bitcoin.Features.LightWallet.csproj, src/Stratis.Bitcoin.Features.MemoryPool/Stratis.Bitcoin.Features.MemoryPool.csproj, src/Stratis.Bitcoin.Features.Miner/Stratis.Bitcoin.Features.Miner.csproj, src/Stratis.Bitcoin.Features.Notifications/Stratis.Bitcoin.Features.Notifications.csproj, src/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common.csproj, src/Stratis.Bitcoin.Features.PoA/Stratis.Bitcoin.Features.PoA.csproj, src/Stratis.Bitcoin.Features.RPC/Stratis.Bitcoin.Features.RPC.csproj, src/Stratis.Bitcoin.Features.Wallet/Stratis.Bitcoin.Features.Wallet.csproj, src/Stratis.Bitcoin.Features.WatchOnlyWallet/Stratis.Bitcoin.Features.WatchOnlyWallet.csproj, src/Stratis.Bitcoin.IntegrationTests.Common/Stratis.Bitcoin.IntegrationTests.Common.csproj, src/Stratis.Bitcoin.Networks/Stratis.Bitcoin.Networks.csproj, src/Stratis.Bitcoin.Tests.Common/Stratis.Bitcoin.Tests.Common.csproj, src/Stratis.Bitcoin.Tests.Wallet.Common/Stratis.Bitcoin.Tests.Wallet.Common.csproj, src/Stratis.Bitcoin/Properties/AssemblyInfo.cs, src/Stratis.Bitcoin/Stratis.Bitcoin.csproj
Bump nuget packages to 3.0.0.2-beta.
=> Bump version

src/Stratis.SmartContracts.CLR/AddressExtensions.cs
Address.Create is internal to Stratis.SmartContracts. In the SBFN solution, Stratis.SmartContracts is a friend assembly of all other smart contract projects, but this does not carry over to the NuGet packages.
=> Fix visibility of Address.Create

src/Stratis.SmartContracts.CLR/ILRewrite/ObserverRewriter.cs
Lets us remove unnecessary branching.
=> [SC] Rewrite module later

src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj, src/Stratis.SmartContracts.CLR.Validation/Stratis.SmartContracts.CLR.Validation.csproj, src/Stratis.SmartContracts.CLR/Stratis.SmartContracts.CLR.csproj, src/Stratis.SmartContracts.Standards/Stratis.SmartContracts.Standards.csproj, src/Stratis.SmartContracts/Stratis.SmartContracts.csproj
All SC + integration tests passing.
=> SC NuGet Bump

src/NBitcoin.Tests/util_tests.cs, src/NBitcoin/Target.cs
=> Fix Target conversion

src/NBitcoin.Tests/ProvenBlockHeaderTests.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/PruneBlockRepositoryTests.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/PruneBlockStoreServiceTests.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.BlockStore/Pruning/IPruneBlockStoreService.cs, src/Stratis.Bitcoin.Features.BlockStore/Pruning/IPrunedBlockRepository.cs, src/Stratis.Bitcoin.Features.BlockStore/Pruning/PruneBlockStoreService.cs, src/Stratis.Bitcoin.Features.BlockStore/Pruning/PrunedBlockRepository.cs, src/Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.Features.BlockStore.csproj, src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderRepositoryTests.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderStoreTests.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenHeaderConsenusManagerBehaviorTests.cs, src/Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs, src/Stratis.Bitcoin.Tests.Common/TestBase.cs, src/Stratis.StratisD/Properties/launchSettings.json
Also, I moved the Prune classes to the block store feature. Next up is to move it to Stratis.Bitcoin.
=> [Pruning] Create unit tests for PruneBlockRepository and PruneBlockStoreService

src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs
Part of #2758 
Note: subtractfeefrom is currently not supported because it is not yet supported in WalletTransactionHandler
https://bitcoincore.org/en/doc/0.16.1/rpc/wallet/sendmany/
=> [RPC] add sendmany

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
This will lead to an improvement in performance.
**When is the wallet saved?**
The wallets are saved every 5 minutes + every time the user creates an account, addresses or the user removes all the transactions.
In the worst case, like a node crash, the wallet file is 4:59 minutes old. On restart, the wallet will just get updated with the 5 minutes old blocks.
=> Removed saving the wallet every time we receive a trx affecting the user's wallets.

src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
Fixed bug when provided callback wouldn't be registered
=> GetOrDownloadBlocksAsync bugfix

src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs
See #3041. Fixes WalletOperationsTests.
=> Fix wallet recovery tests

src/Stratis.SmartContracts.Tests.Common/MockChain/MockChainNode.cs
=> [SC] Use invariant culture in MockChainNode

src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs, src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs, src/Stratis.Bitcoin.Tests/Consensus/TestConsensusManager.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
=> Consensus test extensions fix

src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
Improved `GetUtxoStakeDescriptionsAsync` method to have a faster lookup when we have lot uf utxo in the wallet
Improved stake parallelism in CreateCoinstakeAsync
=> Improved staking with dust

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs
=> [SC] Add tests demonstrating foreach behaviour

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs
=> [SC] Add tests demonstrating public partials

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersReservedSlotsBehavior.cs
Fixes the #3073 issue
minimum required ph enabled peers connected set to 3.
=> ProvenHeadersReservedSlotsBehavior fix (3073)

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs, src/Stratis.Bitcoin.Features.Consensus/Interfaces/IStakeValidator.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/ProvenHeaderRules/ProvenHeaderCoinstakeRule.cs, src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
Close #3047
Fixes the `WalletCanMineWithColdWalletCoins` test case of issue #3041.
=> Fix ProvenHeaderCoinStakeRule

src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs
Add some tests to demonstrate functionality. See: #2037.
=> [SC] Add statics tests

src/Stratis.Bitcoin.Features.PoA/PoAConsensusErrors.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractConsensusErrors.cs
See https://github.com/stratisproject/StratisBitcoinFullNode/pull/3099.
=> Avoid multiple constructor calls 2

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
Please ignore the previous pull request.
=> Updated NodeSettings properties documentation.

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
=> Fix test case for disconnecting node on invalid stake depth

src/NBitcoin/Script.cs, src/NBitcoin/ScriptReader.cs
This will be the last one :)
Busy syncing networks...
=> [NBitcoin] Add usings to memory stream usages #3

src/Stratis.Bitcoin.Tests/Utilities/ParallelAsyncTest.cs
=> Fix ForEachAsync_TestDegreeOfParallelism_Async

src/NBitcoin.Tests/NetworkTests.cs, src/Stratis.Bitcoin.Networks/BitcoinMain.cs, src/Stratis.Bitcoin.Networks/BitcoinTest.cs, src/Stratis.Bitcoin.Networks/StratisMain.cs, src/Stratis.Bitcoin.Networks/StratisTest.cs
Updated the checkpoints for the 4 networks to newer dates.
=> Checkpoints update

src/Stratis.Bitcoin.IntegrationTests/CustomNodeBuilderTests.cs
=> Fix CanOverrideAllPorts

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Models/RequestValidationTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildCallContractTransactionRequest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildCreateContractTransactionRequest.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
=> [SC] Fix wallet syncing issue

src/Stratis.Bitcoin.IntegrationTests.Common/ReadyData/ReadyBlockchain.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs
Removed another 6 minutes from the integration tests run.
=> [Tests] Make use of the ReadyBlockchain stuff in RPC integration tests

src/NBitcoin/Script.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/HeaderTimeChecksPoARuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAHeaderDifficultyRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAHeaderSignatureRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAIntegritySignatureRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoARulesTestsBase.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAVotingCoinbaseOutputFormatRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/VotingDataEncoderTests.cs, src/Stratis.Bitcoin.Features.PoA/BasePoAFeatureConsensusRules/HeaderTimeChecksPoARule.cs, src/Stratis.Bitcoin.Features.PoA/BasePoAFeatureConsensusRules/PoACoinviewRule.cs, src/Stratis.Bitcoin.Features.PoA/BasePoAFeatureConsensusRules/PoAHeaderDifficultyRule.cs, src/Stratis.Bitcoin.Features.PoA/BasePoAFeatureConsensusRules/PoAHeaderSignatureRule.cs, src/Stratis.Bitcoin.Features.PoA/BasePoAFeatureConsensusRules/PoAIntegritySignatureRule.cs, src/Stratis.Bitcoin.Features.PoA/PoABlockDefinition.cs, src/Stratis.Bitcoin.Features.PoA/PoAConsensusErrors.cs, src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs, src/Stratis.Bitcoin.Features.PoA/Voting/ConsensusRules/PoAVotingCoinbaseOutputFormatRule.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingData.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingDataEncoder.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoA/Rules/SmartContractPoACoinviewRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoABlockDefinition.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoARuleRegistration.cs, src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs
See https://github.com/stratisproject/Research/blob/master/PoA/FeatureDesign_DynamicFederationMembers.md
This PR can be reviewed commit by commit. 
This PR implements components needed for logic inside of `PoAVotingCoinbaseOutputFormatRule` + tests + a bit of refactoring
=> PoA_DynamicFederationMembers_1

src/Stratis.Bitcoin.IntegrationTests.Common/ReadyData/ReadyBlockchain.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
Also changed the number of blocks mined in some tests were there were more than necessary for the tests to be useful.
=> [Tests] Use ReadyBlockchain stuff, shaved another 5 min.

src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/OverrideServiceFeatureExtension.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Runners/CustomRunner.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs, src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowRunner.cs, src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
This fixes #3169. We should now use Replace Service
=> [Integration Tests] Update ReplaceService

src/Stratis.Bitcoin.Features.PoA.Tests/PoATestsBase.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/HeaderTimeChecksPoARuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAHeaderDifficultyRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAHeaderSignatureRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAIntegritySignatureRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoAVotingCoinbaseOutputFormatRuleTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/SlotsManagerTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/VotingManagerTests.cs, src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs, src/Stratis.Bitcoin.Features.PoA/Voting/PendingPoll.cs, src/Stratis.Bitcoin.Features.PoA/Voting/Poll.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingController.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingData.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs, src/Stratis.Bitcoin.IntegrationTests/Connectivity/ConnectivityTests.cs, src/Stratis.Bitcoin/Utilities/KeyValueRepository.cs
Refactoring, comments, tests, added partial implementation of voting manager.
=> PoA_DynamicFederationMembers_3

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TxOutSmartContractExecRuleTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Rules/TxOutSmartContractExecRule.cs
=> [SC] Avoid coinbase contracts

src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinViewRuleLogic.cs, src/Stratis.Bitcoin.Features.SmartContracts/SmartContractConsensusErrors.cs
=> [SC] Validate LogsBloom

src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
I put breakpoints in the respective critical areas to ensure that the two exceptions got thrown.
=> [Integration Tests] Stabilise the InvalidStakeDepth and MaxReorgLength tests

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/OpSpendRuleTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Rules/OpSpendRule.cs
* Fix quadratic function
* Fix tests
=> [SC] OpSpendRule improvements

src/NBitcoin/BitcoinStream.Partial.cs, src/NBitcoin/BitcoinStream.cs, src/Stratis.Bitcoin.Features.PoA.Tests/PoATestsBase.cs, src/Stratis.Bitcoin.Features.PoA.Tests/PollTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/SlotsManagerTests.cs, src/Stratis.Bitcoin.Features.PoA.Tests/VotingManagerTests.cs, src/Stratis.Bitcoin.Features.PoA/FederationManager.cs, src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs, src/Stratis.Bitcoin.Features.PoA/Voting/Poll.cs, src/Stratis.Bitcoin.Features.PoA/Voting/PollResultExecutor.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingController.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingControllerModels.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoA/IFullNodeBuilderExtensions.cs
VotingManaer, PollResultExecutor, api controller
=> PoA_DynamicFederationMembers_4

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/AccountRootTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
See BUG 3002.
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3002/
=> Suppress wallet exception

src/Stratis.Bitcoin.Tests/P2P/NetworkPeerTests.cs, src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
See STY 3054.
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3054
=> Do not disconnect peers that don't support required services

src/Stratis.Bitcoin.Features.SmartContracts/Models/ReceiptResponse.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
=> [SC] Queryable return value in receipt

src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs, src/Stratis.Bitcoin/Utilities/ParallelAsync.cs
See BUG 3044.
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3044
=> Validate MaxOutboundConnections/MaxInboundConnections is more than 0

src/Stratis.Bitcoin.Features.Consensus/Rules/ProvenHeaderRules/ProvenHeaderCoinstakeRule.cs, src/Stratis.Bitcoin/Consensus/ConsensusErrors.cs
fixed the race condition that was causing StakeModifierV2 being null on some test environments
=> fix null StakeModifierV2 race condition

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractsControllerTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
=> [SC] Contract balance returned in STRAT

src/Stratis.Bitcoin/Controllers/Models/StatusModel.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs
Fixes : https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3102
=> [API] Fix null consensus tip when node starts up.

src/Stratis.Bitcoin/Connection/PeerBanning.cs
See work item 3059.
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3059
=> [P2P] ValidationContext.BanDurationSeconds doesn't work as expected

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs
Fixed and improved the estimate fee endpoint.
Fixes https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3088
Fixes https://github.com/stratisproject/StratisBitcoinFullNode/issues/2958
=> [Wallet] Estimate fee

src/Stratis.Bitcoin.Features.Miner/PowMining.cs
=> Relax IBD check for regtest to allow mining at genesis

src/NBitcoin/Consensus.cs, src/NBitcoin/IConsensus.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/StakeValidatorTests.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckDifficultyPosRule.cs, src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs, src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, src/Stratis.Bitcoin.Networks/BitcoinMain.cs, src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs, src/Stratis.Bitcoin.Networks/BitcoinTest.cs, src/Stratis.Bitcoin.Networks/Networks.cs, src/Stratis.Bitcoin.Networks/StratisMain.cs, src/Stratis.Bitcoin.Networks/StratisRegTest.cs, src/Stratis.Bitcoin.Networks/StratisTest.cs, src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractPosTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoATest.cs, src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsTest.cs
Fixes [3047](https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3047)
=> [Consensus] Add PosNoRetargeting flag to Networks

src/Stratis.Bitcoin.Features.Api/Stratis.Bitcoin.Features.Api.csproj, src/Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.Features.BlockStore.csproj, src/Stratis.Bitcoin.Features.ColdStaking/Stratis.Bitcoin.Features.ColdStaking.csproj, src/Stratis.Bitcoin.Features.Consensus/Stratis.Bitcoin.Features.Consensus.csproj, src/Stratis.Bitcoin.Features.Dns/Stratis.Bitcoin.Features.Dns.csproj, src/Stratis.Bitcoin.Features.LightWallet/Stratis.Bitcoin.Features.LightWallet.csproj, src/Stratis.Bitcoin.Features.MemoryPool/Stratis.Bitcoin.Features.MemoryPool.csproj, src/Stratis.Bitcoin.Features.Miner/Stratis.Bitcoin.Features.Miner.csproj, src/Stratis.Bitcoin.Features.Notifications/Stratis.Bitcoin.Features.Notifications.csproj, src/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common.csproj, src/Stratis.Bitcoin.Features.PoA/Stratis.Bitcoin.Features.PoA.csproj, src/Stratis.Bitcoin.Features.RPC/Stratis.Bitcoin.Features.RPC.csproj, src/Stratis.Bitcoin.Features.Wallet/Stratis.Bitcoin.Features.Wallet.csproj, src/Stratis.Bitcoin.Features.WatchOnlyWallet/Stratis.Bitcoin.Features.WatchOnlyWallet.csproj, src/Stratis.Bitcoin.IntegrationTests.Common/Stratis.Bitcoin.IntegrationTests.Common.csproj, src/Stratis.Bitcoin.Networks/Stratis.Bitcoin.Networks.csproj, src/Stratis.Bitcoin.Tests.Common/Stratis.Bitcoin.Tests.Common.csproj, src/Stratis.Bitcoin.Tests.Wallet.Common/Stratis.Bitcoin.Tests.Wallet.Common.csproj, src/Stratis.Bitcoin/Properties/AssemblyInfo.cs, src/Stratis.Bitcoin/Stratis.Bitcoin.csproj
Reopening master for business.
=> [Build] Create new beta version 3020-beta

src/Stratis.Bitcoin/Base/Deployments/Models/ThresholdStateModel.cs, src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs
This PR adds a block version summary to the "deploymentflags" API.
=> Add versions to "deploymentflags" api

src/Stratis.Bitcoin/Configuration/TextFileConfiguration.cs
=> Handle Int64 config keys

src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
- Add voting manager et al. to PoA consensus
- Remove now unused classes (which aren't actually registered for injection)
=> [FS] Update FederationGatewayFeature to run in new FN

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
=> Only load wallet if wallet has not already been loaded

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
Fixes a couple of async methods that block unnecessarily.
=> Fix blocking async methods

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
See https://github.com/stratisproject/StratisBitcoinFullNode/pull/3100.
=> Access block before rewinding

src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
Prevents `System.InvalidOperationException : Collection was modified; enumeration operation may not execute.` errors, like the one in [this build](https://dev.azure.com/StratisProject/StratisBitcoinFullNode/_build/results?buildId=11944&view=ms.vss-test-web.build-test-results-tab).
=> Fix wallet staking tests

src/Stratis.Bitcoin.Features.RPC.Tests/RPCMiddlewareTest.cs, src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs
Added support for cookie authentication for RPC requests
Similar to bitcoin: https://bitcoin.stackexchange.com/questions/46782/rpc-cookie-authentication/48524
=> [RPC] Added a check for a cookie

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
=> alternative implementation of "Cancel CheckInputs in CoinViewRule #3313"

Documentation/Features/SmartContracts/Contract_whitelisting.md
Documents the smart contracts side of the PoA whitelisting implementation.
=> [SC] Add whitelisting docs

src/NBitcoin/IpExtensions.cs
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3339.
=> Fix GetGroup to not consider all RFC6598 ips to be in same group

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, src/Stratis.Bitcoin.Features.Consensus/PosConsensusFeature.cs, src/Stratis.Bitcoin.Features.Consensus/PowConsensusFeature.cs, src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3203.
=> Add missing command line help

src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationGatewayControllerTests.cs, src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationWalletControllerTests.cs, src/Stratis.Features.FederatedPeg.Tests/MaturedBlockDepositModelTests.cs, src/Stratis.Features.FederatedPeg.Tests/MaturedBlockRequestModelTests.cs, src/Stratis.Features.FederatedPeg.Tests/MaturedBlocksProviderTests.cs, src/Stratis.Features.FederatedPeg.Tests/MaturedBlocksSyncManagerTests.cs, src/Stratis.Features.FederatedPeg.Tests/OpReturnDataReaderTests.cs, src/Stratis.Features.FederatedPeg.Tests/RestClientsTests/RestApiClientBaseTests.cs, src/Stratis.Features.FederatedPeg.Tests/SignedMultisigTransactionBroadcasterTests.cs, src/Stratis.Features.FederatedPeg.Tests/WithdrawalTests.cs, src/Stratis.Features.FederatedPeg.Tests/WithdrawalTransactionBuilderTests.cs
* Enables tests
* Fixes codestyle issues
* Fixes `SignedMultisigTransactionBroadcasterTests` now that there's no leader functionality
=> [FS] Enable tests

src/Stratis.Features.FederatedPeg/Wallet/FederationWalletSyncManager.cs
Implementation virtually copied from our own WalletSyncManager.
There's no tests for this component but the integration tests (including our skipped one that demonstrates a transfer) are running (and a little bit faster, too).
=> [FS] FederationWalletSyncManager uses a queue

src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
https://github.com/stratisproject/StratisBitcoinFullNode/issues/3164
=> Log debug for blockonly protocol violations

.gitignore, src/Stratis.Benchmark/NetworkBenchmarkBase.cs, src/Stratis.Benchmark/Persistence/FetchCoin.cs, src/Stratis.Benchmark/Program.cs, src/Stratis.Benchmark/Stratis.Benchmark.csproj, src/Stratis.Bitcoin.FullNode.sln
Added a benchmark project that uses BenchmarkDotNet to perform pretty cool benchmarking.
I've created an example where I tested different implementation of DBreeze fetch of data
to run a benchmark go to the folder of benchmark project and run
`dotnet run -c Release`
then you can pick the benchmark to run (with this PR just write `0` and return)
It takes some minute to generate the output, that you can see in console or in `src\Stratis.Benchmark\BenchmarkDotNet.Artifacts\results`
BenchmarkDotNet is a powerful tool, with lot of stuffs to discover
website: https://benchmarkdotnet.org
github repo: https://github.com/dotnet/BenchmarkDotNet
=> Benchmark project (with example)

src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/2968
=> Remove duplicate port check for bind/whitebind

src/NBitcoin/IpExtensions.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs, src/Stratis.Bitcoin.Features.Consensus/PosConsensusFeature.cs, src/Stratis.Bitcoin.Features.Consensus/PowConsensusFeature.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs, src/Stratis.Bitcoin.Features.RPC/RPCClient.cs, src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs, src/Stratis.Bitcoin.Features.RPC/RPCRequest.cs, src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs, src/Stratis.Bitcoin/Configuration/NodeSettings.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
=> [Release-Merge] Fix GetGroup to not consider all RFC6598 ips to be in same group

src/NBitcoin/Network.cs, src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs, src/Stratis.Bitcoin.Networks/BitcoinMain.cs, src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs, src/Stratis.Bitcoin.Networks/BitcoinTest.cs, src/Stratis.Bitcoin.Networks/StratisMain.cs, src/Stratis.Bitcoin.Networks/StratisRegTest.cs, src/Stratis.Bitcoin.Networks/StratisTest.cs, src/Stratis.Sidechains.Networks/CirrusV2/CirrusMain.cs, src/Stratis.Sidechains.Networks/CirrusV2/CirrusRegTest.cs, src/Stratis.Sidechains.Networks/CirrusV2/CirrusTest.cs, src/Stratis.Sidechains.Networks/FederatedPegMain.cs, src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs, src/Stratis.Sidechains.Networks/FederatedPegTest.cs, src/Stratis.SmartContracts.Networks/SignedContractsPoARegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractPosTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoATest.cs, src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsTest.cs
Bringing this in from upstream `NBitcoin`, as it's quite useful.
=> Introduce NetworkType enum

src/Stratis.Features.FederatedPeg/Collateral/FederatedPegPoAConsensusOptions.cs, src/Stratis.Features.FederatedPeg/Collateral/FederationMember.cs
This is needed to allow adding new consensus options to the fed peg network
=> Federation member class and new consensus options

src/Stratis.Features.FederatedPeg/Wallet/FederationWallet.cs
Fixes an issue found by Maciej.
=> [FS] Fix enumeration issue

src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs, src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalExtractor.cs
Should help with CPU pressure during deposit sync.
=> [FS] Performance improvements for withdrawal and deposit extractors

src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationGatewayControllerTests.cs, src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationWalletControllerTests.cs, src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs, src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs, src/Stratis.Features.FederatedPeg.Tests/PartialTransactionsRequesterTests.cs, src/Stratis.Features.FederatedPeg.Tests/SignedMultisigTransactionBroadcasterTests.cs, src/Stratis.Features.FederatedPeg/Controllers/FederationGatewayController.cs, src/Stratis.Features.FederatedPeg/Controllers/FederationWalletController.cs, src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs, src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/TargetChain/MaturedBlocksSyncManager.cs, src/Stratis.Features.FederatedPeg/TargetChain/PartialTransactionRequester.cs, src/Stratis.Features.FederatedPeg/TargetChain/SignedMultisigTransactionBroadcaster.cs, src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
I also renamed IsFederationActive() -> IsFederationWalletActive()
=> [FS] Do less work in IBD or when federation is inactive

src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs, src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalExtractor.cs
Cross-chain transfers aren't actually working in integration tests in master atm. 
This fixes.
=> [FS] Fix deposit and withdrawal format checks

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs, src/Stratis.Bitcoin.Features.PoA/Behaviors/PoABlockStoreBehavior.cs, src/Stratis.Bitcoin.Features.PoA/Behaviors/PoAConsensusManagerBehavior.cs, src/Stratis.Bitcoin.Features.PoA/PoAConsensusManagerBehavior.cs, src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs, src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/PayloadAttribute.cs
The tests are still failing. Investigating...
=> [POA] Ensure that the POA CMB is cloned

src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
Should really change the test so it's not doing this async stuff but just want it to at least pass for now
=> [FS] Giving more time to cooked Ubuntu

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTests.cs, src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreSignaledTests.cs, src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs, src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs, src/Stratis.Bitcoin.IntegrationTests/Connectivity/ConnectivityTests.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs, src/Stratis.Bitcoin.IntegrationTests/LogLevelsTests.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
=> [Tests] Remove redundant tests

src/Stratis.Bitcoin.Features.PoA/FederationManager.cs, src/Stratis.Bitcoin.Features.PoA/FederationMember.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingController.cs, src/Stratis.Bitcoin/Controllers/RestApiClientBase.cs, src/Stratis.CirrusPegD/Program.cs, src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs, src/Stratis.Features.FederatedPeg.Tests/Utils/FedPegTestsHelper.cs, src/Stratis.Features.FederatedPeg.Tests/Utils/TestingValues.cs, src/Stratis.Features.FederatedPeg/CollateralChecker.cs, src/Stratis.Features.FederatedPeg/CollateralFederationManager.cs, src/Stratis.Features.FederatedPeg/FederatedPegBlockDefinition.cs, src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
Added collateral checker (continuously asks another gateway node about federation balances), fixed initialization sequence and a small bug
=> [FS] Collateral checker

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractWalletControllerTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinViewRuleLogic.cs, src/Stratis.SmartContracts.Core.Tests/Receipts/PersistentReceiptRepositoryTests.cs, src/Stratis.SmartContracts.Core.Tests/Receipts/ReceiptSerializationTest.cs, src/Stratis.SmartContracts.Core/Receipts/Receipt.cs
Closes #3502.
Note: this changes the serialization of receipts so the receipt DB will need to be rebuilt.
=> [SC] Add gas price and amount to receipt

src/Stratis.Sidechains.Networks/CirrusTest.cs
This PR updates the CirrusTest Network with new detail for a new network pegged to StratisTest.
=> [FS] Update CirrusTest Network

src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
Quite difficult to test for this condition... I can try, but I want to put this PR out so we can test it on InternalTestnet.
I already tried this on my InternalTestnet - it helped get the furthest amount of transfers at a time yet (~35) before falling over due to other exceptions.
=> [FS] 3547 - Handling reorg race conditions

src/Stratis.Features.FederatedPeg/PartialTransactionsBehavior.cs
=> [FS] Fix out of order log

src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
This code is not doing anything useful and would instead be causing issues.
=> [FS] Remove redundant/incorrect code

src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs, src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
This reverts commit d195e29ad5603fa73d94d7b1305b27d50b823b70.
=> Revert "[FS] Fix FindWithdrawalTransactions (#3568)"

src/Stratis.Sidechains.Networks/CirrusMain.cs, src/Stratis.Sidechains.Networks/CirrusRegTest.cs, src/Stratis.Sidechains.Networks/CirrusTest.cs
=> [FS] MaxReorg on Cirrus

src/Stratis.Sidechains.Networks/CirrusMain.cs, src/Stratis.Sidechains.Networks/CirrusRegTest.cs, src/Stratis.Sidechains.Networks/CirrusTest.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3619
=> [FS] Calling schedulevote-whitelisthash throw error

src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs, src/Stratis.Features.FederatedPeg/Wallet/SpendingDetails.cs, src/Stratis.Features.FederatedPeg/Wallet/WithdrawalDetails.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3561
=> [FS] Add Deposit details to SpendingDetails

src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalHistoryProvider.cs, src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
Ensure that this list is ordered as expected and would be the same on peer nodes. Currently the ordering can differ on peer nodes.
=> [FS] Order GetWithdrawals by UTXO usage order

src/Stratis.Features.FederatedPeg/Controllers/FederationWalletController.cs, src/Stratis.Features.FederatedPeg/Models/RequestModels.cs
=> [FS] EnableFederation should check if (or wait until) the wallet is available

src/NBitcoin/Money.cs, src/Stratis.Bitcoin.Features.Api/Startup.cs, src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreClient.cs, src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs, src/Stratis.Bitcoin/Controllers/Models/AddressBalancesModel.cs, src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs, src/Stratis.Features.FederatedPeg/CollateralChecker.cs
Don't merge, awaiting test results!
=> [API] Ensure string dictionary keys casing gets respected [WIP]

src/Stratis.Bitcoin.Features.Dns/UnreliablePeerBehavior.cs
Need this for DNS seeders for Cirrus
=> [FN] Don't ban non-PH peers on non-PoS network

src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
inform the user while ReIndex operation is in place
=> 3700 - ReIndex causes the node to seems it's stuck (doesn't inform the user about the ongoing operation)

src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexerTypes.cs, src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs
It takes 1h to sync indexer on the testnet
=> Speedup address indexer

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs, src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs, src/Stratis.Features.FederatedPeg/CheckCollateralFullValidationRule.cs, src/Stratis.Features.FederatedPeg/CollateralChecker.cs, src/Stratis.Features.FederatedPeg/SmartContractCollateralPoARuleRegistration.cs
And also do not ban the peers that claim block that failed collateral check
=> Temporary reject blocks if collateral check failed

src/Stratis.Bitcoin/Utilities/LockProtected.cs, src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationWalletControllerTests.cs, src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
=> [FS] Clean-up FWM locking in CCTS

src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
Delete transaction data that is older than maxReorg blocks. This is to help prevent the federation wallet from becoming unworkably large.
=> [FS] Remove old transactions from fed wallet

src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
- Test would pass before the change, but if the implementation was working as it meant to, the test would have failed.
- Adjusted the implementation to be clearer about what it's doing
=> [FS] Test showing that CCTS doesn't maintain FullySigned transactions after reorg

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
=> Fixed multi loop for WalletManager.ChainDownload #3512

src/Stratis.Features.FederatedPeg.Tests/DepositExtractorTests.cs, src/Stratis.Features.FederatedPeg/FederatedPegSettings.cs, src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs
For https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3766
=> [FS] Deposit minimum 

src/Stratis.Bitcoin.Features.PoA.IntegrationTests/VotingAndMiningTests.cs
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3775
=> [FN] Add test to validate PoA mining fees

src/Stratis.Bitcoin.Features.MemoryPool/MempoolSignaled.cs
Code to handle peers that may not have mempool behavior registered
=> [FS] Fix for NullReferenceException for MempoolSignaled async loop

.gitignore, src/Stratis.SmartContracts.CLR.Tests/SmartContracts/Token.cs, src/Stratis.SmartContracts.CLR.Validation.Tests/Contracts/Token.cs, src/Stratis.SmartContracts.IntegrationTests/SmartContracts/Token.cs
Change assertion in Mint function to `this.Message.Sender == this.Owner`
Preferred: @codingupastorm @rowandh
=> Bugfix for SCT test assertions

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs
This will replace 
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3673
=> Take a scope of stream before using it

src/Stratis.FederatedSidechains.AdminDashboard/HostedServices/FetchingBackgroundService.cs, src/Stratis.FederatedSidechains.AdminDashboard/Program.cs, src/Stratis.FederatedSidechains.AdminDashboard/Properties/launchSettings.json
Previously opened for the PoA feature in the sidechain dashboard but renamed to fix an important issue
=> [SC] Fix important dashboard issue

src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
This code appears to be looking up a `TransactionData` that it already has, using the keys from the same `TransactionData`..
=> [FS] Remove unnecessary / inefficient code

src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoARuleRegistration.cs, src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs, src/Stratis.Features.FederatedPeg/Collateral/CheckCollateralFullValidationRule.cs, src/Stratis.Features.FederatedPeg/Collateral/SmartContractCollateralPoARuleRegistration.cs
Fix potential scenario when fed nodes would mine separated chain each
=> Decrease RejectUntil for blocks that were discarded by collateral rule

src/Stratis.Features.FederatedPeg/Wallet/TransactionData.cs
Removes the following JSON occurring in the wallet file:
```
"Key": {
"IsNull": false,
"Hash": {
"Size": 32
},
"N": 0
}
```
by adding [JsonIgore] to the `TransactionData.Key` field.
=> [FS] Fix wallet layout

src/Stratis.FederatedSidechains.AdminDashboard/appsettings.Development.json
This PR updates the default endpoint API ports for the Admin Dashboard for StratisTest and CirrusTest
=> [FS] Admin Dashboard - Update default endpoints for CirrusTest

src/Stratis.Features.FederatedPeg/PartialTransactionsBehavior.cs, src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/TargetChain/PartialTransactionRequester.cs, src/Stratis.Features.FederatedPeg/TargetChain/SignedMultisigTransactionBroadcaster.cs, src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
=> [FS] Adjust log levels

src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexRepository.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexerTypes.cs, src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreClient.cs, src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs, src/Stratis.Bitcoin.Features.PoA/FederationManager.cs, src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.Bitcoin/Controllers/Models/AddressBalancesResult.cs, src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs, src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs, src/Stratis.Features.FederatedPeg.Tests/CollateralHeightCommitmentEncoderTests.cs, src/Stratis.Features.FederatedPeg/Collateral/CheckCollateralFullValidationRule.cs, src/Stratis.Features.FederatedPeg/Collateral/CollateralChecker.cs, src/Stratis.Features.FederatedPeg/Collateral/CollateralPoAMiner.cs, src/Stratis.Features.FederatedPeg/FederatedPegFeature.cs
This is an implementation of the approach covered in https://github.com/stratisproject/Research/blob/master/PoA/FedPegCollateralImprovement.md
Purpose of creating the PR right now is to let everyone review the logic against the design. 
Differences from the design: 
Instead of hash commitment height is used.
=> FedPeg Collateral Improvement

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractsControllerTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
=> Check for peers before broadcasting smart contract transactions

src/Stratis.Features.FederatedPeg/FederatedPegFeature.cs
=> Avoid periodic log failure in case logs collection throws

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3913.
=> [FS] Don't exit mining loop due to collateral failures

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosTransactionsOrderRuleTests.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/RulesRegistrationOrderTest.cs, src/Stratis.Bitcoin.Features.Consensus/FullNodeBuilderConsensusExtension.cs, src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PoSTransactionsOrderRule.cs, src/Stratis.Bitcoin/Consensus/ConsensusErrors.cs
=> PH integrity validation improvements

src/Stratis.CirrusMinerD/Program.cs, src/Stratis.Features.FederatedPeg/FederatedPegFeature.cs
see https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3927
=> Use collateral poa miner instead of poa miner

src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
There's more optimal solutions but this fixes the underlying problem.
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3919
=> [FS] Output Suspended transactions correctly

src/Stratis.Bitcoin.Features.PoA/Voting/DefaultVotingController.cs, src/Stratis.Bitcoin.Features.PoA/Voting/Poll.cs, src/Stratis.Bitcoin.Features.PoA/Voting/PollResultExecutor.cs
See: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3931/
New api output looks like this:
```
{
"isPending": true,
"isExecuted": false,
"id": 0,
"pollVotedInFavorBlockData": null,
"pollStartBlockData": "37a078b89421078ed800c5d9d11fce0b54408c681d80fda33dccaa1ec1e6755b02000000",
"pollExecutedBlockData": null,
"pubKeysHexVotedInFavor": [
"03025fcadedd28b12665de0542c8096f4cd5af8e01791a4d057f67e2866ca66ba7"
],
"votingDataString": "Action:'WhitelistHash',Hash:'0333b88fb7a99c985d695be42e606cb913259bace2babe92970547fa033e4076'"
},
{
"isPending": true,
"isExecuted": false,
"id": 1,
"pollVotedInFavorBlockData": null,
"pollStartBlockData": "ddece98ae2968d08876108d8c8ac09c2962463bf885d3eea0345a3091fc3c42303000000",
"pollExecutedBlockData": null, …
```
=> More readable format for voting api endpoints + Json

src/NBitcoin/TransactionBuilder.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransfer.cs
This will help #3705 and the signing of large transactions, as the nodes often get stuck trying to merge all the inputs when really we know after one input whether it was successful.
=> [FS] Optimisations to transaction signing.

src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_boards/board/t/StratisBitcoinFullNode%20Team/Stories
=> Block puller total peers speed overflow fix

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs
add performance metrics for mining
=> Add perf metrics for PoAMiner

src/Stratis.Bitcoin.Features.Wallet/HdOperations.cs, src/Stratis.Bitcoin/Consensus/ConsensusManager.cs, src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs, src/Stratis.Bitcoin/Consensus/PerformanceCounters/ConsensusManager/ConsensusManagerPerformanceCounter.cs
=> [FN] Suppress some spurious trace logs

src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerOutpointsRepositoryTests.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexerOutpointsRepository.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexerTypes.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
This PR is supposed to improve recovery process of the address indexer in case node's process was killed.
=> Address indexer unexpected shutdown handling improvements

src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
=> CachedCoinView array sizes check

src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexerOutpointsRepository.cs
Fixes per review in https://github.com/stratisproject/StratisBitcoinFullNode/pull/3736
=> Address indexer comments

src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs, src/Stratis.Bitcoin/AsyncWork/AsyncProvider.cs, src/Stratis.Bitcoin/AsyncWork/IAsyncProvider.cs, src/Stratis.Bitcoin/Controllers/Models/AsyncLoopModel.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs
Sample output:
```
[
"AddressIndexer.indexingTask",
"BlockStoreQueue.dequeueLoopTask",
"BlockStoreSignaled.dequeueLoopTask",
"CallbackMessageListener-IncomingMessage-xxx:16178",
"CallbackMessageListener-IncomingMessage-xxx:16178",
"CallbackMessageListener-IncomingMessage-xxx:16178",
"CallbackMessageListener-IncomingMessage-xxx:16178",
"CallbackMessageListener-IncomingMessage-xxx:16178",
"CoinviewPrefetcher-headersQueue",
"ConnectionManager-connectedPeersQueue",
"DiscoverPeersAsync",
"FinalizedBlockInfoRepository.finalizedBlockInfoPersistingTask",
"FlushChain",
"MemoryPool.RelayWorker",
"NetworkPeer-asyncPayloadsQueue-xxx:16178",
"NetworkPeer-asyncPayloadsQueue-xxx:16178",
"NetworkPeer-asyncPayloadsQueue-xxx:16178",
"NetworkPeer-asyncPayloadsQueue-xxx:16178", …
```
=> [FN] Async loop info

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs
Removed a check for SC receipt as we may not have it when tx is unmined
=> [FS] Fix for unmined txs

src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractWalletControllerTest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/ContractTransactionItem.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs
=> [SC] Fix wallet history duplicates

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.Sidechains.Networks/CirrusMain.cs
This PR updates the CirrusMain Network to include the latest Federation mining keys.
=> Update CirrusMain & PoAMiner

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4022.
=> [FS] Move code into try block to catch token disposed errors

src/Stratis.Bitcoin.Features.PoA/Voting/DefaultVotingController.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingDataModel.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3786.
=> [FS] Return proper JSON from Voting API

src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs, src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs, src/Stratis.Features.FederatedPeg.Tests/RestClientsTests/FederationGatewayClientTests.cs, src/Stratis.Features.FederatedPeg/Collateral/CheckCollateralFullValidationRule.cs, src/Stratis.Features.FederatedPeg/Collateral/CollateralChecker.cs, src/Stratis.Features.FederatedPeg/Collateral/CollateralFeature.cs, src/Stratis.Features.FederatedPeg/Collateral/SmartContractCollateralPoARuleRegistration.cs, src/Stratis.Features.FederatedPeg/CounterChain/CounterChainSettings.cs
This reverts commit e6c169cc2f6bedd64894c1743f878a5b06ba7b16.
=> Revert "[FS] Fix CheckCollateralFullValidationRule (#3771)"

src/Stratis.Features.FederatedPeg/FederatedPegFeature.cs, src/Stratis.Features.FederatedPeg/Interfaces/ICrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs, src/Stratis.Features.FederatedPeg/TargetChain/MempoolCleaner.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3773.
=> [FS] Orphan transactions are left in the mempool

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4076.
=> [FS] Add MaxTipAge to console and improve IBD reporting

src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3368.
=> Fix wallet unlock needed error message

src/Stratis.Bitcoin.Features.PoA.Tests/VotingManagerTests.cs, src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4043
=> [PoA] Block disconnection won't cause exception when a duplicate poll is voted on

src/Stratis.Bitcoin.IntegrationTests/API/NetworkControllerApiTests.cs, src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTestsHelper.cs, src/Stratis.Bitcoin/Connection/PeerBanning.cs, src/Stratis.Bitcoin/Controllers/Models/BannedPeerModel.cs, src/Stratis.Bitcoin/Controllers/NetworkController.cs, src/Stratis.Bitcoin/P2P/SelfEndpointTracker.cs
Sample output:
```
[
{
"endPoint": "[::ffff:89.xxx.xxx.xxx]:16178",
"banUntil": "2019-06-27T21:33:34.0218677Z",
"banReason": "Banned via the API."
}
]
```
=> Add getbans API

src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalHistoryProvider.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3844
=> [FS] Base federation wallet withdrawal history solely on CCTS

src/Stratis.SmartContracts.Core/Bloom.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4141
=> [SC] No bloom ReadWrite trace

src/FodyWeavers.xml, src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
Currently not getting any trace logs for the .Features.SmartContracts namespace.
=> [SC] Add Fody to Features.SmartContracts.

src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs
=> Avoid applying duplicated voting data

src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
I'm hoping this can help us discern the "real" `Disconnect` before the message transmission goes breaking after.
=> Logs for Receiving Cancelled

src/Stratis.Features.FederatedPeg/TargetChain/MempoolCleaner.cs
Nested locking should only occur in the following order: CCTS -> FWM.
However `CleanMempoolAsync` is first locking FWM and then calling a method on the CCTS that locks the CCTS.
This fix refactors the code so that this does not happen.
=> [FS] Fix incorrect locking order in CleanMempoolAsync

src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractTransactionServiceTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildCallContractTransactionRequest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildCreateContractTransactionRequest.cs, src/Stratis.Bitcoin.Features.SmartContracts/Models/OutpointRequestModel.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs
=> [SC] Add outpoints to SC calls with test

src/NBitcoin.Tests/script_tests.cs, src/NBitcoin/Script.cs
This is a potentially useful improvement from the upstream NBitcoin repository.
=> Introduce ScriptType enum

Documentation/cold-staking-setup.md
I have created a markdown file describing the process for setting up cold staking.
=> Add cold staking setup information

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletTransactionHandler.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.Wallet/Validations/IsBitcoinAddressAttribute.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4164.
=> Enable change address to be set in build transaction API

src/Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs, src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs
Turns out @fassadlr was right, that Behaviour isn't registered so the code made no sense.
This will just improve the message slightly.
=> [FN] Receiving Cancelled message improved

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoW/SmartContractBlockDefinition.cs, src/Stratis.CirrusD/Properties/launchSettings.json
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4172
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4161
=> [SC] [PoA] Handle ConsensusErrors when mining.

src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/Connection/IConnectionManager.cs, src/Stratis.Bitcoin/P2P/Peer/INetworkPeer.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
Some methods and properties are not being used. This PR removes them.
=> Remove unused properties and methods

src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
=> Rewind data purging fix

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingFeature.cs, src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
Updates the way wallet components are added to ensure that the wallet feature is also being added.
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4209.
=> Add wallet feature to coldstaking feature

src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4111.
=> Fix boolean logic in NetworkPeer

src/Stratis.Features.FederatedPeg/FederatedPegBlockDefinition.cs
Clean up https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3314
=> [FS] Comment on FederatedPegBlockDefinition

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletFeature.cs
For https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3852
=> Add AddressBookManager to Cirrus.

src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs, src/Stratis.Bitcoin/Controllers/Models/StatusModel.cs, src/Stratis.Bitcoin/Controllers/NodeController.cs
It can be useful to interrogate what the node's public IP is.
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4216
=> [API] Show IP from self endpoint tracker

src/Stratis.Bitcoin/EventBus/CoreEvents/Peer/PeerMessageReceived.cs, src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnection.cs, src/Stratis.Bitcoin/P2P/Protocol/Message.cs, src/Stratis.Features.Diagnostic/PeerDiagnostic/PeerStatisticsCollector.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3572
=> [FN] Remove inconsistent MessageSize property from Message.

src/Stratis.Bitcoin/P2P/Protocol/InventoryVector.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/BitcoinSerializablePayload.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/InvPayload.cs, src/Stratis.Bitcoin/P2P/Protocol/Payloads/PayloadAttribute.cs
Removed some spurious logs that were taking up space in p2p.txt
=> Remove a few trace logs

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs, src/Stratis.SmartContracts.CLR/CallDataSerializer.cs, src/Stratis.SmartContracts.CLR/Serialization/ContractPrimitiveSerializer.cs, src/Stratis.SmartContracts.Core/SmartContractScript.cs
Contributes towards https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4212
=> [SC] Micro optimisations for SC script tests

src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs, src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalHistoryProvider.cs, src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
Cherry picked #3790 and removed old unused code.
=> [FS] History amendment for 3.0.4.1

src/Stratis.SmartContracts.Core/State/RootStorageCaches.cs
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4123.
=> [SC] Add lock to root storage caches

src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs, src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs, src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs, src/Stratis.Bitcoin/Connection/ConnectionManager.cs, src/Stratis.Bitcoin/P2P/PeerConnector.cs, src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs, src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs
A better fix for https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4248
=> [P2P] Add lock around addnode list

src/Stratis.Bitcoin.Features.SmartContracts/Models/BuildContractTransactionResponse.cs, src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs, src/Stratis.SmartContracts.Tests.Common/MockChain/MockChainNode.cs
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4284
=> [Smart contracts] Update API message when building and sending contract transactions

src/Stratis.SmartContracts.IntegrationTests/ContractPoAStressTests.cs, src/Stratis.SmartContracts.Tests.Common/MockChain/MockChainNode.cs
May need to be revisited as some of the related PRs go in.
=> [SC] CALL stress test

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTests.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
=> BlockRepository.GetBlocks returns genesis

src/Stratis.Bitcoin.Features.SignalR/Broadcasters/WalletInfoBroadcaster.cs, src/Stratis.Bitcoin.Features.SignalR/Events/WalletGeneralInfoClientEvent.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletBalanceModel.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.CirrusD/Program.cs, src/Stratis.CirrusD/Stratis.CirrusD.csproj
This PR adds SignalR to Cirrus node + added Wallet Balances by Address to the Address Broadcaster
=> Add SignalR and Wallet Address Info to Broadcaster

src/Stratis.Bitcoin.Features.SignalR/Broadcasters/WalletInfoBroadcaster.cs, src/Stratis.Bitcoin.Features.SignalR/Startup.cs
Fixes sending of multiple wallets over SignalR, also use same Serialiser Settings as Api Controllers
=> Multiple wallet and json fix

src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs, src/Stratis.SmartContracts.IntegrationTests/WhitelistedContractTests.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoATest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoAWhitelistRegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs, src/Stratis.SmartContracts.Tests.Common/SmartContractNodeBuilder.cs
This is to try and fix the intermittent windows CI build issues we are having.
=> [Tests] Define Smart Contract POA networks explicitly

src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/AllowedScriptTypeMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/CanGetSenderMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/CheckMinGasLimitSmartContractMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/OpSpendMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/P2PKHNotContractMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/SmartContractFormatLogicMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/MempoolRules/TxOutSmartContractExecMempoolRule.cs, src/Stratis.Bitcoin.Features.SmartContracts/PoA/MempoolRules/AllowedCodeHashLogicMempoolRule.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoAWhitelistRegTest.cs
The issue was that `SmartContractsPoARegTestWhiteList` had the same network name as `SmartContractsPoARegTest`.
=> [CI] Fix SmartContract Integration Tests

src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
@fassadlr Please review as per our discussion
=> [FN] Fix for transaction build verification

src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
This is re introducing workaround to improve performance for certain UTXO composits that would cause significant increase in time for building transactions
=> Revert changes to re-introduce UTXO filtering on WalletTransactionHandler.cs

src/Stratis.Features.SQLiteWalletRepository/External/ITransactionsToLists.cs, src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4451
=> Replace transaction time with block time

src/Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs, src/Stratis.Bitcoin.Features.SignalR/Broadcasters/WalletInfoBroadcaster.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletSyncManager.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs, src/Stratis.Features.SQLiteWalletRepository/External/ITransactionsToLists.cs, src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
This PR updates the `WalletController` for use of the `wallet-sync` endpoint from Core this is part of the SQLWalletDB compatibility update.
=> Update Wallet Controller to Support Core for Wallet Sync

src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs, src/Stratis.Bitcoin.Features.RPC.Tests/RPCParametersValueProviderTest.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, src/Stratis.Bitcoin.Features.RPC/RPCParametersValueProvider.cs
Merging latest PRs into 3.0.6 that were already merged into master:
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3992
https://github.com/stratisproject/StratisBitcoinFullNode/pull/4011
=> [FN] Merge latest prs

src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs, src/Stratis.Features.SQLiteWalletRepository/WalletContainer.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4444/
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4418/
=> Lock all or none and don't wait in ProcessBlocks

src/Stratis.Features.SQLiteWalletRepository/Tables/HDAddress.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4488/
=> Fix address ordering

src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
=> [RPC] GetTransaction (fixes issue 4466)

src/Stratis.Bitcoin/AsyncWork/AsyncLoop.cs
This is an experiment. 
Results below.
=> Lets fix the CI

src/Stratis.Bitcoin.Features.SignalR/Broadcasters/BroadcasterBase.cs, src/Stratis.Bitcoin.Features.SignalR/Broadcasters/CirrusWalletInfoBroadcaster.cs, src/Stratis.Bitcoin.Features.SignalR/Broadcasters/WalletInfoBroadcaster.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
Now have the option to includeAddressByBalance also reconciled CirrusWalletBroadcaster with Inheritance.
=> Get Wallet Balance with Optional includeAddressByBalance

src/Stratis.Bitcoin.Features.Wallet/TransactionData.cs, src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs, src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepositoryExt.cs, src/Stratis.Features.SQLiteWalletRepository/Tables/HDTransactionData.cs
Fixes https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4518
=> ScriptPubKey not RedeemScript to match Payments

src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinviewTests.cs, src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs, src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs, src/Stratis.Bitcoin.Features.Consensus/FullNodeBuilderConsensusExtension.cs, src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Bitcoin/Configuration/Settings/ConsensusSettings.cs, src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs
=> [FN] Make coinview cache size configurable

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
Mostly around initialization and importing json wallets.
=> [SQLLiteRepo] Remove some logging ambiguity 

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs, src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs, src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
Same changes as those on the master branch (PR #4051)
=> Fix immature coin balance 2

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4567/
=> Rewind wallets exceeding consensus tip on startup

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AccountBasedWalletHistoryTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/AccountBasedWalletHistoryQuery.cs
Fix for incorrect history in some circumstances, see https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_boards/board/t/StratisBitcoinFullNode%20Team/Stories/?workitem=4551
=> [Hackathon] Fix transaction history

src/Stratis.Features.SQLiteWalletRepository/DBConnection.cs, src/Stratis.Features.SQLiteWalletRepository/External/ITransactionsToLists.cs, src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs, src/Stratis.Features.SQLiteWalletRepository/Tables/HDWallet.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4589
=> Ensure locks are released in error scenario

src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs, src/Stratis.Features.SQLiteWalletRepository/WalletContainer.cs
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4604
=> Ensure batch deadline is initiailized on batch start

src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
Added a try-catch to make sure we release locks upon startbatch failure. Github diff is quite bad, here is a screenshot from VS
=> [SC] Lock release when StartBatch fails

src/NBitcoin.Tests/NetworkTests.cs, src/NBitcoin/BIP9Deployments.cs, src/NBitcoin/Consensus.cs, src/NBitcoin/IConsensus.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs, src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs, src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs, src/Stratis.Bitcoin.IntegrationTests/ColdStakingTests.cs, src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs, src/Stratis.Bitcoin.Networks/BitcoinMain.cs, src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs, src/Stratis.Bitcoin.Networks/BitcoinTest.cs, src/Stratis.Bitcoin.Networks/StratisMain.cs, src/Stratis.Bitcoin.Networks/StratisRegTest.cs, src/Stratis.Bitcoin.Networks/StratisTest.cs, src/Stratis.Bitcoin/Base/Deployments/Models/ThresholdStateModel.cs, src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs, src/Stratis.Sidechains.Networks/CirrusMain.cs, src/Stratis.Sidechains.Networks/CirrusRegTest.cs, src/Stratis.Sidechains.Networks/CirrusTest.cs, src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs, src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs
* Introduce variable thresholds for BIP9
* Use correct threshold for test
* Build error
* Update src/Stratis.Bitcoin.IntegrationTests/ColdStakingTests.cs
Co-Authored-By: Francois de la Rouviere <fassadlr@gmail.com>
=> [FN] Introduce variable thresholds for BIP9 (#3912)

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
=> Show history correctly when multiple inputs used in CoinStake.

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
* History stake fix
* Test demonstrating the fix
* Retrigger CI
* woops
=> Show history correctly when multiple inputs used in CoinStake. (#4059)

src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
This fix was only applied to 3.0.6
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3979/files
=> [FN] Added changes from 3.0.6-rc that were not pushed to master

src/Stratis.Bitcoin.Features.Wallet/Services/WalletService.cs
This PR will enable SQL pagination which is used by StratisCore 2.0 for the new infinite scroll functionality for transaction history
=> Enable paging for core infinite scrolling

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingFeature.cs, src/Stratis.Bitcoin.Features.ColdStaking/Services/ColdStakingService.cs, src/Stratis.Bitcoin.Features.ColdStaking/Services/IColdStakingService.cs, src/Stratis.Bitcoin.Features.SignalR/Broadcasters/ColdStakingBroadcaster.cs, src/Stratis.Bitcoin.Features.SignalR/Events/ColdStakingInfoClientEvent.cs, src/Stratis.Bitcoin.Features.SignalR/Stratis.Bitcoin.Features.SignalR.csproj, src/Stratis.StratisD/Program.cs
Adds SignalR support for cold staking info.
=> Add cold staking info broadcaster (SignalR)

src/Stratis.Bitcoin.Features.Miner/Controllers/MiningRPCController.cs, src/Stratis.Bitcoin.Features.RPC/RPCClient.cs, src/Stratis.Bitcoin.Features.RPC/RPCOperations.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs, src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs
Moderately useful for test purposes, it is also used by NBitcoin's own test framework.
=> [FN] Add generatetoaddress RPC

src/Stratis.Bitcoin.Features.PoA/PoAConsensusErrors.cs, src/Stratis.CirrusD/Program.cs, src/Stratis.CirrusDnsD/Program.cs, src/Stratis.CirrusDnsD/Stratis.CirrusDnsD.csproj, src/Stratis.CirrusMinerD/Program.cs, src/Stratis.CirrusPegD/Program.cs, src/Stratis.Features.Collateral/CheckCollateralCommitmentHeightRule.cs, src/Stratis.Features.Collateral/CheckCollateralFullValidationRule.cs, src/Stratis.Features.Collateral/CollateralFeature.cs, src/Stratis.Features.Collateral/CollateralPoAMiner.cs, src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainFederationNodeRunner.cs, src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainMinerNodeRunner.cs, src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs, src/Stratis.Features.FederatedPeg.Tests/CollateralHeightCommitmentEncoderTests.cs
=> Merge PR 4127 to release/3.0.8.0 (Split the Check Collateral Full Validation Rule) 

src/Stratis.Features.Collateral/CheckCollateralCommitmentHeightRule.cs
=> Merge PR 4139 to release/3.0.5.1 (CheckCollateralCommitmentHeightRule should ignore the Genesis block)

src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/BroadcasterBehavior.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/BroadcasterManagerBase.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/FullNodeBroadcasterManager.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/TransactionBroadcastEntry.cs, src/Stratis.Bitcoin.Features.Wallet/Broadcasting/TransactionBroadcastState.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/HdOperations.cs, src/Stratis.Bitcoin.Features.Wallet/Interfaces/IBroadcasterManager.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletStatsModel.cs, src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs, src/Stratis.Features.FederatedPeg/TargetChain/SignedMultisigTransactionBroadcaster.cs
I'm learning stratis codebase and meanwhile fixing some minor things around the codebase, hope this helps.
=> Code cleanup, fixed xml comments, redundant usings

src/Stratis.Bitcoin.Networks/StratisMain.cs
=> Update ColdStaking Window on release/3.0.8.0

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AccountBasedWalletHistoryTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/AccountBasedPaymentDetailsExtensions.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/AccountBasedWalletHistoryQuery.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/ChangePayment.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/AddressesModel.cs
* Add accounts-based history (ref. https://github.com/stratisproject/StratisBitcoinFullNode/pull/4044)
* Fix transaction history (ref. https://github.com/stratisproject/StratisBitcoinFullNode/pull/4060)
=> [Unrestricted] Hackathon history fixes

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AccountBasedWalletHistoryTests.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/AccountBasedPaymentDetailsExtensions.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/AccountBasedWalletHistoryQuery.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/ChangePayment.cs, src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Models/AddressesModel.cs
* Add accounts-based history (ref. https://github.com/stratisproject/StratisBitcoinFullNode/pull/4044)
* Fix transaction history (ref. https://github.com/stratisproject/StratisBitcoinFullNode/pull/4060)
=> Hackathon history fixes

src/FederationSetup/FederationSetup.cs, src/FederationSetup/FederationSetup.csproj, src/FederationSetup/Program.cs, src/FederationSetup/RecoveryTransactionCreator.cs
This tool fits into step 4 of the following overall process related to changing a federation's multisig members. 
The order of these steps are important:
```
1. Notify all parties and update documentation etc. Decide when to update wallet UI.
2. Ensure both sides haven't seen any transfers within maxreorg blocks.
3. STOP the UP-TO-DATE old federation nodes and BACK-UP the data folders.
4. Collect signatures and generate the sidechain and mainchain funds-recovery transactions (will provide this tool. The tool will run against the backed up data folder.)
then IF SUCCESSFUL in generating the funds-recovery transaction:
5. Move all new-federation wallet nodes to the new address.
6. Move all funds to new addresses using the funds-recovery transactions.
7. Revert anything sent erroneously to …
```
=> Create funds recovery tx

src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/BalancesController.cs
=> Get balances at any height via controller

src/NBitcoin.Tests/NetworkTests.cs, src/Stratis.Bitcoin.Networks/StratisTest.cs, src/Stratis.Bitcoin.Tests/Consensus/CheckpointsTest.cs
This speeds up node synchronization on testnet, looks like checkpoints for it were updated >4 months ago. 
Block used for new checkpoint: https://chainz.cryptoid.info/strat-test/block.dws?1245000.htm
=> Added testnet checkpoint

src/FederationSetup/FederationSetup.cs, src/FederationSetup/Program.cs, src/FederationSetup/RecoveryTransactionCreator.cs
Move Stratis and Cirrus funds to an address based on the new redeem script format.
In addition Stratis funds are burned and ear-marked for the new Strax multisig address.
=> Move Stratis and Cirrus funds to an address based on the new redeem script format

src/Stratis.Bitcoin.Features.Consensus/BlockNotFoundException.cs, src/Stratis.Bitcoin.Features.RPC.Tests/RPCMiddlewareTest.cs, src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs, src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs, src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs, src/Stratis.Bitcoin/Utilities/FileStorage.cs
Porting this from the master branch
=> [3.0.8.0] RPC content type

src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs, src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreControllerTests.cs, src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs, src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs, src/Stratis.Bitcoin.Features.BlockStore/Models/LastBalanceDecreaseTransactionModel.cs, src/Stratis.Bitcoin.Features.BlockStore/Models/UtxoModel.cs, src/Stratis.Bitcoin.Features.BlockStore/UtxoIndexing/ReconstructedCoinviewContext.cs, src/Stratis.Bitcoin.Features.BlockStore/UtxoIndexing/UtxoIndexer.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
This will allow swap transactions to have their amounts included in vote weight calculations.
=> Allow retrieval of the last transaction affecting an address

src/AddressOwnershipTool/AddressOwnershipService.cs, src/AddressOwnershipTool/AddressOwnershipTool.csproj, src/AddressOwnershipTool/DistributedOwnershipTransaction.cs, src/AddressOwnershipTool/NodeApiClient.cs, src/AddressOwnershipTool/OwnershipTransaction.cs, src/AddressOwnershipTool/Program.cs
Based on the swap distribution tool, although it will distribute once per Stratis address with an ownership signature rather than once per burn transaction.
=> Address ownership tool update
