stratisproject/StratisBitcoinFullNode

Stratis.Bitcoin.Tests/Class1.cs

Increase timeout on tests (from 10s to 30s) so that they pass on my machine.
Also make it easy to see minutes, seconds, in the values.

Increase timeout on tests (from 10s to 30s) so that they pass

---

Stratis.Bitcoin.Tests/Features/BlockNotificationFeatureTest.cs
Stratis.Bitcoin/Notifications/BlockNotification.cs
Stratis.Bitcoin/Notifications/BlockNotificationFeature.cs
Stratis.Bitcoin/Notifications/BlockNotificationStartHash.cs

Added BlockNotification service whose purpose is to broadcast about blocks discovered on the network, starting from the hash of the last broadcasted block. Currently not in use.

Added BlockNotification service 

---

Stratis.BitcoinD/Checks.cs
Stratis.BitcoinD/Program.cs

This code checks for read/write access to the file system, for each of the data directories found in NodeSettings.  I've added a file called Checks.cs, with the Checks class, and VerifyAccess method that performs the check by attempting to create temporary sub-directories, and then deleting them after the test.  Throws an UnauthorizedAccessException, which is handled by Main, and lets the user know which, if any, directories are inaccessible, instead of just giving an unhandled exception.

Fix for issue #76: Daemon crashes if first ran as root, then as regular user on Linux

---

.editorconfig
Documentation/coding-style.md
Rebracer.xml
Stratis.Bitcoin.FullNode.vs2017.sln
Stratis.Bitcoin/RPC/Models/TransactionModel.cs

Enforce code-styles via .editorconfig (VS2017)
Add .editorconfig file to project root, enforcing Documentation/coding-style.md where explicit, and providing additional suggestions based on style of existing code.
Updates coding-sytle document to reflect this change and removes reference to stratis.fullnode.vssettings which does not exist in the repo.
Apply styles and suggestions to TransactionModel.cs

Enforce style rules via EditorConfig

---

Stratis.Bitcoin.IntegrationTests/Class1.cs
Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
Stratis.Bitcoin.IntegrationTests/project.json
Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
Stratis.Bitcoin.Tests/Utilities/LinqExtensionsTest.cs
Stratis.Bitcoin.Tests/project.json
Stratis.Bitcoin/BlockPulling/BlockPuller.cs
Stratis.Bitcoin/Connection/ConnectionManager.cs
Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs
Stratis.Bitcoin/RPC/Controllers/ConnectionManagerController.cs
Stratis.Bitcoin/RPC/Controllers/FullNodeController.cs
Stratis.Bitcoin/RPC/Models/GetInfoModel.cs
Stratis.Bitcoin/Stratis.Bitcoin.csproj
Stratis.Bitcoin/Utilities/LinqExtensions.cs
Stratis.Bitcoin/Utilities/NodeExtensions.cs
Stratis.Bitcoin/project.json
Stratis.BitcoinD/Stratis.BitcoinD.csproj
Stratis.BitcoinD/project.json
Stratis.StratisD/Stratis.StratisD.csproj
Stratis.StratisD/project.json

Implement GetInfo.timeoffset property, which was stubbed as a zero when RPC command was initially implemented.
Add LinqExtension to calculate median
Add GetMedianTimeOffset extension for Nodes collection
RPC GetInfo uses ConnectionManager.NodesCollection.GetMedianTimeOffset()
Disallow direct updates to ConnectionManager.ConnectedNodes via IReadOnlyNodesCollection 
Rename ConnectionManager.(Add/Remove)Node to ConnectionManager.(Add/Remove)NodeAddress
Fix some style violations in ConnectionManager
Fixes: https://github.com/stratisproject/StratisBitcoinFullNode/issues/115

Finish RPC GetInfo.timeoffset, IReadOnlyNodesCollection 

---

Stratis.Bitcoin.Tests/MemoryPool/MempoolPersistenceTest.cs
Stratis.Bitcoin.Tests/RPC/Controller/BaseRPCControllerTest.cs
Stratis.Bitcoin/Builder/BaseFeature.cs
Stratis.Bitcoin/MemoryPool/MempoolFeature.cs
Stratis.Bitcoin/MemoryPool/MempoolManager.cs
Stratis.Bitcoin/MemoryPool/MempoolPersistence.cs
Stratis.Bitcoin/MemoryPool/TxMemPoolEntry.cs

Persist mempool to disk and load it on node start
Use binary format for memorypool.dat in node data directory
Add IMempoolPersistence to MempoolFeatures
Load MemoryPool on MemoryPoolFeature.Start(); Save on  .Stop().
Push loaded transactions to MemPool with validation.
Handle bad files with ignore.
Delete mempool.dat on Stop() if there are no memory pool entries to persist.
Fixes https://github.com/stratisproject/StratisBitcoinFullNode/issues/109

Persist mempool to disk and load it on node start

---

.gitignore
Stratis.Bitcoin.IntegrationTests/Class1.cs
Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
Stratis.Bitcoin.IntegrationTests/project.json
Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs
Stratis.Bitcoin.Tests/RPC/Controller/MempoolActionTests.cs
Stratis.Bitcoin.Tests/project.json
Stratis.Bitcoin/Consensus/CoinViews/DBreezeCoinView.cs
Stratis.Bitcoin/Consensus/ConsensusErrors.cs
Stratis.Bitcoin/Consensus/ConsensusFeature.cs
Stratis.Bitcoin/Consensus/ConsensusLoop.cs
Stratis.Bitcoin/Consensus/ConsensusOptions.cs
Stratis.Bitcoin/Consensus/ContextualInformation.cs
Stratis.Bitcoin/Consensus/PosConsensusValidator.cs
Stratis.Bitcoin/Consensus/PowConsensusValidator.cs
Stratis.Bitcoin/Consensus/StakeChainStore.cs
Stratis.Bitcoin/Consensus/ThresholdConditionCache.cs
Stratis.Bitcoin/DBreezeSingleThreadSession.cs
Stratis.Bitcoin/FullNode.cs
Stratis.Bitcoin/MemoryPool/MemPoolCoinView.cs
Stratis.Bitcoin/MemoryPool/MempoolOrphans.cs
Stratis.Bitcoin/MemoryPool/MempoolValidator.cs
Stratis.Bitcoin/MemoryPool/TxMemPoolEntry.cs
Stratis.Bitcoin/RPC/Controllers/BaseRPCController.cs
Stratis.Bitcoin/RPC/Controllers/FullNodeController.cs
Stratis.Bitcoin/Utilities/AsyncDictionary.cs
Stratis.Bitcoin/project.json
Stratis.BitcoinD/project.json
Stratis.StratisD/Program.cs
Stratis.StratisD/project.json

This commit adds support for validating the stratis consensus rules but without any calculation of stake proofs.
Also the ConsensusValidator was split up to a PowConsensusValidator and a PosConsensusValidator that inherits the from the pow class with additional logic to calculate stake work and stake reward.

Stratis Validation

---

Stratis.Bitcoin/Configuration/NodeSettings.cs

Previous commit [ https://github.com/stratisproject/StratisBitcoinFullNode/pull/125 ] causes null reference error in startup on non-Stratis network. This fixes by preventing NodeSettings.Network from being null.

Bug Fix: Prevent Null Network in NodeSettings

---

Stratis.Bitcoin/BlockStore/BlockStoreLoop.cs

This fix will restart download after a trashold.

Block store is stalling when a block is lost to the downloader

---

Stratis.Bitcoin/RPC/Converters/BtcDecimalJsonConverter.cs

Serializing decimal values with BtcDecimalJsonConverter  didn't work correct when a decimal separator other than a period was configured. This commit fixes this by using InvariantCulture when converting decimal to string.

Fix for BtcDecimalJsonConverter

---

Stratis.Bitcoin.Tests/BlockStore/BlockStoreCachePerformanceCounterTest.cs
Stratis.Bitcoin.Tests/BlockStore/BlockStoreCachePerformanceSnapshotTest.cs
Stratis.Bitcoin.Tests/BlockStore/BlockStoreRepositoryPerformanceCounterTest.cs
Stratis.Bitcoin.Tests/BlockStore/BlockStoreRepositoryPerformanceSnapshotTest.cs
Stratis.Bitcoin/BlockStore/BlockRepository.cs
Stratis.Bitcoin/BlockStore/BlockStoreCache.cs
Stratis.Bitcoin/BlockStore/BlockStoreCachePerformanceCounter.cs
Stratis.Bitcoin/BlockStore/BlockStoreLoop.cs
Stratis.Bitcoin/BlockStore/BlockStoreRepositoryPerformanceCounter.cs
Stratis.Bitcoin/BlockStore/BlockStoreStats.cs

I've added performance counters for both the repository and the cache. These are added to a blockstorestats class that is added to the blockstoreloop which logs the statistics for the blockstore every 10 seconds. Please let me know what you think.

Add blockstore repository and cache performance counters.

---

Stratis.Bitcoin.Tests/Builder/FullNodeBuilderExtensionsTest.cs
Stratis.Bitcoin/Configuration/NodeSettings.cs

The help stated -testnet=1or0 and -regtest=1or0 which didn't work when I was trying to get onto the testnet. Looking at how the arguments are parsed in the nodesettings and program.cs led me to believe the help text is wrong so I corrected it. Also made some tests to see if they are now picked up correctly.

Fix command line help text for testnet and regtest flags

---

Stratis.Bitcoin/Configuration/NodeSettings.cs
Stratis.Bitcoin/Configuration/TextFileConfiguration.cs

* Added a configurable uri for the api. there are default URIs for bitcoin and stratis but the URI can be set manually in the cli using `apiuri=http://localhost:5200`
* Changed the root directory for the stratis full node.
The new folders structure is as follows
in Roaming (on windows):
```
StratisNode
|_ bitcoin
|_ Main
|_ TestNet
|_ stratis
|_ StratisMain
|_ StratisTest
```
@dangershony @dev0tion 
Guys, if you approve, don't merge yet, I want to merge and then explain to the testers how to move their files to the new structure.

configurable api uri

---

Stratis.Bitcoin/Wallet/Controllers/WalletController.cs
Stratis.Bitcoin/Wallet/IWalletManager.cs
Stratis.Bitcoin/Wallet/Models/RequestModels.cs
Stratis.Bitcoin/Wallet/WalletManager.cs

so in order to create a wallet you call:
1. api/wallet/mnemonic and get a mnemonic
2. api/wallet/create twice with the same mnemonic
@dev0tion @dangershony

Added mnemonic as optional input to the create wallet method

---

Stratis.Bitcoin.Tests/Notifications/BlockNotificationFeatureTest.cs
Stratis.Bitcoin.Tests/Notifications/BlockNotificationTest.cs
Stratis.Bitcoin/AsyncLoopFactory.cs
Stratis.Bitcoin/Notifications/BlockNotification.cs

This makes testing methods using the AsyncLoop class easier by providing a factory that can be injected into the constructor of the class. 
Methods using this asyncloop should slowly be refactored from void to Task as their return type.

Introduce AsyncLoopFactory and fix flaky blocknotification test

---

Stratis.Bitcoin/Configuration/NodeSettings.cs

The path in the nodeSettings.DataDir variable contains a mixture of \ and / characters. This change will ensure we use the appropriate operating system specific path separator.

Instead of hard coding / to in nodeSettings.DataDir use Path.Combine

---

Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs
Stratis.Bitcoin/Wallet/WalletManager.cs

```
The following error occurred while creating wallet
[2:55] 
crit: Stratis.Bitcoin.Consensus[0]
Consensus loop unhandled exception (Tip:118471)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at Stratis.Bitcoin.Wallet.WalletManager.UpdateLastBlockSyncedHeight(ChainedBlock chainedBlock) in C:\Users\stratis dev\Documents\StratisBitcoinFullNode\Stratis.Bitcoin\Wallet\WalletManager.cs:line 881
at Stratis.Bitcoin.Wallet.WalletManager.ProcessBlock(Block block, ChainedBlock chainedBlock) in C:\Users\stratis dev\Documents\StratisBitcoinFullNode\Stratis.Bitcoin\Wallet\WalletManager.cs:line 629
at …
```

Solve System.InvalidOperationException: Collection was modified

---

Stratis.Bitcoin.Tests/Wallet/AccountRootTest.cs
Stratis.Bitcoin.Tests/Wallet/HdAccountTest.cs
Stratis.Bitcoin.Tests/Wallet/HdAddressTest.cs
Stratis.Bitcoin.Tests/Wallet/Notifications/BlockObserverTest.cs
Stratis.Bitcoin.Tests/Wallet/Notifications/BlockSubscriberTest.cs
Stratis.Bitcoin.Tests/Wallet/Notifications/TransactionObserverTest.cs
Stratis.Bitcoin.Tests/Wallet/Notifications/TransactionSubscriberTest.cs
Stratis.Bitcoin.Tests/Wallet/SpendingDetailsTest.cs
Stratis.Bitcoin.Tests/Wallet/TransactionDataTest.cs
Stratis.Bitcoin.Tests/Wallet/WalletTest.cs
Stratis.Bitcoin.Tests/Wallet/WalletTestBase.cs
Stratis.Bitcoin/Wallet/Wallet.cs

Should be pretty straight forward tested the wallet model methods and made some improvements there based on the test results.
I would like to suggest as a future improvement we create an hdpath parser that returns an hdpath model to centralize that behavior. It will also make the meaning of the actual data being separated by slashes more obvious to other programmers.
Up next will be the manager and syncmanager. After that I will move to the watchonlywallet.

Wallet tests and wallet notification tests

---

Stratis.Bitcoin.Tests/Wallet/TransactionDataTest.cs

Because these tests were merged after some updates have been made to the class one was failing. I also noticed I missed a test case so added that.

Fix failing TransactionData unit tests

---

Stratis.Bitcoin.Tests/AsyncLoopTest.cs
Stratis.Bitcoin.Tests/DateTimeProviderTest.cs
Stratis.Bitcoin.Tests/PeriodicTaskTest.cs
Stratis.Bitcoin/BlockStore/BlockRepository.cs

Currently the Block Repository supports NoSQL indexes for "Block" and "Transaction".
- This pull request (#205) adds "Script" and "Output" indexes. 
- Index insertion has been changed to key order as that provides performance gains.
Indexing is dependent on the "-txindex" command line switch as with "Transaction" indexing. This can be changed to give us finer grained control.
Using the new "Script" index an address hash can be used to select the list of outputs (transaction hash + output number) of the transactions that the address appears in:
- Task<List<byte[]>> GetTrxOutByAddrAsync(BitcoinAddress addr)
Using the new "Outputs" index also allows us to determine which transactions these outputs have been spent to. Null entries will appear in the output list for corresponding unspent …

Update BlockStore to index address hash -> transaction hashes

---

Stratis.Bitcoin.Common/Stratis.Bitcoin.Common.csproj
Stratis.Bitcoin.IntegrationTests/Data/test.wallet.json
Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs
Stratis.Bitcoin.IntegrationTests/Program.cs
Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
Stratis.Bitcoin.IntegrationTests/WalletTests.cs
Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
Stratis.Bitcoin/Consensus/CoinViews/CachedCoinView.cs
Stratis.Bitcoin/MemoryPool/MemPoolCoinView.cs
Stratis.Bitcoin/Miner/PowMining.cs
Stratis.Bitcoin/RPC/Controllers/FullNodeController.cs
Stratis.Bitcoin/RPC/Controllers/WalletRPCController.cs
Stratis.Bitcoin/RPC/ModelBinders/DestinationModelBinder.cs
Stratis.Bitcoin/RPC/ModelBinders/MoneyModelBinder.cs
Stratis.Bitcoin/RPC/RPCMiddleware.cs
Stratis.Bitcoin/RPC/RPCServerException.cs
Stratis.Bitcoin/RPC/WebHostExtensions.cs
Stratis.Bitcoin/Stratis.Bitcoin.csproj
Stratis.Bitcoin/Utilities/FullNodeExtensions.cs
Stratis.Bitcoin/Wallet/IWalletManager.cs
Stratis.Bitcoin/Wallet/WalletFeature.cs
Stratis.Bitcoin/Wallet/WalletManager.cs

Based on top of https://github.com/stratisproject/StratisBitcoinFullNode/pull/220#discussion_r126923128
* add support for net462 build, this make debug experience better, and we can use profilers
* stratis node runner use a preloaded wallet, this will make the node faster to bootstrap for tests
* creation of model binders for the rpc controller
* block generation only wait the block repository to be coherent at the end
If you have problem debugging the project, please make sure to uncheck `Use managed Compatibility Mode`

Make RPC methods easier to create with binders, improve testing

---

Stratis.Bitcoin.IntegrationTests/WalletTests.cs
Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs
Stratis.Bitcoin/RPC/Controllers/WalletRPCController.cs
Stratis.Bitcoin/Wallet/Controllers/WalletController.cs
Stratis.Bitcoin/Wallet/IWalletManager.cs
Stratis.Bitcoin/Wallet/WalletAccountReference.cs
Stratis.Bitcoin/Wallet/WalletManager.cs

The pair accountname and walletname will often travel together, this make sense to create a value object to bundle them together instead of passing them as individual string.

Introduce WalletAccountReference type

---

Stratis.Bitcoin.IntegrationTests/WalletTests.cs
Stratis.Bitcoin.Tests/Wallet/WalletControllerTest.cs
Stratis.Bitcoin/RPC/Controllers/WalletRPCController.cs
Stratis.Bitcoin/Wallet/Controllers/WalletController.cs
Stratis.Bitcoin/Wallet/IWalletManager.cs
Stratis.Bitcoin/Wallet/Models/RequestModels.cs
Stratis.Bitcoin/Wallet/Validations/IsBitcoinAddressAttribute.cs
Stratis.Bitcoin/Wallet/WalletAccountReference.cs
Stratis.Bitcoin/Wallet/WalletManager.cs

Based on top of https://github.com/stratisproject/StratisBitcoinFullNode/pull/227
Move parameter validation out of WalletManager and out of controllers. 
Note that I did not tested that `Network` get properly injected into the `ValidationContext` yet.

Move string validation logic out of WalletManager

---

Stratis.Bitcoin/Settings.StyleCop

Added rules corresponding to rules 
2 (SA1027): We use four spaces of indentation (no tabs).
4 (SA1101): We always use this. to easily distinguish instance members.
5 (SA1400): We always specify the visibility, even if it's the default
6 (SA1210): Namespace declarations should be sorted alphabetically.
7 (SA1507): Avoid more than one empty line at any time
8 (SA1025): Avoid spurious free spaces
12 (SA1303): We use PascalCasing to name all our constant local variables and fields. 
in our documentation
I think this is a good place to start.
Please make sure that when you submit a PR, you don't mix formatting and code changes at the same time as it distracts the reviewer and make the PR take longer to review.

Added rules in StyleCop

---

Stratis.Bitcoin/Configuration/DataFolder.cs
Stratis.Bitcoin/Configuration/NodeServerEndpoint.cs
Stratis.Bitcoin/Configuration/NodeSettings.cs
Stratis.Bitcoin/Configuration/Settings/CacheSettings.cs
Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
Stratis.Bitcoin/Configuration/Settings/LogSettings.cs
Stratis.Bitcoin/Configuration/Settings/MempoolSettings.cs
Stratis.Bitcoin/Configuration/Settings/RpcSettings.cs
Stratis.Bitcoin/Configuration/Settings/StoreSettings.cs
Stratis.Bitcoin/Configuration/TextFileConfiguration.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolBehavior.cs

XML documentation comments for Stratis.Bitcoin.Configuration files. Also fixes a code style in many places according to the current guideline. 
All code changes by this PR should be equivalent to the original code - i.e. the behavior of all the code should be unchanged by this PR.

Feature/xmldoc stratis.bitcoin.configuration

---

Stratis.Bitcoin/Features/MemoryPool/MemPoolCoinView.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolBehavior.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolErrors.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolFeature.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolManager.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolOrphans.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolPerformanceCounter.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolSignaled.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolValidationContext.cs
Stratis.Bitcoin/Features/MemoryPool/MempoolValidator.cs
Stratis.Bitcoin/Features/MemoryPool/TxMemPool.cs
Stratis.Bitcoin/Features/MemoryPool/TxMemPoolEntry.cs

Clean up tabbing and warnings in mempool feature.

---

Stratis.Bitcoin.Tests/Builder/Feature/FeatureCollectionTest.cs
Stratis.Bitcoin.Tests/Builder/Feature/FeatureRegistrationTest.cs
Stratis.Bitcoin.Tests/Builder/Feature/FeaturesExtensionsTest.cs
Stratis.Bitcoin.Tests/Builder/FullNodeFeatureExecutorTest.cs
Stratis.Bitcoin.Tests/Builder/FullNodeServiceProviderTest.cs
Stratis.Bitcoin/Builder/Feature/FeaturesExtensions.cs
Stratis.Bitcoin/Builder/Feature/FullNodeFeature.cs
Stratis.Bitcoin/Builder/Feature/MissingDependencyException.cs
Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs
Stratis.Bitcoin/Features/Miner/MiningFeature.cs
Stratis.Bitcoin/Features/RPC/RPCFeature.cs
Stratis.StratisD/Program.cs

Add a hook for a dependency check when running node feature executor. Throw exception if a feature's dependency is missing.
Fix for issue #285

Validate feature dependencies on feature startup

---

Stratis.Bitcoin.Tests/Wallet/HdAccountTest.cs
Stratis.Bitcoin.Tests/Wallet/HdAddressTest.cs
Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs
Stratis.Bitcoin/Features/Wallet/HdOperations.cs
Stratis.Bitcoin/Features/Wallet/IWalletManager.cs
Stratis.Bitcoin/Features/Wallet/Wallet.cs
Stratis.Bitcoin/Features/Wallet/WalletManager.cs

* Moved the IWalletManager.CreateNewAccount method to the Wallet object and renamed it to AddNewAccount to better reflect this method's functionalities. 
I started with doing this but then instead of moving further along I worked on extracting HD-related methods to a separate class.
* Extracted all the methods relating to HD wallets' addresses and accounts to a separate class.
* Updated NStratis to the latest submodule

WalletManager refactoring part 1

---

Stratis.Bitcoin.Tests/Wallet/WalletManagerTest.cs

Wow!
The problem came from the fact that the Stratis network, when initialized, sets the Transaction.TimeStamp value to 'true' (look in Network.InitStratisTest() and Network.InitStratisMain()) in order for proof-of-stake to work. 
Now, there are a few tests where we're trying to parse Bitcoin transaction, but since the TimeStamp is set to true, the execution path is different and the bitcoin transaction tests are failing.
Here we're resetting the TimeStamp after every test so it doesn't cause any trouble.

Fixed failing unit tests

---

Stratis.Bitcoin.Tests/Notifications/NotificationsControllerTest.cs
Stratis.Bitcoin/Features/Notifications/BlockNotification.cs
Stratis.Bitcoin/Features/Notifications/BlockNotificationFeature.cs
Stratis.Bitcoin/Features/Notifications/Controllers/NotificationsController.cs
Stratis.Bitcoin/Features/Notifications/TransactionNotification.cs
Stratis.Bitcoin/Features/Notifications/TransactionNotificationFeature.cs
Stratis.Bitcoin/Features/Notifications/TransactionReceiver.cs

With the controller method that was added, it's now easy to move the chain to a certain location using a block height or a block hash, when using the BlockNotification Feature.
This is very useful when working on the Breeze wallet when we want the sync to move backwards or forward.

Added controller providing operations on blocks and transactions notifications.

---

Documentation/using-logging.md

recently we changed how `-debug` argument works, yet we forgot to change the docu

update of logging docu after recent change

---

Stratis.Bitcoin.IntegrationTests/MinerTests.cs
Stratis.Bitcoin.Tests/Features/MemoryPool/MempoolValidatorTest.cs
Stratis.Bitcoin.Tests/Features/MemoryPool/TestChainFactory.cs
Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj

Create a sample chain and validate a valid P2PKH transaction with the mempool validator.
This also includes an helper method for creating a default chain to attach transactions to (which was adapted from code in MinerTest in integration tests).

Mempool validator - test a valid P2PKH tx

---

Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.Bitcoin.Features.BlockStore.Tests.csproj

Adds a required reference to Stratis.Bitcoin.Features.BlockStore.Tests

Fix for not being able to debug tests

---

Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs

- On Windows the wallet test cases are creating the TestData folder on the current drive as e.g. "C:\TestData". 
- On Linux a permission denied error is raised as "/" is not accessible. 
This PR fixes that by removing the leading "/" which makes the path absolute.

Change /TestData/... to TestData/... in Wallet tests

---

Stratis.Bitcoin.Features.IndexStore/IndexRepository.cs
Stratis.Bitcoin.Features.IndexStore/IndexSetings.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreBehaviour.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreCache.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreFeature.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreLoop.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreManager.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreRPCController.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreSignaled.cs
Stratis.Bitcoin.IntegrationTests/IndexerTests.cs
Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs

This allows the IndexStore indexes to be configured using the feature options mechanism.
See PR https://github.com/stratisproject/StratisBitcoinFullNode/issues/329

Allow required indexes to be specified using IndexStore settings

---

Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs

The failure presents as an unhandled "WebException" and is being triggered in the RPCClient.cs file:
```
... (line 694)
catch(WebException ex)
{
if(ex.Response == null || ex.Response.ContentLength == 0 ||
!ex.Response.ContentType.Equals("application/json", StringComparison.Ordinal))
throw;
errorResponse = ex.Response;
response = RPCResponse.Load(await ToMemoryStreamAsync(errorResponse.GetResponseStream()).ConfigureAwait(false));
if(throwIfRPCError)
response.ThrowIfError();
}
...
```
The current situation is that the content type is not being set on JSON formatted error responses (within RPCMiddleware.cs).  As a result the above "throw" gets executed instead of the code that follows. This affects the type of error being produced being "WebException" instead of "RPCException". Consequently …

Set content type to fix failing CheckRPCFailures integration test

---

Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs
Stratis.Bitcoin.Features.IndexStore/IndexStoreLoop.cs
Stratis.Bitcoin.IntegrationTests/BlockStoreTests.cs
Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs
Stratis.Bitcoin.IntegrationTests/NodeSync.cs
Stratis.Bitcoin.IntegrationTests/TestHelper.cs
Stratis.Bitcoin/Base/ChainState.cs
Stratis.Bitcoin/FullNode.cs

This PR addresses 2 TODO's relating to BlockStore and IndexStore in FullNode.cs. It includes:
- Moving "HighestPersistedBlock" from ChainState to the BlockRepository
- Moving the logging code relating to the above value to the Blockstore feature
- It also addresses a bug in the new StoreName method override in the Index Repository

Move "HighestPersistedBlock" to BlockStore feature

---

Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationFeatureTest.cs
Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs
Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
Stratis.Bitcoin.Features.Notifications/BlockNotification.cs

Fix for a bug that happened when syncing from a height or a hash.
When asked to sync, the block puller was starting to sync from the next block.
Now when it's asked to sync from height h, we move the puller to height h-1 so that the next block is the one we seek to start the syncing from.

Take puller one block back when syncing

---

Stratis.Bitcoin/Configuration/NodeSettings.cs

"Stratis node uses -listen for what Bitcoin Core uses -bind. Bitcoin Core also defines -listen, but uses it for different thing. This is probably not an intention and the parameters should be compatible." - Aprogiena
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/259
This PR changes the name of the "listen" parameter to "bind".

Change name of command line parameter "listen" to "bind"

---

Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs

Fixed LoadWalletWithExistingWalletLoadsWalletOntoManager. This should prevent it from failing all the time.

Rework walletmanager test

---

Stratis.Bitcoin.Features.Wallet/WalletManager.cs

When a string like "sdsa" is entered as a mnemonic, a NotSupportedException is thrown from NBitcoin with "Unknown" as the message.
This PR changes the message to "Please make sure you enter valid mnemonic words.", making it less confusing to users.

Rephrase exception thrown when non-valid mnemonic is entered

---

Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs
Stratis.Bitcoin.Features.Wallet.Tests/WalletTestsHelpers.cs
Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
Stratis.Bitcoin.Features.Wallet/WalletManager.cs
Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs

Commits of particular interest:  
4f99028 - Refactoring done to make testing a lot easier to do on this class. Otherwise the walletmanager cast would have made it very difficult. Let me know what you think of it. Doing the same refactor to lightsyncwalletmanager makes it easy to test that as well after this walletmanager refactor from this pull request.
b2a5593 - Ran into and fixed an issue in proceessblock. Already shortly notified dan of the bug that was in it. It has to do with being able to recover using the blockstorecache after the discovery was made earlier that we are not on the best chain anymore.

Unit tests for WalletSyncManager

---

Stratis.Bitcoin.Cli/Program.cs
Stratis.Bitcoin.Cli/Properties/launchSettings.json
Stratis.Bitcoin.IntegrationTests/RPCTEsts.cs

This PR includes:
- Test cases to ensure we can call RPC by passing string arguments
- An update to the CLI to call RPC by passing string arguments. Results are displayed to the console.

Make CLI work for RPC calls

---

Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs

https://github.com/nopara73/ZeroLink/#transaction-output-indexing
|Basic Post-Mix Wallet Requirement|Post-Mix Wallet Uniformity Requirement|
|---------------------------------|--------------------------------------|
||Post-mix wallet SHOULD index its built transaction outputs randomly.|
A post-mix wallet, due to its design, will only have one input and a maximum of two outputs at all times. Uniform indexing of outputs is necessary in order for multiple post-mix wallet implementations to look the same. A post-mix wallet SHOULD use random indexing of outputs.
Random indexing is not exclusively beneficial for post-mix wallet uniformity, conversely it has another privacy benefit. When a wallet software always generates the change output on the second index, observers always know which output …

Implement transaction input and output shuffling for increased privacy

---

Stratis.Bitcoin.IntegrationTests/APITests.cs
Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj

Adds the following "FACT" methods:
- CanGetGeneralInfoViaAPI - Performs a GET to "api/wallet/general-info" passing arguments in the URI.
- CanStartStakingViaAPI - Performs a POST to "api/miner/startstaking" passing arguments in the request body.

Add integration tests to ensure that the API can be called. 

---

Stratis.Bitcoin/Connection/ConnectionManager.cs

This PR relates ConnectionManager's NodeGroups to avoid duplicate connections

Relate the ConnectionManager's NodeGroups to avoid duplicate connections

---

Stratis.Bitcoin.Features.Consensus/ConsensusStats.cs

GetBlock can return null. The output is not super pretty if that happens, but it is very rare for this to happen, so it should be OK.
Fix #590

trivial fix to prevent ConsensusStats crash

---

Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs
Stratis.Bitcoin.Features.RPC/RPCFeature.cs
Stratis.Bitcoin.IntegrationTests/APITests.cs

This PR includes the following:
- Adds a "callbyname" API call to a new RPC controller
- Adds a test case to test "callbyname".

 Add "callbyname" API call on RPC controller

---

Documentation/getting-started.md

Corrected missing step for building node, changing `dotnet build` to `dotnet restore` (Restores the dependencies and tools of a project.). dotnet build is redundant as it is already incorporated into `dotnet run`, however it does not display logging, but dotnet run will report any build issues anyway.

Corrected Node Building Instructions

---

Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletTransactionHandler.cs
Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs

This endpoint is so breeze can do a fee estimate without requiring the user to enter a password. Still need to add unit tests for this.

Add new endpoint in api for estimating transaction fee

---

Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
Stratis.Bitcoin.Features.MemoryPool/MempoolErrors.cs
Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs

This is basically a C# port of this bitcoin logic sections in the mempool validator: https://github.com/bitcoin/bitcoin/blob/ea729d55b4dbd17a53ced474a8457d4759cfb5a5/src/validation.cpp#L584-#L587
https://github.com/bitcoin/bitcoin/blob/aa624b61c928295c27ffbb4d27be582f5aa31b56/src/policy/policy.cpp#L196
As well as some clean up of some async naming issues with some of the mempool tests.

Add witness transaction validation to mempool validator

---

Stratis.Bitcoin/Configuration/NodeSettings.cs
Stratis.Bitcoin/Connection/ConnectionManager.cs
Stratis.BreezeD/Program.cs

I am considering we should change the default agent from `StratisBitcoin` to be `StratisNode`.  
Alternatively we can also enforce a certain structure in the agent name to `stratis:[node-description]:version`.
Then for the fullnode it will be `stratis:fullnode:1.0.2` and for breeze it will be `stratis:breeze:1.0.2`
We could also put macros to for example for the version, Breeze has its own version this will allow to override version.

Adding the Breeze agent to the node version

---

Stratis.Bitcoin.Tests/NodeConfiguration/TextFileConfigurationTests.cs
Stratis.Bitcoin/Configuration/TextFileConfiguration.cs

After the PR we will be able to pass e.g. Azure keys as command line arguments. 
These mime-encoded-data strings end in one or more "=" - e.g.:
`azurekey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==`

Allow "=" in config values 

---

Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs
Stratis.Bitcoin.Features.LightWallet/Stratis.Bitcoin.Features.LightWallet.csproj
Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
Stratis.Bitcoin.Features.Wallet.Tests/WalletTestsHelpers.cs
Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
Stratis.Bitcoin.Features.Wallet/WalletManager.cs

If the chain is still downloading when the user creates a wallet, we now wait until it is downloaded in order to set the lastSyncedBlockHeight. Otherwise, the height of the wallet will be the height of the chain at that moment.

 Fix create or restore during chain headers download bug.

---

src/Stratis.Bitcoin.Features.Consensus/Checkpoints.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

Add a node setting to control use of checkpoints. 

---

src/Stratis.Bitcoin.Cli/Program.cs
src/Stratis.BitcoinD/Program.cs
src/Stratis.BreezeD/Program.cs

Following asynchronous functions naming convention moved async code from Main functions to newly created MainAsync

Moved asynchronous code to functions with Async suffix

---

src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusSettings.cs

Also fixed an issue where if checkpoints are turned off and assumevalid is on, the assumevalid check was being turned off on a fresh IBD because the headers were not yet downloaded. Reverted that code back to what bitcoin core is doing - if can't find assumevalid block it will just proceed to validate it.

Add assumevalid hash for other networks

---

src/Stratis.Bitcoin.Cli/Program.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs

Two miner integration tests were failing because consensus uses check points which causes the block validation to be skipped. This causes the test to fail as it expects a exception to be thrown.

Fix Build & Fix 2 miner tests with checkpoint logic

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs

As stated by @bokobza, argument injection should be preferred over file configuration but currently if we specifiy to use for example, RegTest in the file we will over write the boolean straight after if its NOT in the arguments.
This causes the integration tests to run on the bitcoin network.

[Tests] Fix node setting overriding file configuration

---

src/NBitcoin/BitcoinCore/BlockRepository.cs
src/NBitcoin/BlockValidator.cs
src/NBitcoin/IBlockRepository.cs
src/NBitcoin/NoSqlBlockRepository.cs
src/NBitcoin/RPC/RPCClient.cs
src/NBitcoin/RPC/RestClient.cs
src/NBitcoin/Utils.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepBaseTest.cs
src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
src/Stratis.Bitcoin.Features.Miner/PowMining.cs
src/Stratis.Bitcoin.IntegrationTests/NodeBuilder.cs

before there were two different interfaces called IBlockRepository
this PR renames the one in NBitcoin and cleans the usage of our IBlockRepository in FN files

rename IBlockRepository in NBitcoin to avoid conflicts

---

src/NBitcoin.Tests/NodeBuilderStratis.cs

ever since we moved NBitcoin to FN codebase, we received extra 3 compiler warnings, this PR fixes those
Start and StartAsync were removed from node builder in nbitcoin tests
it was never used and it used uninitialized variables anyway ...

fixed compiler warnings by removing some stuff from nbitcoin

---

src/NBitcoin.Tests/BIP38Tests.cs
src/NBitcoin.Tests/Benchmark.cs
src/NBitcoin.Tests/BitcoinAddressTest.cs
src/NBitcoin.Tests/ColoredCoinsTests.cs
src/NBitcoin.Tests/JsonConverterTests.cs
src/NBitcoin.Tests/NBitcoin.Tests.csproj
src/NBitcoin.Tests/NetworkTests.cs
src/NBitcoin.Tests/PaymentTests.cs
src/NBitcoin.Tests/RepositoryTests.cs
src/NBitcoin.Tests/RestClientTests.cs
src/NBitcoin.Tests/StealthAddressTests.cs
src/NBitcoin.Tests/addrman_tests.cs
src/NBitcoin.Tests/alert_tests.cs
src/NBitcoin.Tests/base58_tests.cs
src/NBitcoin.Tests/bip32_tests.cs
src/NBitcoin.Tests/bip39_tests.cs
src/NBitcoin.Tests/checkblock_tests.cs
src/NBitcoin.Tests/cmpctblock_tests.cs
src/NBitcoin.Tests/hash_tests.cs
src/NBitcoin.Tests/key_tests.cs
src/NBitcoin.Tests/pos_ProtocolTests.cs
src/NBitcoin.Tests/pos_RPCClientTests.cs
src/NBitcoin.Tests/pos_RepositoryTests.cs
src/NBitcoin.Tests/pos_addrman_tests.cs
src/NBitcoin.Tests/pos_hash_tests.cs
src/NBitcoin.Tests/pos_pow_tests.cs
src/NBitcoin.Tests/pos_transaction_tests.cs
src/NBitcoin.Tests/pow_tests.cs
src/NBitcoin.Tests/sighash_tests.cs

This  PR:
- Stabilizes the remaining NBitcoin tests that depend on the static flags Transaction.TimeStamp and Block.BlockSignature
- Makes tests execute sequentially by changing xunit.runner.json from "do not copy" to "copy if newer".
- Fixed tests.
- Disabled broken tests. Marked these tests with TODO.

Make NBitcoin tests green

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs

This is to get rid of the amount of unnecessary logging in the Travis build while running tests.
Like so:

Changed some logs from Info to Debug

---

src/NBitcoin.Tests/pow_tests.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

The call to NodeSettings.Default() in the WalletMangager constructor parameters switches the static flags, Transaction.TimeStamp and Block.BlockSignature on, inadvertently.
This PR fixes the recent code added to NodeSettings to resolve the Api port for Stratis by comparing to the Stratis network objects - the  root cause of the problem.
A second issue is addressed, and that is the use of static test methods. The constructor code intended to stabilize the static flags will not be executed for static methods.

Fix NodeSettings side-effects on static flags in WalletManagerTest

---

src/NBitcoin/Script.cs
src/NBitcoin/Transaction.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs

Tiny pr that replaces 
```
var unused;
fu(out unused)
```
with 
`fu (out var unused)`

Unused 'out' optimizations

---

src/NBitcoin/BitcoinStream.cs
src/NBitcoin/IBitcoinSerializable.cs
src/NBitcoin/InMemoryNoSqlRepository.cs
src/NBitcoin/NetworkOptions.cs
src/NBitcoin/NoSqlBlockRepository.cs
src/NBitcoin/NoSqlRepository.cs
src/NBitcoin/NoSqlTransactionRepository.cs
src/Stratis.Bitcoin/Utilities/DBreezeSerializer.cs

This PR:
1. Allows BitcoinSerializable entities to deal properly with the NetworkOptions member variable during serialization/deserialization. 
2. Injects the NetworkOptions into any new BitcoinStream created during serialization. This makes the NetworkOptions available to any child object being reconstructed from the stream.
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/676

Serialize/Deserialize NetworkOptions

---

src/Stratis.Bitcoin.IntegrationTests/APITests.cs
src/Stratis.Bitcoin.IntegrationTests/Program.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs

I've created separate fixtures for the api and rpc integration tests. This will speed them up tremendously from 1-2 seconds per test to 10-300miliseconds per test. 
I've also merged two of the integration tests because one was just an additional action after the other. Integration tests are expensive and this saves another 4 seconds locally for me.

Api and RPC integration Test fixtures

---

src/Stratis.Bitcoin.IntegrationTests/ConstructorsForSerializableClassesTest.cs
src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj

This test is added in order to prevent scenarios when devs (like me) would delete a parameterless constructor that is never referenced in the codebase thinking that it's useless and then break the node by that.

Added a test in order to ensure that every serializable object has a parameterless constructor

---

src/Stratis.Bitcoin.Tests/Utilities/StopwatchTest.cs

It seems that the testing environment is quite unreliable. We thus try to
- increase the epsilon to accept slightly worse results than before
- wait a bit before the test starts in case some post processing is still going on (like GC or whatever) from previous tests

Attempt to fix stopwatch test

---

src/NBitcoin.Tests/ChainTests.cs
src/NBitcoin/ChainBase.cs
src/NBitcoin/ChainedBlock.cs
src/Stratis.Bitcoin.Features.Consensus/Extensions.cs
src/Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs

This PR 
* Replaces linear searches on chain headers with GetAncestor which uses skip list to search for block heights which will improve performance
* Move FindFork method that was only used by tests into tests
Issue #659

For chain searches use skip list method instead of linear searches

---

src/Stratis.Bitcoin.IntegrationTests/P2P/PeerConnectionTests.cs
src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs

in one method two different networks were used, i think this was bug, 
so instead i'm suggesting that we decide on the network in test class constructor and then we can't be inconsistent

initialize network once and then use it consistently

---

src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs

As discussed we have discovered that the peer discovery async loop is currently spamming the network as it doesn't have functionality to check whether or not the peer is connected.

[PeerDiscovery] Adjust asyncloop repeat interval and parallel threads

---

src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletSyncManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Broadcasting/BroadcasterManagerBase.cs
src/Stratis.Bitcoin.Features.Wallet/Broadcasting/FullNodeBroadcasterManager.cs
src/Stratis.Bitcoin.Features.Wallet/Broadcasting/LightWalletBroadcasterManager.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs
src/Stratis.Bitcoin/Interfaces/IBroadcasterManager.cs
src/Stratis.Bitcoin/Stratis.Bitcoin.csproj

Changes: 
1) Added requirement of having at least 1 connection in order to send a tx.
2) Removed waiting for propagation before returning result of SendTransaction.
3) Now it's possible to check propagation state of the transaction by looking it up in the wallet and using IsPropagated flag. 
4) Changed SendTransactionAsync to SendTransaction because now this method do not use any awaitable methods. 
Those changes were discussed in [issue 597](https://github.com/stratisproject/StratisBitcoinFullNode/issues/597) so for more info about the logic behind this changes take a look at the discussion. 
Fix: #579

Added IsPropagated flag to wallet transaction data and changed how SendTransaction works. 

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs

There was a bug who's repro steps are the following:
In a normal situation:
1. user starts off with new installation (no folder, no blocks, and **no chain**)
2. user starts the node
3. user creates a wallet, before the chain is downloaded
4. wallet is created but LastBlockSyncHeight and LastBlockSyncHash are not yet populated (as per design, we don't know anything about the chain yet)
5. when chain is downloaded, LastBlockSyncHeight and LastBlockSyncHash are updated
If between 4. and 5., the node is stopped, the wallet won't have LastBlockSyncHeight and LastBlockSyncHash on restart, leading to an exception.
The fix presented here waits for the chain to be downloaded in the background before updating the LastBlockSyncHeight and LastBlockSyncHash in the wallets.

Excepton thrown if no LastBlockSyncHeight

---

src/NBitcoin/Networks.cs

I've updated the hashes to match current chain:
* Mainnet (bitcoin/stratis) picked a block back from the tip that had at least 10 confirmations
* Testnet (bitcoin/stratis) picked a block about 10,000 back from tip
I'm not sure if its necessary to go back so far on strat testnet as I'm not sure the strat testnet is quite as crazy as bitcoins but the bitcoin recommendation is to go back 10,000 blocks because of potential for big reorgs on testnet.
I think these should be safe values however. Using these values my IBD times were as follows:
TSTRAT - 10 mins
STRAT - 35 mins

Update assumevalid hashes for faster IBD

---

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Models/WalletHistoryModel.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.StratisD/Properties/launchSettings.json

In order to be able to show a staking transaction in the History, we look for transactions that are marked as coin stake transaction + that have 1 input from our wallet to 2 outputs to our wallet.
This is better reviewed commit by commit.
Any question, please ask.

Staking in History

---

src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs

PeerConnected was previously called when the peer disconnected, not it is called when the peer is connected

fix calling PeerConnected

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs
src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
src/Stratis.Bitcoin/Base/BaseFeature.cs

It was just a bit annoying to see the wrong padding.

Improved console text alignment for the node stats

---

src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
src/Stratis.Bitcoin.FullNode.sln
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/global.json

Should fix #933 
It appears that global.json was introduced in order to fix a compatibility issue with VS2015 side by side with VS2017 in a pre-release version of core (see https://github.com/stratisproject/StratisBitcoinFullNode/commit/9debb6cd11e4720643f683127ad5d08d28c5b0b8). I no longer think this is an issue. I have both VS2015 and VS2017 installed side by side and I do not require a global.json file in order to build. The removal of the global.json file should allow the project to build on newer tooling sets.
I also cleaned up a couple of compiler warnings I noticed that were present with this build.

Remove global.json and fix compiler warnings

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedUdpClient.cs
src/Stratis.Bitcoin.Features.Dns/IDnsServer.cs
src/Stratis.Bitcoin.Features.Dns/IFullNodeBuilderExtensions.cs
src/Stratis.Bitcoin.Features.Dns/IMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/IUdpClient.cs
src/Stratis.Bitcoin/Configuration/DataFolder.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.StratisDnsD/Properties/launchSettings.json

- For trello backlog item: https://trello.com/c/DrlOCEm9
- Uses 3rd party library from https://github.com/kapetan/dns (nuget package)
- Given some deficiencies in the library, the DnsServer class has been rewritten to allow a custom master file and to support dig DNS requests (which it failed with during integration testing).
-  Updates DnsFeature to start the DNS server and restart it if it fails, also responds to the cancellation token ApplicationStopping in the INodeLifetime object.
- Updates to NodeSettings to support dnslistenport and dnsfullnode options
- Updates to DataFolders to support a location for the cached DNS masterfile
- Added DnsSeedServer class (and interfaces) that implements DNS request resolver using 3rd party library
- Added DnsSeedUdpClient class (and interfaces) to …

Base DNS server implementation

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsMetric.cs
src/Stratis.Bitcoin.Features.Dns/DnsMetricSnapshot.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/IDnsServer.cs

- For Trello item: https://trello.com/c/rX5dYdQL
- Added new tests for metric output and updated existing tests
- Changed main DNS loop in feature to not load masterfile on restart of DNS server
- Added DNS metric types for totals and snapshot values
- Updated DNS server to capture metric values in main receive request loop and output metrics periodically using an async loop
- Fixed full stops at end of comments as per previous PR

[DNS] Added metrics for output to console

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedMasterFile.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
src/Stratis.Bitcoin.Features.Dns.Tests/Stratis.Bitcoin.Features.Dns.Tests.csproj
src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/IDnsServer.cs
src/Stratis.Bitcoin.Features.Dns/IFullNodeBuilderExtensions.cs
src/Stratis.Bitcoin.Features.Dns/IMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/IWhitelistManager.cs
src/Stratis.Bitcoin.Features.Dns/ResourceRecordConverter.cs
src/Stratis.Bitcoin.Features.Dns/Stratis.Bitcoin.Features.Dns.csproj
src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.StratisDnsD/Properties/launchSettings.json

Contains two tasks, one to link the Peer Address Manager to the DNS Server and another to implement the load and save of the master file from disk.
- New class WhiteListManager, to allow the DNS feature to populate the resource records in the DNS 
Server using the Peer Address Manager.
- Implemented a custom JSON Converter to handle the serializing and deserializing of the 
IResourceRecords as these are from the nuget package and do not have parameterless constructors or setters for all of the properties.
- Bought in the functionality from the MasterFile in the DNS nuget package into the customised DnsSeedMasterFile.
- Added the DNS peer blacklist threshold and DNS hostname to the node settings.
- Added relevant unit tests

DNS Server integrated populated with WhiteLists

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.StratisDnsD/Program.cs
src/Stratis.StratisDnsD/Properties/launchSettings.json
src/Stratis.StratisDnsD/Stratis.StratisDnsD.csproj

- For Trello item: https://trello.com/c/oMisVGrT
- Added support for SOA and NS records, adds in new command line arguments for dnsnameserver and dnsmailbox.
- Fixed and added new unit tests.
- Fixed metric output for peer counts.
- Added ANY support for DNS queries (3rd party library didn't offer this).
- Added fullnode support.
- Added new launch setting for fullnode.
- Tested both DNS only and fullnode settings.

[DNS] Added SOA and NS support, other fixes

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs
src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs

Also improved our view of peer's chain tip and set startAfter to 1 sec instead of 10 for the staking loop since such long waiting time is no longer required because we have inner waiting for the right conditions to start staking. 
Fix: #921

Added IsSynced to our peer's view and preventing mining until we have at least one synced connection. 

---

src/Stratis.Bitcoin.Features.Dns/DnsSeedMasterFile.cs

- Fixes the DNS query that asks for a NS record without specifying a domain when dig is run in trace mode

[DNS] Small fix for dig trace (recursion) support (not ANY)

---

src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs

This fix allows specifying rpc port without enabling '-server=true'.
This is needed in order to start multiple nodes on the same machine without the need to enable -server.

Rpc port setting fix

---

src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs

It can happen that the pending inventory vector queue contains a single item twice, in which case the code crashes. So this just adds check.
Fix #988

Fix crash in BlockPuller 

---

src/Stratis.Bitcoin.Features.Consensus/InitialBlockDownloadState.cs
src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/InitialBlockDownloadStateMock.cs
src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/MockedInitialBlockDownloadState.cs
src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeRunners.cs
src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
src/Stratis.Bitcoin/Interfaces/IInitialBlockDownloadState.cs

This PR removes test-only method 'SetIsInitialBlockDownload' from the non-test codebase. 
Test implementation of 'IInitialBlockDownloadState' is added for the test environment by replacing the default service with a mock at the node build stage.

IBD provider: moved test only method from interface to test-only environment mock up

---

src/Stratis.Bitcoin/P2P/PeerConnector.cs
src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs
src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs

Also improved some logging and peer disconnection reason (it was treated as timeout no matter what cancellation token was used- application stopping or linked one that is cancelled after 5 sec)
Fix: #1031

Fix: slow node shutdown if many -connect or -addNode options were specified

---

src/NBitcoin.Tests/RPCClientTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinImmutableTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcTestFixtureBase.cs

There are several nbitcoin RPC client tests that are currently failing due to the peer refactoring. This PR moves those tests into integration test project so they can now use the new peer.
See #868 
Status of integration/nbitcoin tests for this PR can be seen here https://ci.appveyor.com/project/mikedennis/stratisci/branch/mikedennis
This PR also generalizes the RPCTestFixture class so it can be used for both Bitcoin and Stratis networks. The Bitcoin RPC tests are divided between tests that can can make use of the testfixture and others that require their own setup for each individual test.

Move failing NBitcoin RPC client tests into integration tests

---

src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs
src/Stratis.Bitcoin/Connection/DropNodesBehaviour.cs
src/Stratis.Bitcoin/P2P/PeerConnector.cs
src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs
src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs
src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs

Renamed MaximumNodeConnections  to MaxOutboundConnections since prev name was misleading and made people assume that this value is limiting overall connections count.  
Made MaxOutboundConnections configurable.
Fix: #931

MaximumNodeConnections : rename and config

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs

This PR removes code related to the Connection Manager from NodeSettings and adds it to the ConnectionManagerSettings class.
A `Load` method is created to contain the code within the ConnectionManagerSettings class.

Move ConnectionManager-specific code to ConnectionManagerSettings

---

src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs
src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
src/Stratis.Bitcoin/P2P/PeerConnector.cs

This change removes 1 second delay between connection attempts until we are connected to at least 1 peer- after that set it back to normal.

Getting the first node connection speedup.

---

src/Stratis.Bitcoin.Features.Miner/Models/GetStakingInfoModel.cs
src/Stratis.Bitcoin.Features.RPC.Tests/Controller/GetInfoActionTests.cs
src/Stratis.Bitcoin.Features.RPC.Tests/Models/GetInfoModelTest.cs
src/Stratis.Bitcoin.Features.RPC.Tests/Models/GetStakingInfoTest.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.Features.RPC/Models/GetInfoModel.cs
src/Stratis.Bitcoin.Features.RPC/Models/GetTxOutModel.cs
src/Stratis.Bitcoin.Features.RPC/Models/TransactionModel.cs

Changed json fields returned by `getstakinginfo` api method to be pascal case.
Changed the properties for `GetInfoModel`, `GetTxOutModel `and `TransactionModel `to follow our code style for properties and used Json.NET property name attribute to specify serialization formatting.

json fields formatting

---

src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs

PR #886 introduced a critical bug in consensus loop. This PR attempts to fix that. Hopefully it succeeds in that.
So, what is the problem?
`AcceptBlockAsync` contained this code:
```
await this.consensusRules.ExecuteAsync(blockValidationContext);
try
{
await this.ValidateAndExecuteBlockAsync(blockValidationContext.RuleContext, true).ConfigureAwait(false);
}
catch (ConsensusErrorException ex)
{
blockValidationContext.Error = ex.ConsensusError;
}
```
the first line of that leads to `BlockHeaderRule.RunAsync`, which may throw:
```
if (context.BlockValidationContext.Block.Header.HashPrevBlock != context.ConsensusTip.HashBlock)
{
this.Logger.LogTrace("Reorganization detected.");
ConsensusErrors.InvalidPrevTip.Throw();
}
```
if this is thrown, then the rest of that rule is not executed, …

bug fix - crash in validator

---

src/Stratis.Bitcoin.Api.Tests/ApiSettingsTest.cs
src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj
src/Stratis.Bitcoin.Api.Tests/xunit.runner.json
src/Stratis.Bitcoin.Features.Api/ApiSettings.cs
src/Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.Features.BlockStore.csproj
src/Stratis.Bitcoin.Features.Consensus/Stratis.Bitcoin.Features.Consensus.csproj
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
src/Stratis.Bitcoin.Features.Dns/Stratis.Bitcoin.Features.Dns.csproj
src/Stratis.Bitcoin.Features.MemoryPool/Stratis.Bitcoin.Features.MemoryPool.csproj
src/Stratis.Bitcoin.Features.Miner/Stratis.Bitcoin.Features.Miner.csproj
src/Stratis.Bitcoin.Features.Notifications/Stratis.Bitcoin.Features.Notifications.csproj
src/Stratis.Bitcoin.Features.RPC/Stratis.Bitcoin.Features.RPC.csproj
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Stratis.Bitcoin.Features.Wallet.csproj
src/Stratis.Bitcoin.Features.WatchOnlyWallet/Stratis.Bitcoin.Features.WatchOnlyWallet.csproj
src/Stratis.Bitcoin.IntegrationTests/APITests.cs
src/Stratis.Bitcoin.IntegrationTests/P2P/PeerConnectionTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinImmutableTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcTestFixtureBase.cs
src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs
src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs
src/Stratis.Bitcoin.Tests/TestBase.cs
src/Stratis.Bitcoin/Base/ChainRepository.cs
src/Stratis.Bitcoin/Configuration/DataFolder.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.Bitcoin/Stratis.Bitcoin.csproj
src/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs

This PR contains a few commits allowing multiple nodes to run on the same machine:
* Make sure the node terminates:
If an exception is thrown (for example the DBreeze fails to initialize), the ManualResetEventSlim is never set and the node stays waiting for it. So if for example a second node is started on a machine, it will fail whilst creating the DBreeze db but the process will keep running. This fix allows the process to terminate.
* Checking for null before disposing of Dbreeze
* Allow setting of custom data directory.
Previously, trying to start a node with a directory different than the default one would throw an exception. Now we create a directory after the one specified in the datadir argument.
* Split of ApiUri
Splitting the apiUri between ApiUri and ApiPort so that it's easier …

Running multiple nodes on the same host

---

src/Stratis.Bitcoin.Features.Api/ApiFeature.cs
src/Stratis.Bitcoin.Features.Api/Program.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.Features.RPC/Startup.cs
src/Stratis.Bitcoin/Interfaces/IGetUnspentTransaction.cs
src/Stratis.Bitcoin/Interfaces/IPooledGetUnspentTransaction.cs

As @dangershony said: the whole design behind .NodeService is wrong: we are supposed to inject services, not ask for them.
So in this PR .NodeService<T> usages for non-test methods are removed.

Removed .NodeService<T> usages from non-test methods

---

src/NBitcoin/Network.cs
src/NBitcoin/NetworkBuilder.cs
src/NBitcoin/Networks.cs
src/Stratis.Bitcoin.Api.Tests/ApiSettingsTest.cs
src/Stratis.Bitcoin.Cli/Program.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ConsensusSettingsTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/InitialBlockDownloadTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletFixedFeePolicyTest.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeRunners.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.BreezeD/Program.cs
src/Stratis.StratisD/Program.cs
src/Stratis.StratisDnsD/Program.cs

Removed the parameter name as well as the property as it is not really used apart for setting the root folder where the different blockchain files are stored. Furthermore, it lead to confusion and errors as the wrong name was sometimes used for another network.

 Remove the "name" parameter in NodeSettings

---

src/Stratis.Bitcoin.Api.Tests/ApiSettingsTest.cs
src/Stratis.Bitcoin.Features.Api/ApiSettings.cs

Added ports 38220 and 38221 to be the API ports for bitcoin testnet and stratis testnet respectively.
This allows mainnet and a testnet nodes to be run at the same time on a single machine.

Added testnet API ports.

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeBuilder.cs

Disable mining until the moment we're not in IBD and our block repository is  at the same height with the peer that has highest PendingTip.Height of all peers that we're connected to.
Fix: #896

Bugfix: Prevent mining if node is not fully synced

---

src/Stratis.Bitcoin/Connection/ConnectionManager.cs

Use this VersionPayload's StartHeight for the console info, so that we reduce the display of "unknown" on the console.
Fix: #995

Use VersionPayload's start height for displaying peer's height when PendingTip is null.

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.IntegrationTests/P2P/PeerConnectionTests.cs
src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs
src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerTests.cs
src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs
src/Stratis.Bitcoin/P2P/PeerAddress.cs
src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs
src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs
src/Stratis.Bitcoin/P2P/PeerSelector.cs

This fixes #1105.
Also, in the scenario where there are no connections, we will employ the burst connection mode BUT if there are no peers to be selected from, the peer connector will continuously try and find peers without any delay. Therefore we need to delay the connection for a bit before trying again. This was the scenario where the logs were being flooded with entries.

[P2P] Reset connection attempts and throttle connection when there are no peers

---

src/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/WatchOnlyWalletManagerTest.cs
src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs
src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs

The watch-only wallet currently only seems to properly watch incoming transactions. This extends the functionality to detecting transactions being spent from the watched addresses as well.

Allow WO wallet to track incoming and outgoing tx

---

src/Stratis.Bitcoin.Features.Notifications/TransactionReceiver.cs

Bug reported by @zeptin:
> fail: Stratis.Bitcoin.P2P.Peer.NetworkPeerConnection[0]
>       [70-[::ffff:46.101.181.118]:18333] Error while detaching behavior 'Stratis.Bitcoin.Features.Notifications.TransactionReceiver': System.ArgumentException: Callback already registered.
>          at Stratis.Bitcoin.Utilities.AsyncExecutionEvent`2.Register(AsyncExecutionEventCallback`2 callbackAsync, Boolean addFirst) in C:\Users\carlt\source\BreezeHub\BreezeProject\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncExecutionEvent.cs:line 91
>          at Stratis.Bitcoin.Features.Notifications.TransactionReceiver.DetachCore() in C:\Users\carlt\source\BreezeHub\BreezeProject\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Notifications\TransactionReceiver.cs:line 43
>          at …

[Bug] TransactionReceiver doesn't properly unregister OnMessageReceivedAsync

---

src/Stratis.Bitcoin.Tests/Utilities/ParallelAsyncTest.cs
src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs
src/Stratis.Bitcoin/Utilities/ParallelAsync.cs

PeerDiscoveryLoop used to use Parallel.ForEach in order to perform the peer discovery. And since awaitable methods were used in the foreach iterations the whole Parallel.ForEach was not awaited (apparently Parallel.ForEach cannot be used with awaits inside the iteration code).
That caused running peer discovery for the same set of peers every 10 seconds without awaiting prev set to be processed => we get a peer discovery connection + connection drop every 10 seconds. 
In order to fix this I've introduced a `ParallelAsync.ForEachAsync` that works exactly the same as `Parallel.ForEach` except for it can work with async code properly. 
Fix: #1124

Peer discovery fix

---

src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderExtensionsTest.cs
src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs
src/Stratis.Bitcoin/Builder/FullNodeBuilder.cs
src/Stratis.Bitcoin/Builder/FullNodeBuilderNodeSettingsExtension.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

This PR removes unnecessary public methods and variables from `NodeSettings`.
Having the public / member `TestNet` and `RegTest` variables can allow contradictions to arise between the values of the variables and the current `this.Network` variable.

Remove public TestNet, RegTest and GetNetwork from NodeSettings (Refactor)

---

src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/ProcessPendingStorageStep.cs

`ProcessPendingStorageStep.ProcessWhenInIBDAsync` will return `StepResult.Continue` if `PendingStorage` has less than 10 blocks in it. Every time `StepResult.Continue` is returned we are starting a new iteration in `BlockStoreLoop.DownloadAndStoreBlocksAsync` which will again bump into that threshold and restart until the moment 10 blocks are finally downloaded. And so it goes over and over again => the slower the peers are the longer it takes to download enough blocks to pass the threshold => more iterations we have. 
On average I have 300000 iterations of the `DownloadAndStoreBlocksAsync:while` loop before I have 30 blocks downloaded given that I'm connected to the slow peers. 
Returning `StepResult.Stop` instead of  `StepResult.Continue` when the threshold is not met makes the loop …

Block store high cpu usage fix

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs

Fixed issue with embedded IPv4 addresses (inside IPv6 address) that should be added as 'A' records to DNS master file, not 'AAAA'.
Fixed tests.

Fixed embedded IPv4 addresses not responding to DNS 'A' requests

---

src/Stratis.Bitcoin.Features.Api/ApiFeature.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ConsensusSettingsTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/InitialBlockDownloadTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/MerkeRootComputationTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusSettings.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsSettings.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs
src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs
src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeatureCollectionTest.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeatureRegistrationTest.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeaturesDependencyCheckingTest.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeaturesExtensionsTest.cs
src/Stratis.Bitcoin.Tests/Builder/FullNodeServiceProviderTest.cs
src/Stratis.Bitcoin/Builder/Feature/FullNodeFeature.cs
src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs
src/Stratis.StratisDnsD/Program.cs

This PR adds a `LoadConfiguration` method to features.
This change promotes a more structured approach to starting up features:
```
/// <inheritdoc />
public void Initialize()
{
try
{
this.Execute(service => service.ValidateDependencies(this.node.Services));
this.Execute(service => service.LoadConfiguration()); // <================
this.Execute(service => service.Initialize());
}
catch (Exception ex)
{
this.logger.LogError("An error occurred starting the application: {0}", ex);
throw;
}
}
```
The alternative to this is to load configurations from the above `Initialize` method. However, since some `Initialize` methods may be looking at configurations from other features, it is better to load all configurations before calling the features' `Initialize` methods.

Add a LoadConfiguration method to features

---

src/NBitcoin/Network.cs
src/NBitcoin/NetworkBuilder.cs
src/NBitcoin/Networks.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

This is for https://github.com/stratisproject/StratisBitcoinFullNode/issues/605
Should we change the default max tip age value for Stratis?
If yes, to what?
I think 2 hours is ok (~120 blocks).
@dangershony @Aprogiena

Move Max tip age to Network

---

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs
src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs

Error on a lower level was handled using LogError while handling was also implemented on a higher level with LogTrace. 
Removed low level handling with LogError. 
Fix: #1141

Appropriate level of exceptions handling in NetworkPeerServer

---

src/Stratis.Bitcoin.Tests/Utilities/AsyncLoopTest.cs
src/Stratis.Bitcoin.Tests/Utilities/ParallelAsyncTest.cs

Removed StopWatch usages from the ParallelAsync tests & changed timings for AsyncLoopRepeatEveryIntervalCanBeChangedWhileRunningAsync & fixed race condition.

Tests consistency on Travis

---

src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
src/Stratis.Bitcoin.Features.Consensus/Interfaces/IPowConsensusValidator.cs
src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs
src/Stratis.Bitcoin.Features.Consensus/PowConsensusValidator.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinbaseHeighRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/HeightInCoinbaseRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockContextRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/TransactionLocktimeActivationRule.cs
src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs

Some rules have already been implemented this code will remove them from the validator class.

 Removing the ContextualCheckBlock method from the validator

---

src/Stratis.Bitcoin.Features.Consensus.Tests/TimeSyncBehaviorTest.cs
src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/MinerControllerTest.cs
src/Stratis.Bitcoin.Features.Miner.Tests/MiningRPCControllerTest.cs
src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs
src/Stratis.Bitcoin/Base/TimeSyncBehavior.cs

* Better warning messages when system time out of sync
* Added method to explicitly states that system time is out of sync
* Prevent staking if system time is out of sync.
Show errors in API, RPC staking calls as well as when starting the node with -stake=true
For https://github.com/stratisproject/StratisBitcoinFullNode/issues/1097

Time sync warnings

---

src/NBitcoin.Tests/ColoredCoinsTests.cs
src/NBitcoin.Tests/pos_RPCClientTests.cs
src/NBitcoin.Tests/util_tests.cs
src/NBitcoin/BitcoinPubKeyAddress.cs
src/NBitcoin/BitcoinSegwitAddress.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs

Fixed 4 NBitcoin test out of 7.
The 3 that are still failing are:
CanGetBlockHeader
CanGetUTXOsMempool
CanGetTransaction
in the class `RestClientTests`.
Not really sure what to do with them as the code they rely on has been moved to NetworkPeer and is no longer working.
So I'm creating this PR in the meantime.
Maybe @Aprogiena or @fassadlr can give us some insight as to the best way forward.

Nbitcoin tests

---

src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusSettings.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

This PR adds a PrintHelp method to the Consensus feature to display command-line help for the Consensus feature when required.

Add PrintHelp method to Consensus feature

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs

This PR adds the PrintHelp method to the BlockStore feature to display command-line help for the BlockStore feature when required.

Add PrintHelp method to BlockStore feature

---

src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsSettings.cs
src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs
src/Stratis.StratisDnsD/Program.cs

This PR adds a PrintHelp method to the Dns feature to print command-line help for the Dns feature when required.

Add PrintHelp method to Dns feature

---

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerFactory.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs

This is first PR in series of PRs that will lead to fixing https://github.com/stratisproject/StratisBitcoinFullNode/issues/1090
In this part NetworkPeerCollection was removed from the NetworkPeerServer

Network Peer Server refactoring

---

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs

Hi, it's my first commit to this repo, let me know if something wrong. This problem occurs when I'm tried to create a private PoW/PoS chain with different parameters.
Not sure if this is correct, but `PosMinting` calculate the reward for current blockchain height (let's say `N`), but when it validates reward in `PosConesnsusValidator` -> `CheckBlockReward` method - its uses newly created block height (`N+1`). As far as Stratis has a constant reward for PoS - 1 coin, it will work properly, but in case if reward depends on the block - it probably won't work

Fix for wrong height reward calculation

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs

Removing the hex of the transaction saved in the wallet file as it's only used by TB at the moment and it takes a lot of space.
Improvement for https://github.com/stratisproject/StratisBitcoinFullNode/issues/598

 Added wallet settings with option to save the transaction hex

---

src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests/WalletTests.cs

* Send one transaction from sender to receiver, with 50 transaction outputs.

New Integration test - WalletCanSendOneTransactionWithManyOutputs

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs

- Improved performance of when and how the lookup dictionary for addresses is loaded
- Added look-up on unspent outputs
- Changed from saving the wallet after every change to saving the wallet when
1. a transaction is received from the network
2. a block is done being processed and had some transactions affecting the wallet within it
- no benchmarking was done but the gain in speed is noticeable.
Kudos to @noescape00 for creating blocks with crazy transactions.
For reference, take a look at these blocks on Stratis Testnet:
333235
333445
333449
333946
334042
334044
334046
334048
334051
334052
334055
334056
334081
334084
334088
334094
334100
@dangershony

Wallet performance improvements numero uno

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs

* MAde the GetUnusedAddresses support change addresses
* now using the new GetUnusedAddresses to protect the wallet from threading issues
* Fixed grammar
* Add error message for invalid Money amount
* Added optimization improvement based on Dan's comment

Merge to master - Wallet Thread and error message fixes (#1264)

---

src/Stratis.Bitcoin/P2P/Protocol/Payloads/PayloadAttribute.cs

This pr adds a check for the `commandName` of the payload. 
I believe this is needed because if a new payload is created (let's say by someone who builds on top of the node and implements a new protocol message) and it's command name doesn't meet the limitations set by the protocol the communication with this payload won't be possible, however no error will be spawned while trying to use a payload with long command name and the node will run normally.

Payload command length check

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTestsHelpers.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs

There was a bug whereby transactions sent to an address would not get confirmed.
The outgoing transaction would get registered in the wallet file, but not updated once it was confirmed in a block.
The explanation is as follows: 
The wallet manager maintains in memory a dictionary of unspent transactions, which makes checking whether incoming transactions affects the wallet or not, much easier and much faster.
The problem was that this list was marking an spent transactions as spent, even before it was confirmed. So when the transaction would show up in a block as confirmed, the manager would not even process it, and the "unconfirmed" status of the transaction would never move to "confirmed".
The resolution is that this dictionary is now keeping a list of all the transactions, unspent or …

Fixed unconfirmed trx bug

---

src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/BackendPerformanceCounterTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CachePerformanceCounterTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinViewStackTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinViewTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/FetchCoinsResponseTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ConsensusSettingsTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/AssumeValidRuleTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderPowContextualRuleTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderRuleTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleDescriptorTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Stratis.Bitcoin.Features.Consensus.Tests.csproj
src/Stratis.Bitcoin.Features.Consensus/CoinViews/BackendPerformanceCounter.cs
src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachePerformanceCounter.cs
src/Stratis.Bitcoin.Features.Consensus/CoinViews/CoinViewStack.cs
src/Stratis.Bitcoin.Features.Consensus/CoinViews/FetchCoinsResponse.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusSettings.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRules.cs
src/Stratis.Bitcoin.Features.MemoryPool/MemPoolCoinView.cs
src/Stratis.Bitcoin/Base/Deployments/NodeDeployments.cs
src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs

I've started to create tests for the consensus project. 
This commit contains tests for some general classes of the coinviews folder, consensus rule executers and a start to unit tests for the consensus rules. The plan is to add tests like dan added for consensusrules later after the unit tests are in place.

Consensus project tests part 1

---

src/NBitcoin/ConcurrentChain.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
src/Stratis.Bitcoin.Tests/Base/BestChainSelectorTest.cs
src/Stratis.Bitcoin/Base/BaseFeature.cs
src/Stratis.Bitcoin/Base/BestChainSelector.cs
src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
src/Stratis.Bitcoin/FullNode.cs

This PR is the first one for #229
It introduces a new component `BestChainSelector` that handles situations when a peer disconnects and selects the best chain tip from the available ones in case disconnected peer was the only one who backed our current best chain. 
ps
Reviewed already by @Aprogiena

Switch from the chain if it's no longer represented by any peer that we're connected to

---

src/Stratis.Bitcoin.Features.Miner/PosMinting.cs

A null exception was possible during the mining. It would stop the mining loop. 
Bug log:
```
[2018-04-11 19:56:48.0332 9] ERROR: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext PosMining.Stake threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Stratis.Bitcoin.Features.Miner.PosMinting.<GenerateBlocksAsync>d__44.MoveNext() in C:\Users\user\Desktop\FNExploits\src\Stratis.Bitcoin.Features.Miner\PosMinting.cs:line 523
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at …
```

PoS Minting null exception

---

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/FullNodeBuilderTest.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs
src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderExtensionsTest.cs
src/Stratis.Bitcoin/Builder/FullNodeBuilder.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

This PR:
- makes the member variables "DataDir" and "ConfigurationFile" on the "NodeSettings" class read-only.
- updates the tests to pass these values via the constructor.
- refactors NodeSettings and moves the RPC-specific code to the RPC feature.

Refactor / Make read-only the DataDir and ConfigurationFile

---

src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs

Missing assembly reference where LogsTestBase couldn't not be found.
Also used Mock<CoinView> instead of using the local TestCoinView class.

Missing assembly reference where LogsTestBase couldn't not be found.

---

src/Stratis.Bitcoin.Features.Miner/PowBlockAssembler.cs

This PR fixes the following error:
`Message: System.ArgumentOutOfRangeException : The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset`
The error occurs in the following test cases:
- CreateCoinbase_CreatesCoinbaseTemplateTransaction_AddsToBlockTemplate
- CreateNewBlock_WithScript_DoesNotValidateTemplateUsingRuleContext
- CreateNewBlock_WithScript_ReturnsBlockTemplate
- CreateNewBlock_WithScript_ValidatesTemplateUsingRuleContext

Fix failing CreateCoinBase and CreateNewBlock test cases

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs

After #1290 several unit tests failed related to the block assemblers. This PR fixes them.

Update miner unit tests broken by #1290 and fix integration tests

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepBaseTest.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/StoreSettingsTest.cs

This PR fixes the following test cases which are currently failing intermittently:
BlockStoreLoopIntegration
=========================
CheckNextChainedBlockExists_WithNextChainedBlock_Exists_SetStoreTipAndBlockHash
DownloadBlockStep_WithNewBlocksToDownload_DownloadBlocksAndPushToRepo
ProcessPendingStorage_PushToRepo_BeforeDownloadingNewBlocks
ReorganiseBlockRepository_WithBlockRepositoryAndChainOutofSync_ReorganiseBlocks
BlockStoreLoopStepReorganiseTest
================================
ReorganiseBlockRepository_WithBlockRepositoryAndChainOutofSync_ReorganiseBlocks_InMemory
BlockStoreLoopStepCheckNextChainedBlockExistStepTest
====================================================
CheckNextChainedBlockExists_WithNextChainedBlock_Exists_SetStoreTipAndBlockHash_InMemory …

Fix BlockStore test cases

---

src/NBitcoin.Tests/NetworkBuilderTest.cs
src/NBitcoin/CheckpointInfo.cs
src/NBitcoin/Network.cs
src/NBitcoin/NetworkBuilder.cs
src/NBitcoin/Networks.cs
src/Stratis.Bitcoin.Features.Consensus/Checkpoints.cs

This PR moves the checkpoints to the network file and adds methods to include them in the nodebuilder.
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/1341
@dangershony please have a look. I'm still unsure where to move CheckpointInfo to.

Move checkpoints to network (#1341)

---

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Tests/Utilities/FileStorageTest.cs
src/Stratis.Bitcoin/Utilities/FileStorage.cs

This should fix https://github.com/stratisproject/StratisBitcoinFullNode/issues/1230 and hopefully https://github.com/stratisproject/StratisBitcoinFullNode/issues/1231.
I added a call to `File.Replace` when saving the file so that the file never gets in a corrupted state.
This call is atomic in the sense that the file is either replaced successfully or not replaced at all.
Additionally, I added a parameter to the `FileStorage.SaveFile` method where a backup file (.bak) will be saved every time the file is saved. So the backup will have the previous version, and the file will have the new version.
More here: https://msdn.microsoft.com/en-us/library/windows/desktop/hh802690%28v=vs.85%29.aspx

Protect file from corruption while saving

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.StratisD/Program.cs

This PR updates StratisD to respect the configuration files' network selection ('regtest' or 'testnet').

Update StratisD to respect the configuration file network selection

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs

This PR adds the GetBlocksAsync method to the BlockRepository and BlockRepositoryInMemory classes.
The method opens the possibility of further optimization by allowing multiple blocks to be returned in a single call and by leveraging sorted access within the underlying DBreeze database.
The new method has relevance to https://github.com/stratisproject/StratisBitcoinFullNode/issues/1103.

Add GetBlocksAsync method to IBlockRepository

---

src/Stratis.Bitcoin/P2P/Protocol/Payloads/PayloadAttribute.cs

Example usage from the FederatedGateway:
```
// add our payload
var payloadProvider = this.fullNode.Services.ServiceProvider.GetService(typeof(PayloadProvider)) as PayloadProvider;
payloadProvider.AddPayload(typeof(RequestPartialTransactionPayload));
```

Added AddPayload method to PayloadProvider

---

src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs
src/Stratis.Bitcoin.Tests/NodeConfiguration/NodeSettingsTest.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
src/Stratis.Bitcoin/Utilities/Extensions/IPExtensions.cs

This PR:
- Moves the `ConvertIpAddressToEndpoint` method from `NodeSettings.cs` to `IPExtensions.cs` and renames the string extension method to `ToIPEndPoint`.

Move "ConvertIpAddressToEndpoint" to IPExtensions.cs

---

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeRunners.cs

This is needed for testing node features that are outside the SBFN codebase.

Add back removed support for custom node builders in integration tests

---

src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs
src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
src/Stratis.Bitcoin/P2P/PeerSelector.cs

This is a bugfix for a bug reported by @maciejzaleski 
The problem is that at some point all the peers in peers.json have maxed out connectionAttempts count and the selector always returns nothing. 
This can happen when node was working without access to the internet for some time or if node was running for a very long time. 
I've added a quick fix that will reset attempts count in case there are no peers to try and all peers from the list that are not banned have their connection attempts count maxed out. 
After resetting the node will recover if any of the peers are still alive.

Node stops attempting to connect

---

src/NBitcoin.Tests/script_tests.cs

Check if the tests are running on Windows before executing them.
This will fix the NBitcoin tests relying on libbitcoinconsensus-0.dll.

exclude libbitcoinconsensus-0.dll tests when not on windows

---

src/NBitcoin.Tests/NetworkTests.cs
src/NBitcoin/Consensus.cs
src/NBitcoin/Networks/BitcoinMain.cs
src/NBitcoin/Networks/StratisMain.cs
src/NBitcoin/Networks/StratisRegTest.cs
src/NBitcoin/Networks/StratisTest.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinviewRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PowCoinviewRule.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
src/Stratis.Bitcoin.IntegrationTests.Common/SharedSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs

Moved 
* CoinbaseMaturity
* PremineReward
* PremineHeight
* ProofOfWorkReward
from ConsensusOptions to Consensus.
This way these properties are more accessible. We need this if we want to create new networks with custom mining settings. For example POW network with 50M coins, no reward.
I have no idea why this test is failing: https://github.com/stratisproject/StratisBitcoinFullNode/compare/master...bokobza:consensus-options-move?expand=1#diff-b3695281628304a7bdb952a6e293ceb8R179
If someone has any idea, I'll happily take it.
All the other unit tests run ok, the integration ones are broken.

Moved a few properties from ConsensOptions implementations to Consensus

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs

Minor blockstorequeue optimization which allows us to avoid serialization of every block in order to get block size.

Utilize BlockSize property in the block store queue

---

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs

this is to make life easier in sidechain integration tests, where up to 8 nodes will be started to simulate a federation + sidechain users

possibility to name the folder in which node data is stored

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

Create 2 chains Chain A and Chain B, where Chain A has more chain work than B. Connect both chains to chain header tree. Consensus tip should be set to chain A. Now extend / update Chain B to make it have more chain work. Attempt to connect B again. Consensus tip should be set to chain B.
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/1321#issuecomment-389155904

Added new test to cover issue #13. Presenting chains with different chain work

---

src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
src/Stratis.Bitcoin.Features.Miner/PosBlockDefinition.cs
src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs

In SmartContracts we add transactions to the block differently than how we do pow/pos blocks. We first need to check whether or not the transaction to be added contains SC information and if it does, we execute it to validate and calculate fees etc.
Currently we have to make the `AddToBlock` method in `BlockDefinition` virtual so that we can override its behavior. This needs to be changed to an abstract method so that each block definition implements its own logic to add a transaction to a block.
The logic in the current `AddToBlock` has been split into 3 methods:
1> Add tx to block.
2> Update block stats.
3> Update block fee.

[RF][SmartContracts] Abstract the AddToBlock method

---

src/NBitcoin/UInt256.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/MemoryPoolTransactionTests.cs
src/Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs
src/Stratis.Bitcoin.Features.MemoryPool/TxMemPoolEntry.cs
src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
src/Stratis.Bitcoin.Features.Miner/Comparers/CompareModifiedEntry.cs
src/Stratis.Bitcoin.Features.Miner/Comparers/CompareTxIterByAncestorCount.cs
src/Stratis.Bitcoin.Features.Miner/TxMemPoolModifiedEntry.cs

This PR:
- Removes the duplicated fee comparison in TxMempoolEntry and TxMemPoolModifiedEntry
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/1441.

Remove duplicated fee comparison in TxMempoolEntry and TxMemPoolModifiedEntry

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

Issue 14 @ Chain exists with checkpoints enabled. There are 2 checkpoints. Peer presents a chain that covers first checkpoint with a prolongation that does not match the 2nd checkpoint. Exception should be thrown.
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/1321#issuecomment-389155904.

Chain header tree test to cover issue 14

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

Issue 15 @ Checkpoint are disabled. Assume valid is enabled. Headers that pass assume valid and meet it is presented. Chain is marked for download. Alternative chain that is of the same lenght is presented but it doesnt meet the assume valid- also marked as to download.
See https://github.com/stratisproject/StratisBitcoinFullNode/issues/1321#issuecomment-389155904

1762 chainheadertree issue 15

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

Issue 16 @ Checkpoints are enabled. After the last checkpoint, there is an assumed valid. The chain that covers them all is presented - marked for download. After that chain that covers the last checkpoint but doesn't cover assume valid and is longer is presented - marked for download.

CHT Test: Two chains one covering checkpoint and assume valid and another only checkpoint

---

src/NBitcoin.Tests/ChainTests.cs
src/NBitcoin.Tests/ConstructorsForSerializableClassesTest.cs
src/NBitcoin.Tests/pos_transaction_tests.cs
src/NBitcoin.Tests/transaction_tests.cs
src/NBitcoin/BitcoinStream.cs
src/NBitcoin/Block.cs
src/NBitcoin/BlockHeader.cs
src/NBitcoin/ConsensusFactory.cs
src/NBitcoin/IBitcoinSerializable.cs
src/NBitcoin/NoSqlRepository.cs
src/NBitcoin/Transaction.cs
src/NBitcoin/TransactionBuilder.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/InitialBlockDownloadTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/FeeTests.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.Tests/Base/BestChainSelectorTest.cs

This PR was to remove the `SetNull()` method in `BlockHeader` as we override this in smart contracts. A better implementation would be to set all these values in the constructor.
As part of this PR I had to fix a lot of tests as we now correctly create the block header via the consensus factory everywhere.
All unit and integration tests pass. Busy syncing....

Remove SetNull() from BlockHeader and make the constructor internal

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/HdOperations.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs

Swapped the parameter order to the Create HDAddress path as it had an optional parameter that was never used optionally. Therefore optional changed to explicit.
should be tagged very-low

Optional parameter never used optionally

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

Issue 21 @ FindHeaderAndVerifyBlockIntegrity called for some bogus block. Should throw because not connected.

CHT test: Calling FindHeaderAndVerifyBlockIntegrity on a bogus block

---

src/Stratis.Bitcoin/Controllers/DashboardController.cs
src/Stratis.Bitcoin/Controllers/LogsController.cs

Rather than move into smart contracts, I made it generic so it will work with any log file (just use the name  in the url).
I added hyperlinks to make this easier and changed the root to have 2 links, one to stats and one to logs

Generic logs controller to view logs in browser on full node

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

Block data received (BlockDataDownloaded is called) for already FV block with null pointer. Nothing should be chained, pointer shouldn't be assigned. Should return false

CHT test: BlockDataDownload for null pointer - issue 23

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs

**Issues 7 & 10** (#1321)
(7)  _We have a chain, someone presents an invalid header. After that our chain's last block shouldn't change and it shouldn't have .Next and it throws_
(10) _When checkpoints are enabled and the only checkpoint is at block X, when we present headers before that- none marked for download. When we first present checkpointed header and some after- all previous are also marked for download & those that are up to the last checkpoint are marked as assumevalid_

CHT tests issues #7, #10

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs
src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs

Checkpoints are disabled. Chain tip is at header 5. Reorganisation is initiaised with max reorg of 500 blocks plus extra 50 blocks. We start syncing until block 490. Peer 2 presents the alternative chain with 2 headers after fork point at header 5. We then you join the rest of 60 blocks. ConsensusTipChanged should return identifier of the second peer at block number 505.

CHT test: Reorg with 550 blocks and presentation of another chain - issue 27

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs

Mega low impact,  calls an existing method that does the same as the lines of code did.

Called GetWalletManagerWithCustomParam which does the same job

---

Docker/Stratis.StratisD/Dockerfile

No longer builds with 2.0:
`The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.`

Update Dockerfile with 2.1 sdk

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

CHT is initialized with BlockStore disabled. CT advances and old block data pointers are removed. Make sure that data availability 
for those headers set to header only.
CHT is initialized with BlockStore enabled. CT advances and old block data pointers are removed. Make sure that data availability for those headers is DataAvailable. 

CHT test: Enabling and disabling block store and checking data availability - issue 49 50

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs

**Cht tests fazzdev #1321 45**
- Node has a reorg of 5 blocks.
- Make sure that headers for the blocks that were reorged away.
- Have no block pointers and block data availability == headers only.
Preferred: @Aprogiena @noescape00

Cht tests fazzdev #1321 45

---

src/Stratis.BitcoinD/Program.cs
src/Stratis.BreezeD/Program.cs
src/Stratis.StratisD/Program.cs
src/Stratis.StratisDnsD/Program.cs

FWIW: https://blogs.msdn.microsoft.com/benwilli/2017/12/08/async-main-is-available-but-hidden/
Also, [one of these files](https://github.com/stratisproject/StratisBitcoinFullNode/compare/master...DragonSpark:master#diff-6e4cc3136f86c0b1782c738d49faadfd) had trailing whitespace which can be seen/mitigated with the following extension:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespaceVisualizer
Thank you for any consideration and/or feedback. 👍

Converting entry points to asynchronous methods.

---

src/Stratis.Bitcoin/P2P/Peer/NetworkPeerCollection.cs

Hopefully this is exactly the same except that we now check that PeerVersion is not null and has an address
I was getting exceptions when it was

Matching peers : PeerVersion can be null

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs

so if the peers are in the list but disconnected this return the wrong answer

peers in the list are not necessarily connected

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs

Fixes #1215.
There is likely potential to reuse code from `OnInsertBlocks` and `OnInsertTransactions`, however for now I believe it makes more sense to have a completely separate method as the logic is slightly different and I don't believe we need to involve the PerformanceCounter in any way.

-reindex command now functions as expected.

---

src/NBitcoin/Networks/BitcoinRegTest.cs
src/NBitcoin/Networks/BitcoinTest.cs
src/NBitcoin/Networks/StratisRegTest.cs
src/NBitcoin/Networks/StratisTest.cs

Moves the assignment of all Consensus settings into inherited networks BitcoinTest, BitcoinRegTest, StratisTest, and StratisRegTest.
Reasoning:
* All settings are assigned in one place. Much easier to reason about than having to dive into multiple layers of inheritance
* These fields will not change, so it's no problem to have duplication
* Allows us to make `Consensus` immutable in the future
Testing:
✅ NBitcoin Network tests pass
✅ Sync and validate StratisTest (100k blocks)
✅ Sync and validate BitcoinTest (100k blocks)

Assign all Consensus settings directly in inherited networks

---

src/NBitcoin/BitcoinCore/Coins.cs
src/NBitcoin/Consensus.cs
src/NBitcoin/ConsensusFactory.cs
src/NBitcoin/Networks/StratisMain.cs
src/NBitcoin/Networks/StratisRegTest.cs
src/NBitcoin/Networks/StratisTest.cs
src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
src/Stratis.Bitcoin/P2P/Protocol/Payloads/HeadersPayload.cs

`Consensus.ConsensusFactory` was only being used to check if the network is POS. 
This PR:
* Replaces the check for `IsProofOfStake` by looking at the type of `ConsensusFactory`
* Removes the `Consensus` property from `ConsensusFactory`

Remove Consensus from ConsensusFactory

---

src/Stratis.Bitcoin.Features.BlockStore/Models/BlockModel.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
src/Stratis.Bitcoin/Controllers/Models/BlockHeaderModel.cs
src/Stratis.Bitcoin/Controllers/Models/GetTxOutModel.cs

Per discussion with @majikandy on discord after PR #1635, 2 items were suggested to change with a minor PR:
* Method names had a redundant "_via_api" naming scheme
* Deserialize rather than use JObject
All respective tests are passing.

API Integration Test method naming redunancy fix

---

src/NBitcoin/BitcoinAddress.cs
src/NBitcoin/BitcoinPubKeyAddress.cs
src/NBitcoin/BitcoinSegwitAddress.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin/Controllers/NodeController.cs

The BitcoinAddress types all unnecessarily pass Network by reference. This is dangerous, as it means they can change the Network object pointed to by `reference`.
✅All tests pass except SmartContracts integration tests (failing in master), AddNewAccount_for_xpub_only_wallet_informs_user_to_create_new_wallet_ (failing in master), and CreateExtPubKeyOnlyWallet_creates_wallet_with_extra_flag (failing in master)

Remove pass-by-reference of Network in BitcoinAddress types

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs

Adds a single specification for smart contract executor handling contract creation. Part of an overall goal to have contract execution behaviour well-specified in tests.
Writing this required a lot of setup, which makes me feel like the executor is still doing too much. @majikandy would appreciate your input on this.

[SC] Executor contract creation specification

---

src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

Closes #1336.
Adds a method to set up the NLog configuration using the NLog.config in the DataDir. This occurs after we establish the path to the DataDir, but before the programmatic configuration takes place. 
The order of logger config precedence is: 
DataDir NLog.config > Regular [NLog.config path resolution](https://github.com/nlog/NLog/wiki/Configuration-file#configuration-file-locations) > Default empty NLogConfiguration. 
Programmatic rules are always loaded.
There's an existing chicken-and-egg problem where a Logger is initialized and used to log within `NodeSettings` before it has been configured, but can't be configured until after settings are read. Some calls made to logger before configuration do not actually go anywhere. We can move some existing logging to occur after …

Load NLog.config from the DataFolder

---

src/NBitcoin/ChainedHeader.cs
src/NBitcoin/Consensus.cs

This PR moves the calculation of `DifficultyAdjustmentInterval` closer to its usage. `DifficultyAdjustmentInterval` is only used in one method of `ChainedHeader`.
Moving this also makes it possible for us to use `IConsensus` in place of `Consensus`. I will do this as part of a later PR.

Move DifficultyAdjustmentInterval calculation

---

src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs
src/Stratis.Bitcoin/P2P/PeerAddress.cs
src/Stratis.Bitcoin/P2P/PeerSelector.cs

- Handshake counter does not get reset to zero until a successful handshake occurs.
- Handshake counter should get reset after threshold time expires.
Preferred: @fassadlr

After peer attempt time threshold expires reset counters (#1816)

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs

Fixes #1550 
Closes #1669 
The call for recovering a wallet would always trigger a sync, but recovering a wallet ahead of the current sync run would make the sync jump forward.
This was fixed by only triggering a sync if the current sync run needs to go back a number of blocks.
@maciejzaleski Can you please retest?
@zeptin

Wallet Recovery Fix

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs

Looks like two unused variables were introduced that load NodeSettings defaults.
Fix #1847

Fixes #1847 NodeSettings is initalized 3 times

---

src/Stratis.SmartContracts/ICreateResult.cs
src/Stratis.SmartContracts/ITransferResult.cs

Trivial change - everything still builds and tests pass. 
Important so that smart contract developers can't access StackTrace inside their contracts (and save it to state hence determinism issue)

[SC] Remove ThrownException from ITransferResult and ICreateResult

---

src/Stratis.Bitcoin/Consensus/BlockDownloadRequest.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
src/Stratis.Bitcoin/Consensus/IConsensusManager.cs
src/Stratis.Bitcoin/Consensus/ValidationResults/ConnectBlocksResult.cs
src/Stratis.Bitcoin/Consensus/ValidationResults/PartialValidationResult.cs
src/Stratis.Bitcoin/Consensus/ValidationResults/ValidationResult.cs
src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs

split of the file
use Action<ChainedHeaderBlock> instead of OnBlockDownloaded callback (I asked in the room and everybody was finding that more readable)

little reorg of the consensus manager file

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs

TestHelper.Wait loop is now accepting 3 additional arguments to control exceptions, sampling interval and cancellation token

Improvements toTestHelper.Wait loop, increased wait time on Segwit test

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs

Related to #1801.
This is required so any client code using `BlockStoreCache.GetBlockAsync()`, can move over to `BlockStoreQueue.GetBlockAsync()`.

Implement GetBlockAsync.

---

Documentation/contributing.md

Proposal to favour rebasing vs. merging from parent branch when PRs become stale.
Reasons:
* Keeps unrelated changes out of PRs, making them easier to review
* History is cleaner/easier to reason about
Guideline taken from [corefx](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md). Bitcoin also do a [similar thing](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md).

Add guidelines around rebasing PRs with conflicts

---

src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowApiRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisPosApiRunner.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs
src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs

`NodeGroupBuilder` builds a group of nodes to presumably be used together, so it makes sense to use the same network for all the nodes it builds.

Use same Network in NodeGroupBuilder when creating nodes

---

src/Stratis.Bitcoin.Features.SmartContracts.Wallet/SmartContractWalletTransactionHandler.cs
src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletTransactionHandler.cs
src/Stratis.Bitcoin.Features.Wallet/Recipient.cs
src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
src/Stratis.Bitcoin.IntegrationTests.Common/SharedSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletOnPosNetworkTests.cs
src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs

This PR was geared up to be something a bit different, in line with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1773 but in the end we opted for a less disruptive change.
* `Transaction Transaction` and `bool Sign` were removed from the TransactionBuilderContext object because the user shouldn't set them.
* The object originally passed to TransactionBuilderContext's ctor are now initialized via properties. This has the advantage to allow more flexibility as to where the inputs are taken from, and it also shows to the user that all the properties are settable and effectively on the same level.
Closes https://github.com/stratisproject/StratisBitcoinFullNode/pull/1773
Related to https://github.com/stratisproject/StratisBitcoinFullNode/issues/1689
@codingupastorm if you need …

Clean up TransactionBuilderContext to be easier for a user to use.

---

src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
src/Stratis.Bitcoin/Utilities/HashHeightPair.cs

Apparently tests don't use ==. Assert.Equal uses default.Equal
So This one fixes around 5 tests

[Aprogina] fixed some more tests

---

src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs

This is to fix this integration test as it was failing to complete due to the folder path being too long.

Shortened name of AddNodeWithValidNodeThenExecutesSuccessfully 

---

src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs

Related to https://github.com/stratisproject/StratisBitcoinFullNode/issues/1936
Fixed ChainedHeaderTreeTest tests.
From about 55 failures to 0.
@noescape00 @fassadlr

Fix ChainedHeaderTreeTest tests

---

src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj
src/Stratis.Bitcoin.Features.Apps.Tests/Stratis.Bitcoin.Features.Apps.Tests.csproj
src/Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.Bitcoin.Features.BlockStore.Tests.csproj
src/Stratis.Bitcoin.Features.Consensus.Tests/Stratis.Bitcoin.Features.Consensus.Tests.csproj
src/Stratis.Bitcoin.Features.Dns.Tests/Stratis.Bitcoin.Features.Dns.Tests.csproj
src/Stratis.Bitcoin.Features.LightWallet.Tests/Stratis.Bitcoin.Features.LightWallet.Tests.csproj
src/Stratis.Bitcoin.Features.MemoryPool.Tests/Stratis.Bitcoin.Features.MemoryPool.Tests.csproj
src/Stratis.Bitcoin.Features.Miner.Tests/Stratis.Bitcoin.Features.Miner.Tests.csproj
src/Stratis.Bitcoin.Features.Notifications.Tests/Stratis.Bitcoin.Features.Notifications.Tests.csproj
src/Stratis.Bitcoin.Features.RPC.Tests/Stratis.Bitcoin.Features.RPC.Tests.csproj
src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
src/Stratis.Bitcoin.Features.Wallet.Tests/Stratis.Bitcoin.Features.Wallet.Tests.csproj
src/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests.csproj
src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
src/Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj

Added explicit package ref to xunit.runner.visualstudio because jetbrains rider ide doesn't detect tests even though this package is inherited from the test.common project.
This solves the issue and allows all tests to be detected by the IDE now.

vs xunit runner needs explicit ref for jetbrains rider

---

src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs

Need to call FullNode.Start() to make sure ConnectionManager.Initialize() is called, then logic to set up ISelfEndpointTracker.MyExternalAddress is invoked.

ISelfEndpointTracker.MyExternalAddress was null when running CanCall_AddNode()

---

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/RulesRegistrationOrderTest.cs

**Test rules registration order for validation and execution rules #1435**
Added two tests for POW, POS to guarantee current consensus rules and their ordering remain unchanged.

[Activation] Test rules registration order for validation and execution rules #1435

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
src/Stratis.SmartContracts.Core/ISmartContractTransactionContext.cs
src/Stratis.SmartContracts.Core/SmartContractTransactionContext.cs
src/Stratis.SmartContracts.Executor.Reflection/Executor.cs

Removes some unused fields on TransactionContext. Changes the Type of the contract transaction data to be bytes rather than having to pull them from the Script.

[SC] Remove unused fields on TransactionContext

---

src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosBlockSignatureRuleTest.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractPosBlockSignatureRule.cs

Verify the exact number of opcodes and the maximum size of the data following an OP_RETURN in the (optional) special second output of coin stake transactions.

Validate Block Based On Public Key Extracted From CoinStake Output

---

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BitcoinActivationRule.cs
src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
src/Stratis.Bitcoin/BlockPulling/BlockPullerBehavior.cs

Fixed 
Stalling_DoesntAffectPeersThatFailedToDeliverNotImportantBlocksAsync
Stalling_PeerStallsButQualityScoreIsTheBestBecausePeerIsTheOnlyOneAsync
ProcessHeadersAsync_PeerThatSentInvalidHeaderIsBannedAsync

[Activation] Fixed some tests

---

src/NBitcoin.Tests/NBitcoin.Tests.csproj
src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj
src/Stratis.Bitcoin.Features.Apps.Tests/Stratis.Bitcoin.Features.Apps.Tests.csproj
src/Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.Bitcoin.Features.BlockStore.Tests.csproj
src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Stratis.Bitcoin.Features.Consensus.Tests.csproj
src/Stratis.Bitcoin.Features.Dns.Tests/Stratis.Bitcoin.Features.Dns.Tests.csproj
src/Stratis.Bitcoin.Features.LightWallet.Tests/Stratis.Bitcoin.Features.LightWallet.Tests.csproj
src/Stratis.Bitcoin.Features.MemoryPool.Tests/Stratis.Bitcoin.Features.MemoryPool.Tests.csproj
src/Stratis.Bitcoin.Features.Miner.Tests/Stratis.Bitcoin.Features.Miner.Tests.csproj
src/Stratis.Bitcoin.Features.Notifications.Tests/Stratis.Bitcoin.Features.Notifications.Tests.csproj
src/Stratis.Bitcoin.Features.RPC.Tests/Stratis.Bitcoin.Features.RPC.Tests.csproj
src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
src/Stratis.Bitcoin.Features.Wallet.Tests/Stratis.Bitcoin.Features.Wallet.Tests.csproj
src/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests.csproj
src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
src/Stratis.Bitcoin.Tests.Common/Stratis.Bitcoin.Tests.Common.csproj
src/Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
src/Stratis.Bitcoin/Base/ChainRepository.cs
src/Stratis.BitcoinD/Stratis.BitcoinD.csproj
src/Stratis.SmartContracts.Core.Validation.Tests/Stratis.SmartContracts.Core.Validation.Tests.csproj
src/Stratis.SmartContracts.Core/Receipts/PersistentReceiptRepository.cs
src/Stratis.StratisD/Stratis.StratisD.csproj

- updated xunit to latest verison (lots of improvements in the latest version)
- removed references to NLog in StratisD and BitcoinD
- added creation of folder before calling `new DBreezeEngine(folder)`.  With this, all the `Creation of the database folder failed!` occasionally appearing in the tests are gone.

Tests improvements 1

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CalculateStakeRuleTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CalculateWorkRuleTest.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockMerkleRootRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckDifficultyPowRule.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckDifficultykHybridRule.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
src/Stratis.Bitcoin/Consensus/Rules/RuleContext.cs

This PR removes .BlockMined property from the context and fixes mempool tests + mocking that fails CHT tests + improves stability of BS tests

[Activation] Remove block mined from context

---

src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusQuery.cs

**Fix failing test CallWithDependencies on activation #1936**
_Fix provides INetworkDifficulty from ConsensusQuery following deprecation of ConsensusLoop._
Preferred: @fassadlr @dangershony

Fix failing test CallWithDependencies on activation #1936

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractResultRefundProcessorTests.cs
src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
src/Stratis.SmartContracts.Executor.Reflection/ISmartContractResultRefundProcessor.cs
src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionResult.cs
src/Stratis.SmartContracts.Executor.Reflection/SmartContractResultRefundProcessor.cs
src/Stratis.SmartContracts.Executor.Reflection/State.cs
src/Stratis.SmartContracts.Executor.Reflection/StateTransitionResult.cs
src/Stratis.SmartContracts.Executor.Reflection/TransferResult.cs

Closes #2121.
* Adds success and error result types which are returned on `StateTransitionResult`.
* Returns an error type for all expected state transition errors.
* Returns any exceptions generated within the VM execution.
* Pushes the handling of internally generated transaction errors back to the ITE.
For review only. Do not merge until we establish what's going on with core-way-activation.

[SC] State transition error improvements

---

src/NBitcoin/BouncyCastle/math/BigInteger.cs
src/Stratis.Bitcoin.Cli/Program.cs
src/Stratis.Bitcoin.Features.Apps/AppsFeature.cs
src/Stratis.Bitcoin.Features.Apps/AppsStore.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/PowConsensusRuleEngine.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolPersistence.cs
src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
src/Stratis.Bitcoin/Base/BaseFeature.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs
src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
src/Stratis.Bitcoin/FullNode.cs
src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs
src/Stratis.Bitcoin/Utilities/AsyncLoop.cs
src/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs
src/Stratis.Bitcoin/Utilities/PeriodicTask.cs

Fixed bug in `IsConsensusConsideredToBeSyncedLocked` - it was considering our own tip and would return `true` in case we are not connected to anyone or connected to peers who are less synced than we are. 
Minor initialization logging fixes
Added logging for headers to periodic log as we had them before activation:

Periodic log, small CHT and CM edits

---

src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs

This will at least log out unexpected errors, but the greater question is what to do when that happens, we could for example inject the lifetime token and just shutdown the node for such errors.

handle unexpected error in rules engine

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.StratisSmartContractsD/Program.cs

If a network is passed into the `NodeSettings` to be used by the node, it also needs to be registered in our list of networks so that we can create a wallet, as the `Network.Parse` method relies on `GetCandidates` using registered networks. Insanely gross, we should fix that eventually, but for now at least we can patch it here.
It's otherwise misleading for anyone else consuming our API trying to run a new network.

Register Network if passed in to NodeSettings

---

src/NBitcoin/Consensus.cs
src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

Slimmed down version #2216.
@noescape00 after this change I get this null reference in the block puller when calculating speed? Without that where clause one of the peers has speed of -173382348 something like that. Maybe you can shed some light on this?

Fix partial validation sequence when a fork occurs

---

src/Stratis.Bitcoin/BlockPulling/BlockPullerBehavior.cs

[Fix] BlockPullerBehavior SpeedBytesPerSecond can be negative sometimes

---

src/NBitcoin/ProvenBlockHeader.cs
src/Stratis.Bitcoin/P2P/Protocol/Payloads/GetHeadersPayload.cs
src/Stratis.Bitcoin/P2P/Protocol/Payloads/GetProvenHeadersPayload.cs
src/Stratis.Bitcoin/P2P/Protocol/Payloads/HeadersPayload.cs
src/Stratis.Bitcoin/P2P/Protocol/Payloads/ProvenHeadersPayload.cs
src/Stratis.Bitcoin/P2P/Protocol/Payloads/SendProvenHeadersPayload.cs

New set of payloads to be used for `ProvenBlockHeaders` as per #1787 
Payloads are based on equivalent `BlockHeader` payloads

[PH] - New payloads for Proven headers

---

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

Log provided by Kevin:
```
crit: Stratis.Bitcoin.FullNode[0]
PeriodicLog threw an unhandled exception
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
at System.String.Substring(Int32 startIndex, Int32 length)
at Stratis.Bitcoin.Consensus.ConsensusManager.formatBigNumber(Int64 number) in C:\Users\Kevin\Downloads\Projects\DotNET\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 1308
at Stratis.Bitcoin.Consensus.ConsensusManager.AddComponentStats(StringBuilder log) in C:\Users\Kevin\Downloads\Projects\DotNET\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 1290
at Stratis.Bitcoin.Utilities.NodeStats.GetStats() in C:\Users\Kevin\Downloads\Projects\DotNET\StratisBitcoinFullNode\src\Stratis.Bitco …
```

PeriodicLog bugfix

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs

If the node are at genesis the nodes should be considered to be synced.

[Integration Tests] Fix TestHelper's IsNodeSynced methods

---

src/NBitcoin.Tests/ChainTests.cs

commented the tested scenarios and added a missing one (scenario 4)
previously the test was simplier, were comparing 2 small chains (around 5 blocks long) and missed a test case.
I changed this in order to have a longer chain to test and commented the 5 tested scenarios (4th is new)
```
//test scenario 1:
//chain2 is empty, so the fork point is supposed to be the Genesis
//chain1) G a b c d e
//chain2) G
//test scenario 2:
//chain2 is a chain on another network (main vs test), null expected
//chain1) G a b c d e
//chain2) Gtest
//test scenario 3:
//chain2 is a subset of chain2 and stops at the fork point "c", fork point expected
//chain1) G a b c d e
//chain2) G a b c
//test scenario 4:
//chain2 is a forked chain (at the fork point "c") that has other blocks on top of it, fork point …
```

improved the CanFindFork test

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/FormatValidationTests.cs
src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs
src/Stratis.SmartContracts.Core.Validation/FormatPolicy.cs
src/Stratis.SmartContracts.Core.Validation/Validators/Instruction/NewObjValidator.cs

Closes #1921. Prevents all usages of `newobj` except when it is being used to create value types.

[SC] Blacklist new object creation

---

src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs

The ban time is reduced to 10 minutes to facilitate testing of misbehaving nodes - without having to wait 24 hours if the node gets banned.

Reduce Testnet Ban Time

---

src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs

Minor perf optimization. 
Instead of exiting async lock and then entering it inside EvictAsync I've moved eviction under the lock and changed the method to be EvictLocked. 
Also fixed TODO

CoinView: moved evict under lock

---

appveyor.yml
build.sh
src/FodyNlogAdapter/Adapters/LogManagerAdapter.cs
src/FodyNlogAdapter/Adapters/LoggerAdapter.cs
src/FodyNlogAdapter/FodyNlogAdapter.csproj
src/FodyNlogAdapter/Log.cs
src/FodyNlogAdapter/TracerAttributes.cs
src/FodyWeavers.xml
src/Stratis.Bitcoin.FullNode.sln
src/Stratis.Bitcoin/Stratis.Bitcoin.csproj

Adds additional compilation step that will add trace logging to all classes under Stratis.Bitcoin namespace.
This implements first step from list of steps covered in #2249 
PS:
to review this compile the solution, run it with trace logging on (any target with namespace Stratis.Bitcoin will do)- logs will contain entry and exit logs for every method. 
PSS:
To understand how exactly it works read links supplied in #2249

Fody tracer- adding entry\exit logs on compilation

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/NonceGeneratorTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/StateTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/StateTransitionSpecification.cs
src/Stratis.SmartContracts.Executor.Reflection/IState.cs
src/Stratis.SmartContracts.Executor.Reflection/NonceGenerator.cs
src/Stratis.SmartContracts.Executor.Reflection/State.cs
src/Stratis.SmartContracts.IntegrationTests/ContractExecutionFailureTests.cs

Closes #2259.
Uses a shared `NonceGenerator` during the lifetime of `State`, which corresponds to the lifetime of a transaction execution. If `State` is snapshotted, the snapshot will use the original `NonceGenerator` ensuring that even if execution fails, nonces will still increment.

[SC] Use shared nonce state during tx execution

---

src/Stratis.Bitcoin/Stratis.Bitcoin.csproj

Microsoft.Bcl.Build it is basicly a way for older packages that targeted older .Net to build and compile with no problems on new .Nets
Info: 
http://blogs.msdn.com/b/dotnet/archive/2013/11/13/pcl-and-net-nuget-libraries-are-now-enabled-for-xamarin.aspx
http://blogs.msdn.com/b/dotnet/archive/2013/08/12/improved-package-restore.aspx
Why we need this? 
On some PCs with old .nets or several versions of it `dotnet build` command will fail with:
```
Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, 
that the assembly and all its dependencies are available, and that the task contains a public
class that implements Microsoft.Build.Framework.ITask. 
[C:\Users\user\Desktop\StratisRepo\src\Stratis.Bitcoin\Stratis.Bitcoin.csproj]
```

Added microsoft.bcl.build

---

src/Stratis.Bitcoin.IntegrationTests.Common/Runners/BitcoinCoreRunner.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs

1. Some new RPCs have been added, which broke a relatively pointless test.
2. Tests using `bitcoind` on Windows are highly sensitive to path length. While this cannot be solved from within the tests, it can at least be made to fail rapidly, rather than wasting 5 minutes of execution time per test in some cases.

Minor test fix

---

src/Stratis.Bitcoin/Utilities/AsyncLoop.cs

Previous log had the problem of printing that the task was Starting even if delayStart was set
As a result of this, when you launched the node you were reading `Periodic peer flush starting.` and it seemed that it took so long to execute, when actually it had a delayStart of 5 minutes.
with current changes, in case of delay you see something like
`Periodic peer flush starting in 300 seconds.`
and when it start for real, you'll see the previous `Periodic peer flush starting.`

improved the logging of starting tasks

---

src/Stratis.Bitcoin.Tests/Utilities/DBreezeTest.cs
src/Stratis.Bitcoin/Utilities/DBreezeSerializer.cs

This is to allow us deserialise any types that implements IBitcoinSerialisable
This is a smaller change than the one suggested in #2331 for now.
It should help in https://github.com/stratisproject/FederatedSidechains/pull/118

deserialise any IBitcoinSerializable

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/StateTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/StateTransitionSpecification.cs
src/Stratis.SmartContracts.Executor.Reflection/BalanceState.cs
src/Stratis.SmartContracts.Executor.Reflection/ContractExecutor.cs
src/Stratis.SmartContracts.Executor.Reflection/IState.cs
src/Stratis.SmartContracts.Executor.Reflection/State.cs
src/Stratis.SmartContracts.Executor.Reflection/StateFactory.cs
src/Stratis.SmartContracts.Executor.Reflection/StateProcessor.cs
src/Stratis.SmartContracts.IntegrationTests/ContractInternalTransferTests.cs
src/Stratis.SmartContracts.IntegrationTests/SmartContracts/BalanceTest.cs
src/Stratis.SmartContracts.IntegrationTests/SmartContracts/ReceiveFundsTest.cs
src/Stratis.SmartContracts.IntegrationTests/Stratis.SmartContracts.IntegrationTests.csproj

Closes #2364 and #2349.
* For external calls/creates, store initial UTXO value to balance state against the contract's address
* For internal calls/creates/transfers, add internal transfers before applying the message to the state.
* Add tests

[SC] BalanceState and Transfer fixes

---

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs
src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingStakedCoinsBeforeMaturity_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
src/Stratis.SmartContracts.IntegrationTests/MockChain/Chain.cs
src/Stratis.SmartContracts.IntegrationTests/MockChain/Node.cs
src/Stratis.SmartContracts.IntegrationTests/SmartContractNodeSyncTests.cs
src/Stratis.SmartContracts.IntegrationTests/SmartContractWalletOnPosNetworkTests.cs
src/Stratis.SmartContracts.IntegrationTests/SmartContractWalletTests.cs

Move this method to the builder so that it checks after the node has started whether or not to set it's IBD state.
After this I'll move the WithWallet() method which will clean up the code even more.

[Integration Tests] Clean up NotInIBD

---

src/FodyNlogAdapter/Adapters/LoggerAdapter.cs

Add the ability for the debugger to not step into these methods to make debugging a bit more efficient.

[Logging] Add debugger step through to TraceEnter and TraceLeave

---

src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
src/Stratis.Bitcoin.Tests/Utilities/StopwatchTest.cs
src/Stratis.Bitcoin/Consensus/PerformanceCounters/ConsensusManager/ConsensusManagerPerformanceSnapshot.cs
src/Stratis.Bitcoin/Utilities/Stopwatch.cs

refactory of Stopwatch usage in DnsSeedServer class and documented Stopwatch implication of ElapsedTicks usage as per issue #2391

refactory of Stopwatch usage in DnsSeedServer

---

src/NBitcoin.Tests/NetworkTests.cs
src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs
src/Stratis.Bitcoin.Networks/StratisRegTest.cs

Closes https://github.com/stratisproject/StratisBitcoinFullNode/issues/2415
Stratis RegTesyt fees were incorrectly set to 0.
This has been fixed so that they inherit the values from Stratis Mainnet.

Fixed fees for Stratis Regtest

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/ObserverTests.cs
src/Stratis.SmartContracts.Executor.Reflection/Contract.cs
src/Stratis.SmartContracts/SmartContract.cs

Closes #2152. Replace all state fields with a single field. Fix docs on receive handler.
Note that this will make all accesses to the state fields more Gas expensive, as they now require a method invocation to retrieve. We can address this further with #2268.

[SC] Set single state field on contract

---

src/NBitcoin/Protocol/Versions.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
src/Stratis.Bitcoin.Features.Dns/IFullNodeBuilderExtensions.cs
src/Stratis.Bitcoin.Features.Dns/UnreliablePeerBehavior.cs
src/Stratis.Bitcoin/Builder/Feature/MissingServiceException.cs
src/Stratis.Bitcoin/Builder/FullNodeServiceProvider.cs

Implementation of #2147 
nodes that connects to our DNS node when PH gets activated, will be disconnected if they can't serve PH.
Extended the IFullNodeServiceProvider/FullNodeServiceProvider and used a better way to instance and register PeerBehavior like per issue #2402
Fixed tests

[PH] DNS Seed nodes to prefer using PH enabled nodes

---

src/Stratis.Bitcoin/Consensus/ProvenHeadersConsensusManagerBehavior.cs

Use `Network` `Consensus` to create a `ProvenBlockHeader`, instead of creating a new `PosConsensusFactory()`.

Use network consensus to create a ProvenBlockHeader.

---

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs

- Methodise out the CheckInput part of CoinviewRule
- Override this in SmartContractCoinviewRule
- Call to base in SmartContractCoinviewRule, avoiding much code duplication.
Should help with SC / PoA dev! Slowly a little more modular

Modular input check in CoinviewRule

---

src/NBitcoin/BlockHeader.cs
src/NBitcoin/ProvenBlockHeader.cs
src/Stratis.Bitcoin.Features.PoA/PoABlockHeader.cs
src/Stratis.Bitcoin.Features.SmartContracts/Consensus/SmartContractBlockHeader.cs

I merged #2538 but unfortunately it wasn't quite correct. 
This fixes the broken build.
We have separated the serialization of blocks from hash retrieval, as there are cases where we wish to add to the serialization but not to the hash (e.g. PH, PoA).
And base.ReadWrite wasn't going to last because we have to add to add extra fields to the hash in the case of smart contracts or other extensions

Fixing the ReadWriteHash functionality

---

src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs

Quite self-explanatory but in a nutshell, to be truly cross platform, we need to use Path.Combine when creating paths.

Fixed CanAuthWithCookieFile for non-Windows environments

---

src/NBitcoin/ConsensusOptions.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
src/Stratis.Bitcoin.Features.PoA/PoAConsensusOptions.cs
src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs
src/Stratis.Bitcoin.Networks/StratisMain.cs
src/Stratis.Bitcoin.Networks/StratisRegTest.cs
src/Stratis.Bitcoin.Networks/StratisTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsTest.cs

Added maxStandardTxSigopsCost ConsensusOptions property to fix #2470

[Mempool] CheckSigOps using incorrect constant (#2470)

---

src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs

Previously, this log would show coins that are spendable only but then immature coins wouldn't be included.
since it's supposed to show the balance of confirmed coins, immature coins should also included.
I've also added the unconfirmed balances.
It looks like this now:

Changed wallet logs to include immature coins in balance

---

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

Remove the callback when a downloaded block headers is not found

---

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/InitialBlockDownloadStateMock.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/FullNodeTestBuilderExtension.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/NodeRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisSmartContractPosNode.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerInterceptorTests.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs
src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
src/XUnitRetry/DelayedMessageBus.cs

We only really need to override the default DTP with integration tests where coins are staked. On occasion with the reorg tests the internal time of `GenerateCoinsFastDateTimeProvider` gets too far into the future and block creation fails for other tests as the transaction's time isn't valid anymore. 
This is because `GenerateCoinsFastDateTimeProvider` is subbed to `BlockConnected`, so every time a block is reconnected from a reorg, the DTP's internal clock also advances, which is incorrect.

[Integration Tests] Remove defaulted DateTimeProvider override for Pos Runners

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/AddressTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractLogHolderTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractPrimitiveSerializerTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodParameterByteSerializerTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodParameterStringSerializerTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/ObserverTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
src/Stratis.Bitcoin.Features.SmartContracts/Models/ReceiptResponse.cs
src/Stratis.SmartContracts.Core/Extensions.cs
src/Stratis.SmartContracts.Core/Hashing/HashHelper.cs
src/Stratis.SmartContracts.Core/IContractExecutionResult.cs
src/Stratis.SmartContracts.Core/Stratis.SmartContracts.Core.csproj
src/Stratis.SmartContracts.Executor.Reflection/AddressExtensions.cs
src/Stratis.SmartContracts.Executor.Reflection/ContractExecutor.cs
src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionResult.cs
src/Stratis.SmartContracts.IntegrationTests/MockChain/MockChainNode.cs
src/Stratis.SmartContracts.IntegrationTests/PoW/ContractExecutionFailureTests.cs
src/Stratis.SmartContracts.IntegrationTests/PoW/ContractInternalTransferTests.cs
src/Stratis.SmartContracts.IntegrationTests/PoW/ContractParameterSerializationTests.cs
src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs
src/Stratis.SmartContracts.Token.Tests/StandardTokenTests.cs
src/Stratis.SmartContracts/AssemblyInfo.cs
src/Stratis.SmartContracts/Block.cs
src/Stratis.SmartContracts/Message.cs

Removes all references to Stratis.SmartContracts (which is implementation-specific) from Stratis.SmartContracts.Core.

[SC] Fix boundaries of Stratis.SmartContracts.Core

---

src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs

This is to see if this fixes the timeout in integration tests as this test fails to complete:
`MempoolReceiveFromManyNodes`

[Mempool] AttachedPeer can be null when relaying.

---

src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerInterceptorTests.cs

This covers the scenario where minerA/B/C are synced to height 5. Miner C mines on its to height 10. When miner's A an B want to reorg to miner C's chain and their chain data has rewound to block 5, we intercept it and disconnect miner C. Miner's A and B should still synced to block 10.

[Integration Tests] Added second interceptor test for node disconnects

---

src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

1. 
Changed the size of consumed blocks in the console from
```
Unconsumed blocks: -126 -- (-50 633 / 209 715 200 bytes). Cache is filled by: -0.02%
```
to
```
Unconsumed blocks: -126 -- (-50,633 / 209,715,200 bytes). Cache is filled by: -0.02%
```
because space is not a proper separator for thousands.
2. 
Changed the balance of wallets in the console from
```
======Wallets======
Wallet: newWallet, Confirmed balance: 1000.00000000        Unconfirmed balance: 0.00000000
Wallet: newWallet, Confirmed balance: 0.00000000           Unconfirmed balance: 0.00000000
Wallet: myRecoveredWallet, Confirmed balance: 500.77550400         Unconfirmed balance: 0.00000000
```
to
```
======Wallets======
newWallet/account 0,           Confirmed balance: 1000.00000000        Unconfirmed balance: 0.00000000 …
```

Size formatting

---

src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs

Fixes https://github.com/stratisproject/StratisBitcoinFullNode/issues/2590
So before, when checking whether the size of transactions to be included in a block wouldn't exceed the max sigOps, we looked at the **size** of the trnsactions, rather than at the number of sigOps.
This is now fixed.

Fix the calculation of sigOps cost when mining a block

---

Scripts/linux-x64.package.sh
Scripts/osx-x64.package.sh
Scripts/windows-x64.package.ps1

Does what it says on the tin.
Use at will. 
The name of the file output contains the git commit of the code contained in the executable, e.g Stratis-a51d85c.exe.
To run testnet, just do `Stratis-a51d85c.exe -tesnet` in a command line.

Added scripts to compile the StratisD to one single executable 🤯

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs

Fixes #2570 .
The flow for nodes requesting blocks using `getblocks` (like stratisX) is the following:
node A `getblocks` (do you have these blocks?) ----> node B
node A <--------- `inv` (yeah I got these hashes) node B
node A `getdata` (I like that, send blocks to me) ----------> node B
node A <------- `block` node B
node A <------- `block` node B
node A <------- `block` node B
etc..
Then, the logic in X says that if node B has sent the max number of block hashes in the `inv` to node A, then node B needs to send one last `inv` containing the last block hash, to trigger A into sending another `getblocks`.
```
int nLimit = 500;
LogPrint("net", "getblocks %d to %s limit %d\n", (pindex ? pindex->nHeight : -1), hashStop.ToString(), nLimit);
for (; pindex; pindex = pindex->pnext)
{
if …
```

Make sure we send an inv message to downloaders needing more blocks.

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs
src/Stratis.Bitcoin.Features.BlockStore/ProvenHeadersBlockStoreSignaled.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderRepositoryTests.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderStoreTests.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderRepository.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderStore.cs
src/Stratis.Bitcoin/Interfaces/IProvenBlockHeaderProvider.cs
src/Stratis.Bitcoin/Interfaces/IProvenBlockHeaderRepository.cs
src/Stratis.Bitcoin/Interfaces/IProvenBlockHeaderStore.cs

Implemented as per #2589 requirements
Actually it's not yet complete because it isn't clear what to do once a ProvenHeader is created because the arguments passed, are then used to announce the blocks and so if a header is a legacy header this wouldn't work.
Moreover the eventual assignment
//blockPair.Block.Header = blockPair.ChainedHeader.Header = createdProvenHeader;
can't actually be done because both those property setters aren't accessible and I'm not sure is a good idea to set them public or have a way to change it once a block has been instantiated
as a final note it seems we want to get rid of whitelisted legacy nodes so the creation shouldn't be needed (all nodes should talk using proven header)

PH BlockStoreSignaled (#2589)

---

src/NBitcoin/ChainedHeader.cs
src/Stratis.Bitcoin.IntegrationTests/Compatibility/StratisXTests.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs

When we handle ChanedHeaders we should assume that at any given moment a peer may get disconnected and the chain will be removed form the tree.
**Unhandled yet**
The problematic scenario is when we are in the middle of a big reorg and the only peer that claims this branch gets disconnected.
For example a reorg of 10 blocks and at block 5 the only peer claiming this branch is disconnected we will remove the entire branch of the reorg from the tree.
Two ways to fix it
1. We observe the branch was disconnected and try to reconnect
2. We place a temporary claim on a branch that is about to be connected, then this branch will not get removed on disconnect.

Consensus manager reorg bug

---

src/Stratis.Bitcoin.Features.Wallet/Wallet.cs

A node with an active wallet calls these methods a very large number of times.

Tweak level of trace logs in wallet

---

src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs

There are some optional parameters we were ignoring in previous implementation. Throw exceptions when they are not well formed.
Bitcoin core docs https://bitcoincore.org/en/doc/0.16.0/rpc/wallet/getnewaddress/
Related to https://github.com/MetacoSA/NBitcoin/pull/413

[RPC] Properly handle optional parameters for getnewaddress

---

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs

Closes https://github.com/stratisproject/StratisBitcoinFullNode/issues/2518
This will leave out from processing in the wallet:
- poa mining transactions
- coinbase transactions in pos
- first coinstake output
where we know we're not gonna save anything to the wallet.
This will also improve performance a bit.

Wallet: skip processing of transactions with 0 in output

---

src/Stratis.Bitcoin.Features.SmartContracts/PoA/Rules/SmartContractPoACoinviewRule.cs
src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinViewRuleLogic.cs
src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinviewRule.cs

Separates logic shared between SC base and PoA CoinViewRule implementations. PoS is different (and inherits from ScCoinViewRule), so I left it untouched. Goal is to prevent bugs like #2755 in the short term. Ideal long-term solution requires refactoring of the FN CoinViewRule implementation, which is not in the immediate plan.
Closes #2755.

[SC] Shared CoinViewRule logic

---

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingFeature.cs

This adds the address book into the cold staking wallet feature that replaces the wallet feature. the address book was somehow omitted in the merge but it's now back in.
The second commit tidies up the console output to show accounts in a more compact way.

added support for addressbook to cold staking feature

---

src/NBitcoin/BlockStake.cs
src/NBitcoin/ProvenBlockHeader.cs

reverted back GetCoinstakeOrNewTransaction to GetCoinstakeOrCoinBase
related to #2787

SBFN PH: Two PH SBFN nodes fail to sync from each other

---

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/LoadCoinviewRule.cs
src/Stratis.Bitcoin.Features.Consensus/UnspentOutputSet.cs

Trivial change - removes a variable that is not being used and makes the API for dealing with an UnspentOutputSet a little nicer

[Consensus] Remove unused ICoinView parameter

---

src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs

Fixes #2761
I examined other calls to `CachedCoinview.FetchCoinsAsync` and they all either use the CoinviewHelper (which internally utilises a HashSet) or only fetch one transaction at a time. This was the only apparent place where de-duplication needed to be done.

[Coinview] Deduplicate coinview cache fetches for staking

---

src/Stratis.Bitcoin/Configuration/NodeSettings.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs

Used to be `StratisBitcoin:1.2.5`.
`StratisBitcoin` has changed to `Stratis` and we now include the protocol version.

Change the agent to be like Stratis:1.2.5 (70012)

---

src/Stratis.Bitcoin.Features.Consensus/PosConsensusFeature.cs
src/Stratis.Bitcoin.Features.PoA/PoAFeature.cs

about #2846 
this fixes the exception message itself (triggers the guard) but the reason why this exception was rised ins't clear yet.
This can be merged as it is, the problem probably should be fixed on the sidechain repo

Error in PosConsensusFeature.InitializeAsync #2846

---

src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderRepositoryTests.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderStoreTests.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderRepository.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderStore.cs
src/Stratis.Bitcoin/Interfaces/IProvenBlockHeaderProvider.cs

GetAsync now looks into pending batch first. 
Also removed GetAsync overload from the codebase because it wasn't implemented properly and would ask repo for headers one by one. Also given that we don't use this method and don't plan to (mostly because we will keep PH always in memory like ChainedHeaders) it wasn't reasonable to fix it over removing it. 
Fix: #2873

Fix for "PHBS can serve reorged headers"

---

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs

Also adds secondary ordering by txhash, so that multiple histories in the same block still appear in logical order.
Closes #2775.

[SC] Display history with empty block numbers first

---

src/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common/PoANodeRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/TestChainedHeaderTree.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/FullNodeTestBuilderExtension.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowRunner.cs
src/Stratis.Bitcoin.IntegrationTests/Compatibility/StratisXTests.cs
src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/ColdWalletTests.cs
src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
src/Stratis.SmartContracts.Tests.Common/StratisSmartContractNode.cs
src/Stratis.SmartContracts.Tests.Common/StratisSmartContractPosNode.cs

Usage:
```
var testCHT = stratisNode1.FullNode.NodeService<TestChainedHeaderTree>();
Dictionary<uint256, ChainedHeader> chainedHeadersByHash = testCHT.ChainedHeadersByHash;
Dictionary<uint256, HashSet<int>> peerIdsByTipHash = testCHT.PeerIdsByTipHash;
Dictionary<int, uint256> peerTipsByPeerId = testCHT.PeerTipsByPeerId;
```

Ability to access private CHT members in tests

---

src/Stratis.Bitcoin.Features.PoA.Tests/SlotsManagerTests.cs
src/Stratis.Bitcoin.Features.PoA/KeyTool.cs

It'd be nice to be able to just use a path for the tool.
Also, generating the mining keys on the fly is not great UX, because there are too many steps between mining key generation and miners actually mining.
An idea we had is to generate the federationKey.dat file at the same time as the 
federation members generate the signing key. 
Then everyone share their keys and the networks are created. 
Finally, miners can start the federation member sidechain node by specifying the path to the federationKey.dat file.
@noescape00 @monsieurleberre

Added custom path for KeyTool

---

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs

Allowed syncing using normal headers before the last checkpoint for gateway nodes
That should speed up initial syncing for gateway nodes
Also fixed deadlock caused by disconnection when peer is in the same group

Gateway node should be able to sync normal headers before last checkpoint

---

src/Stratis.Bitcoin.Features.Api/appsettings.json

Changed this because when I create an exe, this appsettings is distributed the package and as a result, debug statements show up in the console.

Changed Default log lovel to Information for API appsettings

---

src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoABlockDefinition.cs

First step to fix: https://github.com/stratisproject/FederatedSidechains/issues/237
After this PR is merged we will need to create new nuget packages, update them on federation sidechains projects, then update `SmartContractPoABlockDefinition.cs` since constructor was changed and we need to pass nodeSettings to base constructor.

Fix issue: Additional fedpeg folder created

---

src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

Fix issue
```
Stratis.Bitcoin.Consensus.ConsensusException: input missing/spent
at Stratis.Bitcoin.Consensus.ConsensusManager.BlockMinedAsync(Block block) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 281
at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.CheckStakeAsync(Block block, ChainedHeader chainTip) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 490
at Stratis.Bitcoin.Features.Miner.Staking.PosMinting.GenerateBlocksAsync(WalletSecret walletSecret, CancellationToken cancellationToken) in C:\Users\fullnodedan\Documents\Github\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Miner\Staking\PosMinting.cs:line 408
at …
```

Fix unhandled miner exception

---

src/NBitcoin/TransactionBuilder.cs

Extending the functionality to the wallet transaction handler can be done at a later stage. This just needs to be introduced at this level of the code as it is not clean having to re-sign transactions in the wallets' handlers after transaction construction instead.

Add timestamp to transaction builder

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderRepositoryTests.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/ProvenBlockHeaders/ProvenBlockHeaderStoreTests.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderRepository.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreSignaledTests.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
src/Stratis.Bitcoin.IntegrationTests/NodeContext.cs
src/Stratis.Bitcoin.Tests.Common/TestBase.cs
src/Stratis.Bitcoin.Tests/Base/ChainRepositoryTest.cs
src/Stratis.Bitcoin.Tests/FinalizedBlockInfoRepositoryTest.cs
src/Stratis.Bitcoin.Tests/Utilities/DBreezeTest.cs
src/Stratis.Bitcoin/Base/BaseFeature.cs
src/Stratis.Bitcoin/Base/ChainRepository.cs
src/Stratis.Bitcoin/FinalizedBlockInfoRepository.cs
src/Stratis.Bitcoin/Utilities/DBreezeSerializer.cs

What:
Removes responsibility for complex object serialization from DBreeze and pushes it into the repository layer.
Why:
Solves an issue with DBreeze whereby a static `ByteArray(De)Serializator` instance can not be shared across multiple networks. Closes stratisproject/FederatedSideChains#297.
Summary:
* Inline all complex object serialization.
* Remove use of `CustomSerializator.ByteArraySerializator` and `CustomSerializator.ByteArrayDeSerializator`.
* DI `Network` into `DBreezeSerializer`
* Rename serialization methods to better fit the API
Chain syncs up to 100k. Tests are passing. I will let CI run the integration ones.
cc @codingupastorm @quantumagi

Inline serialization of complex types for database transactions

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs
src/Stratis.Bitcoin.Features.BlockStore/IPrunedBlockRepository.cs
src/Stratis.Bitcoin.Features.BlockStore/PrunedBlockRepository.cs
src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletSyncManagerTest.cs
src/Stratis.Bitcoin.Features.LightWallet/Blocks/ILightWalletBlockStoreService.cs
src/Stratis.Bitcoin.Features.LightWallet/Blocks/IPruneBlockStoreService.cs
src/Stratis.Bitcoin.Features.LightWallet/Blocks/LightWalletBlockStoreService.cs
src/Stratis.Bitcoin.Features.LightWallet/Blocks/PruneBlockStoreService.cs
src/Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs
src/Stratis.Bitcoin.Features.LightWallet/LightWalletInitialBlockDownloadState.cs
src/Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs
src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
src/Stratis.Bitcoin.Features.Notifications/BlockNotificationFeature.cs
src/Stratis.Bitcoin.Features.Notifications/TransactionNotification.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletSyncManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs
src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
src/Stratis.BreezeD/Program.cs
src/Stratis.BreezeD/Properties/launchSettings.json

In this PR the node will now prune its database on startup and shut down.
An async loop will run that periodically deletes blocks from the block store. It will keep blocks up until 1000 blocks from the store tip.
On shutdown the database will be "compacted" so that all the deleted references are removed from the file and the database file re-saved.
On startup the node will check to see if its needs to be pruned (i.e. if the pruned tip is more than 1000 blocks from the store tip) if it is needed the database will be pruned and shrunk.
Some tests are still failing which I am looking at.
I have tested this extensively and the breeze wallet syncs fully.
The size of the DB after compactin is about 290kb.

[Light Wallet] Fix Breeze node and introduce pruning

---

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

We recently observed a failed reorg and when trying to reconnect the older chain back we failed.
This will at least provide the consensus reason for the failure.

Add more logs to CM when failed to reconnect the old chain.

---

src/Stratis.Bitcoin.Cli/Program.cs

This through me for a bit of a loop. The sequence of parameters for RPC calls is incorrect in the examples for the CLI.
I reordered the documentation so the examples actually work.

Fix up incorrect examples in CLI for RPC

---

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersReservedSlotsBehavior.cs
src/Stratis.Bitcoin.Features.Consensus/PosConsensusFeature.cs
src/Stratis.Bitcoin.IntegrationTests/ProvenHeaderTests.cs

fixed a bug in ProvenHeadersReservedSlotsBehavior that was disconnecting the wrong peer.
attached ProvenHeadersReservedSlotsBehavior to peer behaviors template.
Created part of an integration test to cover the scenario (skipped because incomplete).

Attach ProvenHeadersReservedSlotsBehavior to peer behaviors in PoS network

---

src/Stratis.Bitcoin.Features.Consensus/Rules/ProvenHeaderRules/ProvenHeaderCoinstakeRule.cs

Low priority but this was reported as an issue on one of the tests in simulation network.

Check StakeModifierV2 property is not null on a PH

---

src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderRepository.cs
src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs

This check is redundant as when we reorg we just overwrite the values in the proven header repo. I.e. it is possible to call flush chain and the `provenBlockHeaderTip` be the same as the new tip we are trying to store.
Relates to #3012

[ProvenHeaders] Remove same hash check

---

src/Stratis.Bitcoin/Utilities/LoggingExtensions.cs
src/Stratis.Bitcoin/Utilities/PrefixLogger.cs

I was looking at some full logs and I noticed that we log what we're about to log.
Look here:
The blue bit is the log, the red bit is the meta-log.

Remove some logging about logging

---

src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderStore.cs

I was running some tests and noticed that the repository wasn't being disposed and DBreeze was locking the folder. 
This fixes it.

Dispose the PH repository when the PH store gets disposed.

---

src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs

If by the time we've added an entry to a block and the tx does not exist in the mapped tx collection in the mempool, don't try and process it further.

[Mempool] Fix exception when finding ancestors for added entry to block

---

src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs

Fixes this test case which was not building a transaction big enough to be sufficiently near the policy byte limit (95,000 to 100,000 bytes).

Fix sending_transaction_near_policy_byte_limit

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs

See #3041.
This test case is failing due to not selecting all the expected inputs. It has to take into account that `BuildTransaction` will only select enough inputs to make up the total spend amount.

Fix FundTransaction test case

---

src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs

Some tests were marked as requiring #2474 before they could be completed.
However, transaction rejection for transactions newer than the future drift time is already separately tested in the integration tests. It is not entirely clear what was meant by 'expired transaction times' in some of the unimplemented test names, so these have been removed.
Positive and negative integration tests for non-relative locktimes have also been added.

[Mempool] Adjustments to mempool tests

---

src/Stratis.Bitcoin/Consensus/ConsensusErrors.cs

With the way that the `ConsensusErrors` class is defined currently ALL the error object constructors are called whenever this class is used to raise an error. This avoids that by postponing object creation as follows:
```
public static readonly ConsensusError InvalidPrevTip = new ConsensusError("invalid-prev-tip", "invalid previous tip");
public static readonly ConsensusError HighHash = new ConsensusError("high-hash", "proof of work failed");
public static readonly ConsensusError BadCoinbaseHeight = new ConsensusError("bad-cb-height", "block height mismatch in coinbase");
...
```
changed to:
```
public static ConsensusError InvalidPrevTip => new ConsensusError("invalid-prev-tip", "invalid previous tip");
public static ConsensusError HighHash => new ConsensusError("high-hash", "proof of …
```

Avoid multiple constructor calls

---

src/Stratis.Bitcoin.Cli/Program.cs
src/Stratis.Bitcoin.Cli/Stratis.Bitcoin.Cli.csproj

Currently the CLI always performs a GET operation when calling the API. 
This PR adds a call to the POST method if the GET method is not found.
EDIT: This has changed in favor of specifying the method on the command line:
`dotnet run <Stratis.Bitcoin.Cli/Stratis.Bitcoin.Cli.dll> [network-name] [options] [method] <command> [arguments]`

CLI to perform POST if GET not found

---

src/NBitcoin/Target.cs
src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs

Optimised array creation in `Target` and `StakeValidator`.
This is to help combat memory fragmentation in the node during IBD. The node is struggling to release unused or free space once it exits IBD.
Before:
```
0:000> !dumpgen 2 -stat
Count      Total Size      Type     
3,756,208    180,297,984   NBitcoin.uint256
742,164    441,369,177   System.Byte[]
582,818    544,742,724   **** FREE ****
```
After fixing some byte array creation:
```
0:000> !dumpgen 2 -stat
Count      Total Size      Type
2,467,683    115,490,916   System.Int32[]
4,153,281    199,357,488   NBitcoin.uint256
822,896    448,630,928   **** FREE ****
GEN 2:
2,489,824    116,410,048   System.Int32[]
879,858    188,783,732   **** FREE ****  
```

[NBitcoin] Optimise byte array creation

---

src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

fixes the `Consensus Manager displays negative value for Unconsumed Block` issue #2587

fix for Consensus Manager displays negative value for Unconsumed (2587)

---

src/Stratis.Bitcoin.IntegrationTests.Common/BlockObserverFeature.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/BlockBuilder.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/NodeRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowRunner.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerFailedReorgTests.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerInterceptorTests.cs
src/Stratis.Bitcoin.IntegrationTests/Program.cs

@dangershony noticed that some of the reconnect chain integration tests runs too quickly for the test too properly assert whether or the `Reconnect` chain methods in `ConsensusManager` was in fact called. This was purely due to the whole reconnect logic not being properly waited on to complete, thus the test completes whilst the node is still doing its thing.
I've extended the interceptors on those tests to be more robust and accurate. Now we can with precision "stop" the node at any point during the block connect and disconnect process and perform custom logic.

Ensure Consensus Manager Integration tests run more accurately

---

src/Stratis.SmartContracts.CLR.Tests/ContractTransferProcessorTests.cs
src/Stratis.SmartContracts.CLR.Tests/DeterminismErrorMessageTests.cs
src/Stratis.SmartContracts.CLR.Validation/Validators/Instruction/FloatValidator.cs

Closes #3076.
Thought there were a lot more tests comparing to non-constant strings but this seems to be the only one. Any future tests written can update the strings when needed.
Also removing some unused variables.

[SC] Minor changes to tests

---

src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs

Here are a few numbers to explain why I did that.
After 5h logs with Tracing enabled, a file of 27GB was produced for Base (base.txt) containing 190 millions lines.
`Stratis.Bitcoin.Base.Deployments.ThresholdConditionCache.ContainsKey` appears on 1M times. 💣 
`Stratis.Bitcoin.Base.Deployments.ThresholdConditionCache.Mask`appears on 57M lines. 💣 💣 
`Stratis.Bitcoin.Base.Deployments.ThresholdConditionCache.Condition` appears on 131M lines. 💣 💣 💣 💣 💣 💣 💣 💣 
After this goes in, let's see if maybe we're calling this too much.

[Logs] Remove some logging from ThresholdConditionCache

---

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletPostOperationsTests.cs

When the wallet gets out of sync, we already had the ability to completely clean it from transactions and resync. But for big wallets, this may mean resyncing 18 months of transactions.
In this PR we have the ability to specify a date after which back to which we want the wallet to "roll-back".
This useful will need some UI in StratisCore but an API endpoint is exposed.

[Wallet] Remove transactions from date

---

src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerFailedReorgTests.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerInterceptorTests.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs

Also ensure that `ReorgChain_FailsPartialValidation_Nodes_ConnectedAsync` and `ReorgChain_FailsPartialValidation_Nodes_DisconnectedAsync` waits on the respective node to disconnect the other, due to partial validation failure.

Update consensus manager tests to use ReadyBlockchainData

---

src/Stratis.Bitcoin.Features.PoA.Tests/Rules/PoARulesTestsBase.cs
src/Stratis.Bitcoin.Features.PoA.Tests/SlotsManagerTests.cs
src/Stratis.Bitcoin.Features.PoA.Tests/VotingDataEncoderTests.cs
src/Stratis.Bitcoin.Features.PoA/FederationManager.cs
src/Stratis.Bitcoin.Features.PoA/KeyTool.cs
src/Stratis.Bitcoin.Features.PoA/PoAConsensusOptions.cs
src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs
src/Stratis.Bitcoin.Features.PoA/SlotsManager.cs
src/Stratis.Bitcoin.FullNode.sln
src/Stratis.Bitcoin.Tests/Utilities/DBreezeTest.cs
src/Stratis.Bitcoin/Utilities/DBreezeSerializer.cs
src/Stratis.Bitcoin/Utilities/KeyValueRepository.cs

Refactoring, tests, ability to save and load federation member keys to db. 
This PR corresponds to `Keep list of active federation members inside of the FederationManager and use it instead of list from the network` item in the design doc

PoA_DynamicFederationMembers_2

---

src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
src/Stratis.Bitcoin/Utilities/UnspentOutputs.cs

This is the scenario that likely caused  UTXOs to be out of sync in the cache
- [FetchCoinsAsync] Acquire the lock
- [FetchCoinsAsync] Fetch happens trx is not in cache
- [FetchCoinsAsync] Release the lock and try to fetch the trx from disk
- [RewindAsync ] The Lock is acquired by rewind we deleted the trx from disk and clear the cache
- [FetchCoinsAsync] Will wait for the lock to be released
- [RewindAsync] Release the lock
- [FetchCoinsAsync] Take the lock and add the rewinded trx to cache
- [FetchCoinsAsync] A block with that same reorged trx comes -> bip30 bug

Race condition coinview bug

---

src/Stratis.SmartContracts.IntegrationTests/SmartContractNodeSetupTests.cs
src/Stratis.SmartContracts.Tests.Common/SmartContractPoARunner.cs
src/Stratis.SmartContracts.Tests.Common/StratisSmartContractNode.cs
src/Stratis.SmartContracts.Tests.Common/StratisSmartContractPosNode.cs

This is to bring the SC and POA integration tests in line with all the other tests.

[Integration Tests / SC] Disable Peer Discovery and PeerDiscoveryConnector

---

src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs

Fix RPC batching when method doesn't exist. Also add a test that tests that scenario.
Fix RPC validateaddress to return invalid for P2WSH addresses (which we currently don't support)
Used by NBitcoin Altcoins.

[RPC] Fixes for RPC for NBitcoin integration

---

src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs

OperationCanceledException is being throw when:
a) handshake times out
b) peer is not connected
c) AsyncQueue is already disposed
This commit makes it more clear why a peer gets disconnected.
Fix #2998

Improve peer disconnect message

---

src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs

Fixes an issue where a race condition was happening between the notification reaching the wallet and our code making it to the Assert.

[SC] Fix sporadically failing SC integration test

---

src/Stratis.SmartContracts.RuntimeObserver/Stratis.SmartContracts.RuntimeObserver.csproj

Has already been deployed to NuGet. 
Important because everything uses 'Gas' from this package now. Will get weird hidden issues if we don't have our packages requiring this version.

[SC] Up RuntimeObserver package

---

src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs
src/Stratis.SmartContracts.Tests.Common/MockChain/PoAMockChainFixture.cs
src/Stratis.SmartContracts.Tests.Common/MockChain/TargetSpacingDateTimeProvider.cs

Should make tests run 'deterministically' -> the time being fed to them will be consistent and so should avoid certain race conditions with poa turn-taking

[SC] Start test PoA mockchains from same time

---

src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/ProvenBlockHeaderRepository.cs
src/Stratis.Bitcoin/Utilities/DBreezeRetryOptions.cs
src/Stratis.Bitcoin/Utilities/RetryOptions.cs
src/Stratis.Bitcoin/Utilities/RetryStrategy.cs

This is related to the issue when DBreeze transaction commit throws an I/O exception during disk write when multiple nodes are running on the same disk.
Another thing to consider is to upgrade DBreeze nuget package from 1.89 to 1.92 as few minor improvements were made.

Add retry logic

---

src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs

Give a better error when wallet is locked and spend is attempted. Add test for this scenario.

[RPC] Better error handling with sendmany

---

src/Stratis.Bitcoin.Features.Wallet/Models/GetTransactionModel.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletRPCControllerTest.cs

- fixed amount, fee and times types
- added vout to gettransaction response object
- added outputIndex to spend transactions
example response of a transaction sent to oneself (see example [here](https://bitcoin.org/en/developer-reference#gettransaction)):
```
{
"amount": 0.0,
"confirmations": 645,
"blockhash": "c5cedbee6465116742c1326b9447e1b0bfdac3cc476597ddc45d1e543431a7f4",
"blockindex": 2,
"blocktime": 1550580960,
"txid": "4487bcc967f04f607e428cb7bf0bf0fd4d17dddabf0be10fb6d863e92559c9d7",
"time": 1550580944,
"timereceived": 1550580944,
"details": [{
"address": "TLyPPCF4B7eePA1UkWf2hKGTGTtLuCA8Sr",
"category": "send",
"amount": -1.0,
"vout": 0
}, {
"address": "TLyPPCF4B7eePA1UkWf2hKGTGTtLuCA8Sr",
"category": "receive",
"amount": 1.0,
"vout": 0
}],
"hex": …
```

[RPC] Fix Json types for gettransaction response

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs

* Previously WaitLoop would return true before the connection was established, resulting in a race condition in some tests that immediately check for the number of connected peers.
* Previously some ConsensusManager tests would not wait for block heights or block hashes to reach the expected values (some were fine but have updated for consistency)
* Log WaitLoop inner exceptions so we can get a better insight into tests failures

Fix test race conditions

---

src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs
src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersConsensusManagerBehavior.cs
src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs
src/Stratis.Bitcoin/Consensus/PeerGetHeaderRequestBehavior.cs

Remove tracing for every incoming message also when not related to the behaviour itself.
When we trace on any incoming message most of the log messages look like this
```
[2019-02-25 11:10:17.2664 470] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.OnMessageReceivedAsync ()
[2019-02-25 11:10:17.2664 470] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.ProcessMessageAsync ()
[2019-02-25 11:10:17.2664 470] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior+<ProcessMessageAsync>d__24.MoveNext (-)
[2019-02-25 11:10:17.2664 470] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior+<OnMessageReceivedAsync>d__23.MoveNext (-)
[2019-02-25 11:10:17.3366 470] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.OnMessageReceivedAsync () …
```

Remove tracing for every incoming message 

---

src/Stratis.Bitcoin.IntegrationTests/Connectivity/ConnectivityTests.cs
src/Stratis.Bitcoin/P2P/PeerSelector.cs

The issue here was that when we select peers for GetAddrPayload we filter them out by checking when last we connected or handshaked due a 60 second delay. We don't need to filter them in this instance.

Fix Ensure_Peer_CanDiscover_Address_From_ConnectedPeers_And_Connect_ToThem

---

src/NBitcoin.Tests/NetworkTests.cs
src/Stratis.Bitcoin.Networks/BitcoinMain.cs
src/Stratis.Bitcoin.Networks/BitcoinTest.cs
src/Stratis.Bitcoin.Networks/StratisMain.cs
src/Stratis.Bitcoin.Networks/StratisTest.cs

Bitcoin networks were updated to be the same as bitcoin core.
For Stratis networks took values about 1000 blocks back from current tip.

Update assumevalid hashes for various networks

---

src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs

When configuring NLog to auto-archive files it will  save the archived files to the bin folder rather than Logs folders.
This change modifies the ArchiveFileName in similar name as we modify log FileName.

Modified ArchiveFileName so that NLog will archive log files into the Logs folder

---

src/Stratis.Bitcoin/Connection/ConnectionManager.cs
src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs

moved the peersbyid.add call earlier
adjusted the peer console dump (added cacheHeaders information and compressed the Inbound/Outbound direction
UPDATE:
fixed a nasty bug that was causing peers to stuck (and potentially stuck node too)

Fixed peer that were stuck

---

src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs

Fix
```
Using launch settings from C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.StratisD\Properties\launchSettings.json...
There was a problem initializing the node. Details: 'System.NullReferenceException: Object reference not set to an instance of an object.
at Stratis.Bitcoin.Configuration.Logging.LoggingConfiguration.AddFilters(LogSettings settings, DataFolder dataFolder) in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Configuration\Logging\LoggingConfiguration.cs:line 133
at Stratis.Bitcoin.Configuration.Logging.LoggingConfiguration.AddFilters(ILoggerFactory loggerFactory, LogSettings settings, DataFolder dataFolder) in C:\Users\dan\Documents\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Configuration\Logging\LoggingConfiguration.cs: …
```

Fix archive file null on logger startup

---

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Models/WalletHistoryModel.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletPostOperationsTests.cs

The index of a transaction in a block is useful for smart contracts and some RPC methods.
😑  Added it under the name `blockIndex`, which isn't particularly nice, but txindex is taken by something else, and bitcoin uses blockIndex as well.
Related to https://github.com/stratisproject/StratisBitcoinFullNode/issues/2823.

[Wallet] Added the index of a transaction in the block 

---

src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs

This commit does not change how the code works. `token` local variable is used instead of `this.stakeCancellationTokenSource.Token` member variable  so that `token` is no longer unused variable.
Fixes #3307

Use the better of the same two tokens

---

src/Stratis.Bitcoin/Builder/FullNodeBuilder.cs
src/Stratis.Bitcoin/Configuration/NodeSettings.cs

This PR:
1) Brings back printing of usage information and base settings
2) Building of the default configuration file as it relates to the base settings.

Fix regression issues with Printhelp and BuildDefaultConfigurationFile

---

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs

The method requires an optimization to avoid adding keys for the same address more than once. Addition of keys is a slow process so if we have a large number of UTXOs (e.g. 351) due to stake splitting the method will appear to hang.

Fix GetColdStakingWithdrawalTransaction unresponsiveness

---

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/ColdWalletTests.cs

This PR adds key lookup initialization at the point where new cold staking addresses are created.
Previously cold staking transactions would be omitted from the wallet unless the wallet had been reloaded between address creation and address usage - i.e. cold staking balances may remain 0.
The unit tests had not detected this issue due to the keys lookup initialization that had been present in the tests themselves. That initialization has been removed from the tests as part of this fix.

Fix cold staking keys lookup initialization

---

src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs

Closes #1446.
Uses `Parallel.ForEach` to run each `CheckInput` in parallel. If a single `CheckInput` fails, the loop is stopped and no more inputs are checked.

Cancel CheckInputs in CoinViewRule

---

src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.Features.RPC/Models/BlockchainInfoModel.cs
src/Stratis.Bitcoin.Features.RPC/Models/NetworkInfoModel.cs
src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs

`getinfo` is deprecated in newer versions of bitcoin core. I've moved some of its functionality to these new methods and added some additional capability as well.
NBXplorer uses the newer `getblockchaininfo` and `getnetworkinfo` to retreive node status information. This PR is not a complete implementation of the new RPC methods but hopefully will be enough for NBXplorer. Partly addresses #3306 
I will add to this PR if I find I need additional fields for these RPC calls.

[RPC] Initial implementation of getblockchaininfo and getnetworkinfo

---

src/Stratis.Bitcoin.Features.Consensus.Tests/MerkleRootComputationTest.cs
src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockMerkleRootRule.cs

Hi,
This PR reduces the number of memory allocations needed in `ComputeMerkleRoot()`.
I tried to measure it in very simplified manner:
```C#
[Fact]
public void MerkleRootComputationMutated()
{
GC.TryStartNoGCRegion(200_000_000);
long kbAtExecution = GC.GetTotalMemory(false) / 1024;
for (int i = 0; i < 10_000; i++)
{
var leaves = new List<uint256>()
{
new uint256("281f5acb40a65640bc48b90b5296a87d09341e3510608b191c9bc3a511f8e436"),
new uint256("d0249653efaaa999f0278bb390c0f4ec3e5465a10f35264ebcfbb6dd6a677abd"),
new uint256("7897c117fddbf98ea9749cc868a9d1e663b198dd3ac0ae5837734007f0060b20"),
new uint256("ced314892a97f342a136269e2842fd0dbd1cab1fa84557bc48420f7cf96f0bc7"),
new uint256("5b98af3d7554916483bca1a52f16570a93f07c95d6aeb8d08b0794c86cf58128"),
new …
```

Optimize memory allocations in BlockMerkleRootRule.ComputeMerkleRoot()

---

src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedMasterFile.cs
src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs
src/Stratis.Bitcoin.Features.Dns/IMasterFile.cs
src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs

Fix for [3163](https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3163). 
* Move the Seed method into `DnsSeedMasterFile` so that it is responsible for managing its own state.
* Remove the Add method to prevent the collection being modified externally.
* Seed the new masterfile _before_ swapping it. As this is only time the entries are modified, this should fix the serialization issue.
* Defensively, only serialize a copy of the entries.

Fix for serializing DnsSeedMasterFile

---

src/Stratis.Bitcoin.Features.RPC/IPAddressBlock.cs

See BUG 2970.
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/2970/
This PR makes e.g:
- rpcallowip=10.0.75.0/4 equivalent to its normalized form 0.0.0.0/4.
- rpcallowip=10.0.75.0/8 equivalent to its normalized form 10.0.0.0/8.
- rpcallowip=10.0.75.0/16 equivalent to its normalized form 10.0.0.0/16.
See "table of sample ranges" in https://www.mediawiki.org/wiki/Help:Range_blocks

Support non-normalized CIDR block ranges

---

src/Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs
src/Stratis.Bitcoin.IntegrationTests/Compatibility/StratisXTests.cs

Fixes a `Sequence contains no elements` error which occurs when the data directory contains no wallets.

Fix GetFirstWalletBlockLocator

---

src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletRPCControllerTest.cs

Added the fee for sent transaction details in the `gettransaction` RPc method.
More details on how the fee is calculated and display in this PR. https://github.com/stratisproject/StratisBitcoinFullNode/pull/3212
Closes VSTS 3173.

[RPC] Added fee for sent transactions in RPC method gettransaction

---

src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinImmutableTests.cs
src/Stratis.Bitcoin.Tests/Utilities/AsyncExecutionEventTest.cs
src/Stratis.Bitcoin.Tests/Utilities/AsyncManualResetEventTest.cs
src/Stratis.Bitcoin.Tests/Utilities/AsyncQueueTest.cs
src/Stratis.Bitcoin.Tests/Utilities/ParallelAsyncTest.cs

Though xUnit seems to support tests that return `async void` through a [custom synchronization context](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/AsyncTestSyncContext.cs), best practices are to return `async Task` instead of `async void`.
I've deliberately excluded FedPeg tests which are being updated in a separate PR.

Change tests to return async Task instead of async void

---

src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTestsMutable.cs
src/Stratis.Bitcoin/Controllers/Models/BlockHeaderModel.cs

Fixes #3356 
Also small fix to getblockchaininfo RPC, correctly populate IsInitialBlockDownload.

[RPC] Support hex output for getblockheader method

---

src/NBitcoin/Protocol/PerformanceCounter.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs
src/Stratis.Bitcoin/Connection/IConnectionManager.cs
src/Stratis.Bitcoin/P2P/PeerConnector.cs

Performed manual testing by calling the `disconnect` API method. The resulting totals in the `ConnectionManager` counter are as expected (i.e. those of the disconnected peer(s)), and are still reflected in the console stats overall total accordingly.
Relates to VSTS 3008. There will still be a slight discrepancy between recorded traffic and 'on the wire' traffic, due to TCP overhead etc.

[P2P] Track traffic of disconnected peers

---

src/Stratis.Bitcoin.Features.ColdStaking.Tests/ColdStakingControllerTest.cs
src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTest.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs

Originally the wallet was designed to reflect the nomenclature of HD wallets and derivation structures.
so we have a wallet that can have multiple account roots to be able to support any number of coins from within the same wallet.
In retrospect, this is a bad idea and wholly unnecessary: we'd never be able to run nodes for multiple coins at the same time and keep the wallet file sane.
The idea  is to remove the account root from the wallet file but rather have a wallet containing a coin type with a collection of accounts.
This change doesn't affect the wallet file, but rather removes support for multiple account roots.
Yet again, this is step 1.

[Wallet] Remove support for multiple account roots - part 1

---

src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs

Re-introduces the skipped test `Notify_Completes_StartHashNotOnChain`.

Re-introduce skipped test Notify_Completes_StartHashNotOnChain

---

src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/TransactionDataTest.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs

Gave a new name to this method as the previous name implied that the method returns amount that is spendable, but in reality the method returns the amount that has not yet been spent.
The amount that has not been spent is not necessarily spendable so the method was renamed to avoid confusion.

[Wallet] Renamed SpendableAmount to GetUnspentAmount to avoid confusion

---

src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs

We need this otherwise the fedwallet nodes won't be able to send each other partial transactions to sign.

[FS] Require the Federation IPs parameter

---

src/Stratis.Sidechains.Networks/CirrusV2/CirrusMain.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusRegTest.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusTest.cs

Hey @noescape00 this is setting up a network that will potentially be used for the real Cirrus. 
Do you have any strong ideas about the max reorg for this network? I picked 240 using the heuristic of roughly 2 loops of the PoA members. Let me know what you're thinking

[FS] Adjusting MaxReorg for CirrusV2 networks

---

src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeatureCollectionTest.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeatureRegistrationTest.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeaturesDependencyCheckingTest.cs
src/Stratis.Bitcoin.Tests/Builder/Feature/FeaturesExtensionsTest.cs
src/Stratis.Bitcoin.Tests/Builder/FullNodeServiceProviderTest.cs
src/Stratis.Bitcoin/Builder/Feature/FullNodeFeature.cs
src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs
src/Stratis.Bitcoin/Controllers/Models/StatusModel.cs
src/Stratis.Bitcoin/Controllers/NodeController.cs

By calling `http://localhost:38221/api/node/status`, the user can see the state of the node but not the state of each individual feature.
We're sometimes interested in knowing the state of each feature.
In particular, when the consensus is rewinding or the wallet is loading, it'd be useful for Stratis Core to know not to call endpoints on these components.
Here is an example showing what would the response from `/api/node/status` called during node startup look like:
```
{
"agent": "StratisNode",
"version": "3.0.4.0",
"network": "StratisTest",
"coinTicker": "TSTRAT",
"processId": 33936,
"consensusHeight": 809658,
"blockStoreHeight": 809658,
"inboundPeers": [],
"outboundPeers": [],
"featuresData": [
{
"namespace": "Stratis.Bitcoin.Base.BaseFeature",
"state": "Initialized"
},
{
"namespace": …
```

[Features] Added support for state in features

---

src/Stratis.Bitcoin.Tests/Connection/ConnectionManagerControllerTest.cs
src/Stratis.Bitcoin.Tests/Connection/ConnectionManagerTest.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs
src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs

This PR provides the following error via Swagger:
```
{
"errors": [
{
"status": 400,
"message": "Can't perform 'addnode' for a banned peer.",
"description": "System.InvalidOperationException: Can't perform 'addnode' for a banned peer.\r\n   at Stratis.Bitcoin.Connection.ConnectionManager.AddNodeAddress(IPEndPoint ipEndpoint) in E:\\Public\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin\\Connection\\ConnectionManager.cs:line 413\r\n   at Stratis.Bitcoin.Connection.ConnectionManagerController.AddNodeRPC(String endpointStr, String command) in E:\\Public\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin\\Connection\\ConnectionManagerController.cs:line 46\r\n   at Stratis.Bitcoin.Connection.ConnectionManagerController.AddNodeAPI(String endpoint, String command) in …
```

Improve error message when connecting to banned peer using Swagger API

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs

Some test cases take more than one minute to complete `ConnectAndSync`. This increases the timeout from one minute to two minutes. For instance this will fix the test cases `CanHandleReorgs` and `ConsensusManager_Fork_Occurs_Node_Gets_Disconnected_Due_To_InvalidStakeDepth` which time out when not being run in debug mode.

ConnectAndSync test helper times out too quickly

---

src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/RewindDataIndexCacheTest.cs
src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/IRewindDataIndexCache.cs
src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/RewindDataIndexCache.cs

This is a fix on the efficiency or rewind data index reported in this PR.
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3383

Improve rewind data index to use an OutPoint instead of a string index

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs

I suspect that why some tests are failing on connect is because the RPC call to connect to another node won't wait for the connection to actually complete. So its possible that we will try the same connection again which will cause the node to disconnect the initial connection. This will cause the Connect method to go into a loop, eventually timing out.

[Tests] Improve TestHelper.Connect

---

src/NBitcoin/Network.cs
src/Stratis.Bitcoin.Api.Tests/ApiSettingsTest.cs
src/Stratis.Bitcoin.Features.Api/ApiSettings.cs
src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs
src/Stratis.Bitcoin.Networks/BitcoinMain.cs
src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs
src/Stratis.Bitcoin.Networks/BitcoinTest.cs
src/Stratis.Bitcoin.Networks/StratisMain.cs
src/Stratis.Bitcoin.Networks/StratisRegTest.cs
src/Stratis.Bitcoin.Networks/StratisTest.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusMain.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusRegTest.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusTest.cs
src/Stratis.Sidechains.Networks/FederatedPegMain.cs
src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs
src/Stratis.Sidechains.Networks/FederatedPegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsTest.cs

Previously we relied on `GetDefaultPort` in the `ApiSettings` class.
This PR fills in each network's `DefaultAPIPort` field with the value that `int GetDefaultPort(Network network)` would have produced and then removes the `GetDefaultPort` method:
```
private static int GetDefaultPort(Network network)	
{	
if (network.IsBitcoin())	
return network.IsTest() ? TestBitcoinApiPort : DefaultBitcoinApiPort;	
return network.IsTest() ? TestStratisApiPort : DefaultStratisApiPort;	
}
```
**IMPORTANT**
Verifying/updating API port values will be left for a separate PR.
The idea is not to have any unexpected side-effects in this PR.

[FN] Move the APIPort location from settings to the Network class

---

src/NBitcoin.Tests/NetworkTests.cs
src/NBitcoin/Network.cs
src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs
src/Stratis.Bitcoin.Features.RPC/RPCClient.cs
src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs
src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs
src/Stratis.Bitcoin.Networks/BitcoinMain.cs
src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs
src/Stratis.Bitcoin.Networks/BitcoinTest.cs
src/Stratis.Bitcoin.Networks/StratisMain.cs
src/Stratis.Bitcoin.Networks/StratisRegTest.cs
src/Stratis.Bitcoin.Networks/StratisTest.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusMain.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusRegTest.cs
src/Stratis.Sidechains.Networks/CirrusV2/CirrusTest.cs
src/Stratis.Sidechains.Networks/FederatedPegMain.cs
src/Stratis.Sidechains.Networks/FederatedPegRegTest.cs
src/Stratis.Sidechains.Networks/FederatedPegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsTest.cs

The `RPCPort` on the `Network` class is not intended to be used directly. This PR renames the field from `RPCPort` to `DefaultRPCPort` to clarify its purpose and align the naming with similarly named fields:

[FN] Rename RPCPort to DefaultRPCPort

---

src/Stratis.Bitcoin.IntegrationTests/LogLevelsTests.cs
src/Stratis.Bitcoin/Controllers/Models/LogRuleModel.cs
src/Stratis.Bitcoin/Controllers/NodeController.cs

Added the endpoint `GET api/node/logrules` to retrieve the log rules as they are enabled in the NLog.config file.
The result will look like so:
```
[
{
"ruleName": "Stratis.Bitcoin.Features.Api.*",
"logLevel": "Debug",
"filename": "'C:\\Users\\jerem\\AppData\\Roaming\\StratisNode\\stratis\\StratisTest\\Logs\\api.txt'"
},
{
"ruleName": "Stratis.Bitcoin.Features.BlockStore.*",
"logLevel": "Debug",
"filename": "'C:\\Users\\jerem\\AppData\\Roaming\\StratisNode\\stratis\\StratisTest\\Logs\\blockstore.txt'"
},
{
"ruleName": "Stratis.Bitcoin.Consensus.ConsensusManager",
"logLevel": "Debug",
"filename": "'C:\\Users\\jerem\\AppData\\Roaming\\StratisNode\\stratis\\StratisTest\\Logs\\CHTandCM.txt'"
},
{
"ruleName": "Stratis.Bitcoin.Features.MemoryPool.*",
"logLevel": "Trace",
"filename": …
```

[Logs] Added an endpoint to get the enabled log rules

---

src/Stratis.Bitcoin.Features.SmartContracts.Tests/BlockBufferGeneratorTests.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TestRulesContext.cs
src/Stratis.Bitcoin.Features.SmartContracts.Tests/SigningContractTests.cs

Very trivial fix... one of the test context creators was overriding the consensus options.

[Tests] Fix Buffer_50Kb_For_1MB_BlockSize

---

src/Stratis.Features.FederatedPeg.Tests/MaturedBlocksProviderTests.cs
src/Stratis.Features.FederatedPeg/Controllers/FederationGatewayController.cs
src/Stratis.Features.FederatedPeg/SourceChain/MaturedBlocksProvider.cs
src/Stratis.Features.FederatedPeg/SourceChain/Result.cs

Modified the return type to `Result` so that we can explicitly indicate the expected failure of a call and return an error message which contains information related to the call. Considered returning `null` but we also need to know the current matured block height at which the request failed.
API still needs to return an error response, otherwise behaviour on the API caller end is different.
Still need to handle exceptions as there are other places they can be thrown.

[FS] Remove GetMaturedDepositsAsync exception

---

src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs

See https://stratisplatformuk.visualstudio.com/Sidechains/_workitems/edit/3378

[FS] Federation gateway nodes can start without adding the counterchain api params

---

src/Stratis.Bitcoin/Connection/ConnectionManager.cs

This fix relates to:
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3502
I was unable to reproduce this bug via various unit tests, so for now we need to protect against passing null endpoints to the Match method. I have also added extra logs so that we can determine when this is the case.

[API] Fix null reference in IPExtension's Match method

---

src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs

Addresses the occasionally failing test case `CreateWalletWith12WordsChineseMnemonicAsync`.
Due to the randomness of word selection a sequence of word could be generated that are identified as `ChineseSimplified` (versus the expected `ChineseTraditional`).
This test is therefore relaxed to allow both.

[FN] Recognize possible language ambiguity for particular word selections

---

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeerListener.cs

asyncProvider.CreateAsyncQueue was called after peer.MessageProducer.AddMessageListener(this);
this caused race condition when a message arrived from a peer, between producer listener registration and asyncqueue creation

NetworkPeerListener constructor fix

---

src/Stratis.Features.FederatedPeg.Tests/WithdrawalTransactionBuilderTests.cs
src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletTransactionHandler.cs

https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3545
@quantumagi you were right on this one... The wallet can get into a state where enough funds are locked up in pending transactions such that it requires time for these transactions to go through, and it isn't actually an error state.

[FS] Log warning for NotEnoughFunds in federation error.

---

src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
src/Stratis.Features.FederatedPeg/Wallet/TransactionData.cs

This property isn't used anywhere, and the callback for broadcast state changing makes it harder to enforce determinism

[FS] Removing propagation property and unnecessary async

---

src/Stratis.Bitcoin/Connection/PeerBanning.cs
src/Stratis.Bitcoin/P2P/PeerAddress.cs
src/Stratis.Bitcoin/P2P/PeerConnector.cs
src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs
src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs
src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs

https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3584
A peer in the `PeerConnectorAddNode` or `PeerConnectorConnect` can become banned after it has been added.

[P2P] Check if the peer is banned inside the peer connector.

---

src/Stratis.Features.FederatedPeg/TargetChain/MaturedBlocksSyncManager.cs
src/Stratis.Features.FederatedPeg/Wallet/DeterministicCoinOrdering.cs

When blocks were coming in sometimes the deposits inside weren't in the correct order.

[FS] Order deposits out of MaturedBlocksSyncManager deterministically

---

src/Stratis.Features.FederatedPeg/Interfaces/IWithdrawal.cs

I actually suggest this two fields should be swapped
```
/// <summary>
/// The hash of the deposit transaction from the source chain.
/// </summary>
[JsonConverter(typeof(UInt256JsonConverter))]
uint256 DepositId { get; }
/// <summary>
/// The hash of the withdrawal transaction to the target chain.
/// This can be null until the trx is fully signed.
/// </summary>
[JsonConverter(typeof(UInt256JsonConverter))]
uint256 Id { get; }
```
Deposit should go to target and Withdraw should come from source
So it should be :
```
/// <summary>
/// The hash of the deposit transaction to the target chain.
/// </summary>
[JsonConverter(typeof(UInt256JsonConverter))]
uint256 DepositId { get; }
/// <summary>
/// The hash of the withdrawal transaction from the source chain.
/// </summary> …
```

Change some comments on IWithdrawal

---

src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs

It's important that we lock all calls to the CCTS. This method is still being used.

[FS] Add locking to GetAsync

---

src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs

Previously this method would identify transactions in the wallet `TransactionData` root. After this change we will be looking in the `TransactionData.SpendingDetails`. The reason for this change is that we want to identify withdrawals (which are spends) and that a withdrawal transaction would not always be found in the `TransactionData` root, specifically when there was no change associated with the withdrawal.
The associated test case is updated to demonstrate that we can now spend the full funding UTXO (i.e. no change) without running into errors on that test case.

[FS] Fix FindWithdrawalTransactions

---

src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs
src/Stratis.Features.FederatedPeg/CollateralChecker.cs

fixes https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3629/ issue
I've relaxed the rule to include all entry generated in any `Stratis.*` namespace and not only for `Stratis.Bitcoin.*`

3629-Errors not logged in Node.txt

---

src/Stratis.Features.FederatedPeg/Interfaces/IFederationWalletManager.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs

Prevents wallet updates from happening while the `CrossChainTransferStore` is using it:
- Encapsulates all public wallet manager methods in `lock(this.lockObject) { ... }`
- Adds `lock (((FederationWalletManager)this.federationWalletManager).lockObject) { ... }` around the CCTS's `Synchronize` method calls and subsequent code to guarantee that the wallet remains in sync for the duration of the method's execution.
Includes an optimization to avoid locking when receiving block batches devoid of deposits. Also added `Guard.Assert` to all `Synchronize` calls to be consistent and not to assume success as we were doing.

[FS] Lock FederationWalletManager during CCTS operations

---

src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs

The `http://` portion gets added where the config value is used, so this was resulting in `http://http//...`

[FS] Default hostname fix

---

src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs

- The Bitcoin documentation defaults verbosity to 1, and returns JSON, not HEX. Recent changes to this RPC method changed the previous default boolean from true, to false.

Fix "getblock" to correctly default verbosity to 1

---

src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs

Rewind Data Index was indexing too much (new UTXO as well as spent UTXO) and it was overwriting UTXO that where not spend but still pulled from disk (this is due to the nature of how coinview works where all the UTXOs of a trx are loaded even though not all inputs are spent n the block)

Fix rewind data index

---

src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs

If they are not ignored, `GetDestinationAddress` doesn't know what to do with them and treats them as segwit addresses. This throws an exception on networks that have no bech32 encoders defined.

Ignore OP_RETURN outputs for address indexing

---

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs

The output was in this form instead of the desired truncated pubkey format:
```
======PoA Miner======
Mining information for the last 20 blocks.
MISS means that miner didn't produce a block at the timestamp he was supposed to.
[PubK]-MISS-[PubK]-[PubK]-[PubK]-[PubK]-MISS-[PubK]-MISS-[PubK]-[PubK]-[PubK]-[PubK]-MISS-[PubK]-MISS-[PubK]-[PubK]-[PubK]-[PubK]-MISS-...
```

Correct PoA console output

---

src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin/Consensus/ScriptAddressReader.cs

#3613 is insufficient, this is a more future-proof way of handling extraction of addresses from scripts.
WIP because the reader should be injected into the indexer. Currently hardcoded to use `ScriptAddressReader`, this should currently only incorrectly handle smart contract & possibly cold-staking transactions.

[FN] Make address indexer use script address reader

---

src/Stratis.Features.FederatedPeg/PartialTransactionsBehavior.cs

The method `BroadcastAsync` throws an object reference, this PR will try to avoid that.

Make sure the BroadcastAsync method will not throw

---

src/Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs

Looks like Connection is getting a null in some cases. Checked `AttachedPeer` and it is already locked and checked for null as part of the `NetworkPeerBehavior.Detach`.

[FS] Fix for null connection when peer is disconnected

---

src/Stratis.Bitcoin.Features.Wallet/Helpers/SentTransactionItemModelComparer.cs

fixed the issue. Payment DestinationAddress default value was set from String.Empty to null and it was causing a nullexception when SentTransactionItemModelComparer was used (e.g. wallet/history API)

3728 - Cannot load transaction history in Stratis Core

---

src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs

Added a null check to make sure we do not get NullReferenceException, sync should reenter and be ok next time around. Alternatively, we may need to just throw a known exception

[FS] Updated sync logic to handle NullReferenceException

---

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs

A fix to place unconfirmed transactions first in the transaction history

[Wallet] Fix for transaction sorting

---

src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
src/Stratis.Features.FederatedPeg.Tests/MaturedBlocksSyncManagerTests.cs
src/Stratis.Features.FederatedPeg/Interfaces/ICrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/TargetChain/MaturedBlocksSyncManager.cs
src/Stratis.Features.FederatedPeg/TargetChain/RecordLatestMatureDepositsResult.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs

Please note that I had to Skip some tests as after a few hours I couldn't figure out a way to Mock the block store in such a few to return the correct transactions. I am going to investigate this further in a separate PR.

Remove hex from spending details in the multi sig wallet

---

src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Tests/Utilities/FileStorageTest.cs
src/Stratis.Bitcoin/Utilities/FileStorage.cs

refers to the issue https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3734/
Save space on wallet serialization and allow to do the same for other users of FileStorage.SaveFile
In this commit I did apply this optimization only for standard Wallet (`WalletManager.SaveWallet`),  we could do the same for any serialization and is as simple as passing a parameter to `FileStorage.SaveToFile` with `minimalSize` set to true
Actually that class is used by FederationWalletManager, PeerAddressManager, AddressBookManager, WatchOnlyWalletManager
I haven't done by purpose because it's out of scope about the issue itself, but it's very trivial do to

JSON wallet serializator and null values (3734)

---

src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
src/Stratis.Features.FederatedPeg.Tests/SignedMultisigTransactionBroadcasterTests.cs
src/Stratis.Features.FederatedPeg/Events/CrossChainTransferTransactionFullySigned.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/TargetChain/SignedMultisigTransactionBroadcaster.cs

I've used the eventbus to publish a `CrossChainTransferTransactionFullySigned` event that SignedMultisigTransactionBroadcaster subscribes to, in order to broadcast a transaction as soon as it's marked as fullysigned.
Implemented some tests too

3679 - Performance: Remove SignedMultisigTransactionBroadcaster and instead broadcast transactions once they are FullySigned.

---

src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
src/Stratis.Features.FederatedPeg.Tests/DepositExtractorTests.cs
src/Stratis.Features.FederatedPeg.Tests/WithdrawalTransactionBuilderTests.cs
src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs
src/Stratis.Features.FederatedPeg/Interfaces/IFederationGatewaySettings.cs
src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
src/Stratis.Features.FederatedPeg/Wallet/DeterministicCoinOrdering.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletTransactionHandler.cs

- Everyone pays 0.001 to transfer coins across.
- Withdrawal transactions will be assigned 0.0002 in fees, plus 0.0001 for every input it uses.
- Given that the wallet has to receive a UTXO to be able to spend it, the average gain for the federation wallet is 0.0007 per 1-way deposit.

[FS] Dynamic fees

---

src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
src/Stratis.Bitcoin.Features.BlockStore/Models/AddressIndexerTipModel.cs

http://localhost:37221/api/blockstore/addressindexertip
returns:
{"tipHash":"a6087a042129c58edf421ea5684a8931ab7a1e388924437ecc6ec0b602ef7316","tipHeight":19583}

[API] Add block store endpoint to return the address indexer's height.

---

src/Stratis.Bitcoin.Features.MemoryPool/MemPoolCoinView.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs
src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs

This should fix a condition where transaction is about to be placed into a memory pool while a block with the same transaction in it arrives.

[FS] Fix for block and tx race condition

---

src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs

Previously was incorrectly outputting both that the transaction did and did not receive enough signatures.

[FS] Fix wrong logs during transaction signing

---

src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs
src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs
src/Stratis.Bitcoin/AsyncWork/AsyncProvider.InnerClasses.cs
src/Stratis.Bitcoin/AsyncWork/AsyncProvider.cs
src/Stratis.Bitcoin/AsyncWork/IAsyncProvider.cs

Implemented an AsyncProvider method to register simple task and handle their healthy status and used such method (AsyncProvider.RegisterTask) to register AddressIndexer indexing Task.
This way if it fails we have evidence in the AsyncProvider statistic output

AddressIndexer can crash without evidence (3780)

---

src/Stratis.SmartContracts.CLR.Tests/ObserverTests.cs

Saw this failed on a PR test run. Giving it a little bit more time so it passes on our frail servers

[SC] [Tests] More time for test to pass

---

src/Stratis.Bitcoin.Features.PoA/FederationMember.cs
src/Stratis.Features.FederatedPeg/Collateral/CollateralChecker.cs

So here we block node initialization until the call to check collateral has completed. If there are no deposits to check the checker will assume that the checker initialized properly.

[POA] Handle the CollateralChecker not initialized exception, round #2

---

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingFeature.cs
src/Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs

Relying on `this.chainIndexer.GetHeader(this.WalletTipHash)` to get the current wallet height can cause a race condition in a reorg scenario.
The reason for this check is to allow blocks that are behind current wallet tip (which is a valid scenario for a wallet catching up) so the ChainIndexer call is not needed.
This replaces PR 
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3664

Removing the wallets manager rely on ChainIndexer

---

src/Stratis.Features.FederatedPeg/FederatedPegBlockDefinition.cs

https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3823
If we're not mining the premine then it should be `PoAMiner`'s responsibility to determine the destination. In this case the member's public key has nothing to do with their wallet, so sending the reward there results in the fees not appearing in the wallet.

[FS] Fix destination of mined fees

---

src/Stratis.Bitcoin/FullNode.cs
src/Stratis.Bitcoin/Utilities/NodeRunningLock.cs

This allows us to stop node initialization before we initialize any component that uses dbreeze which will fail inevitably.

Stop node initialization in case data folder is being used by another instance of the application

---

src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs

Removes this code which was probably never that great an idea. It is more reliable to delete the wallet to re-create it. Also, following PR3639 we don't want re-instate transactions that are being removed by that PR.

[FS] Don't try to fix wallet from CCTS data

---

src/Stratis.Features.FederatedPeg.Tests/Wallet/MultiSigTransactionsTests.cs
src/Stratis.Features.FederatedPeg/Wallet/MultiSigTransactions.cs

The code is looking at the `BlockHeight` on `TransactionData` instead of `SpendingDetails.BlockHeight` so we may end up with missing outpoints for transactions that still need them.
Fixes an error in #3666.

[FS] Fix spentTransactionsByHeightDict

---

src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreClient.cs
src/Stratis.Bitcoin/Controllers/RestApiClientBase.cs
src/Stratis.Features.FederatedPeg/Controllers/FederationGatewayClient.cs
src/Stratis.Features.FederatedPeg/TargetChain/MaturedBlocksSyncManager.cs

Removed duplicated messages, reduced amount of data shown when api endpoint is down (no need to see stack trace there on console's logging level)

Api clients error handling

---

src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs

When setting transfers to suspended (as per #3643) the `NextMatureDepositHeight` also needs to be updated to ensure that the transfers are retried.
It may be causing this bug:

[FS] Setting transfers to Suspended required additional work

---

src/Stratis.Features.FederatedPeg.Tests/Wallet/MultiSigTransactionsTests.cs
src/Stratis.Features.FederatedPeg/Wallet/MultiSigTransactions.cs

The `spendableTransactionList` is sorted by height/id/index and should therefore look out for changes to the `TransactionData.BlockHeight`. This PR adds code to `BeforeBlockHeightChanges` and `AfterBlockHeightChanged` to do exactly that.
The following reported issue may be related:
Notice how, counter-intuitively, an error is raised on line 105 instead of line 102...

[FS] Lookup needs to look for height changes

---

src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationGatewayControllerTests.cs
src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
src/Stratis.Features.FederatedPeg/SourceChain/MaturedBlocksProvider.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
src/Stratis.Features.FederatedPeg/Wallet/SpendingDetails.cs
src/Stratis.Features.FederatedPeg/Wallet/TransactionData.cs

The transaction hex currently stored in the wallet can be retrieved from the block store.

[FS] Remove "Hex" field from Federation Wallet

---

src/Stratis.Features.FederatedPeg/FederatedPegFeature.cs
src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs

Limits the pending transaction withdrawal history to 25 entries. Uses the same ordering as `PartialTransactionRequester`.

[FS] Limit pending tx withdrawal history

---

src/Stratis.Bitcoin.Features.SmartContracts/Models/GetCodeResponse.cs
src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs

Related to 3887. We _do_ return code for all types in the module, but it's not obvious which Type is the contract type. This PR adds the return Type name.

[SC] Return type name with API response

---

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/ContractTransactionItem.cs
src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletController.cs

This is to make sure we only show transactions that have an associated smart contract
Currently, wallet shows all txs in Smart Contracts tab
Future enhancement shoul include load on demand feature, so we only load a limited set of historical items for performance

[FS] Update for SC history endpoint to filter out all txs without a SC

---

src/Stratis.FederatedSidechains.AdminDashboard/appsettings.json
src/Stratis.Sidechains.Networks/CirrusMain.cs

This PR updates the CirrusMain Network to include the public keys of Sidechain Masternodes and additionally updates the default API Endpoints on the Sidechain Dashboard for both StratisMain and CirrusMain

Update CirrusMain & Sidechain Dashboard Endpoints

---

src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs
src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs

As far as I can determine, during the normal handshaking process we were never sending a `getaddr` request. So `getaddr` is only ever sent as part of the discovery loop executed every 10 seconds. But a peer we have just handshaked & connected with will most likely not accept a second connection from us due to IP range filtering, so we never find out its known peers.
https://github.com/stratisproject/stratisX/blob/master/src/main.cpp#L2947-L2953

[FN] Handshaking improvement

---

src/Stratis.Bitcoin.Features.Api/NoCacheMiddleware.cs
src/Stratis.Bitcoin.Features.Api/Startup.cs

API responses currently don't set a caching policy. This causes weird behaviour in some browsers where they return a cached response which is different from expected. See VSTS #3971 which was a result of this.
I don't think there's ever a scenario where we want the browser to cache these values, so we should be able to set the `Cache-Control` header to `no-cache` to prevent this happening.

Set Swagger API response cache control header

---

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs

There was a possibility that slow PCs would miss their timestamp and start waiting for the new one.

Poa miner improvement

---

src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs
src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs
src/Stratis.Features.FederatedPeg.Tests/RestClientsTests/FederationGatewayClientTests.cs
src/Stratis.Features.FederatedPeg/Collateral/CheckCollateralFullValidationRule.cs
src/Stratis.Features.FederatedPeg/Collateral/CollateralChecker.cs
src/Stratis.Features.FederatedPeg/Collateral/CollateralFeature.cs
src/Stratis.Features.FederatedPeg/Collateral/SmartContractCollateralPoARuleRegistration.cs
src/Stratis.Features.FederatedPeg/CounterChain/CounterChainSettings.cs

In comparisons involving `maxReorgLength` and `counterChainConsensusTipHeight` one would expect that the `maxReorgLength` is that of the counter chain. However that is not the case. This PR fixes that by:
- first fixing the `CounterChainNetwork` value on the `CounterChainSettings` class.
- using the value to determine the `maxReorgLength` to use in the comparison.
`CollateralChecker.cs:`
```
public CollateralChecker(ILoggerFactory loggerFactory, IHttpClientFactory httpClientFactory, ICounterChainSettings settings,
IFederationManager federationManager, ISignals signals, Network network, IAsyncProvider asyncProvider)
{
...
this.maxReorgLength = AddressIndexer.GetMaxReorgOrFallbackMaxReorg(settings.CounterChainNetwork);
...
lock (this.locker)
{
if (heightToCheckAt > …
```

[FS] Fix CheckCollateralFullValidationRule

---

src/Stratis.Bitcoin.Features.Wallet/HdOperations.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs

The existing documentation for these two properties was potentially misleading, I think this clarifies it somewhat.

Clarify wallet documentation

---

src/Stratis.Bitcoin/Connection/ConnectionManager.cs

This PR fixes the IP address matching in the CM's `ShouldDisconnect` method to take into account that IP addresses can be either V4 or V6.
This may be related to https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3934.

Fix CM's ShouldDisconnect IP address matching

---

src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
src/Stratis.Bitcoin.Features.Miner/Interfaces/IPosMinting.cs
src/Stratis.Bitcoin.Features.Miner/Models/GetStakingInfoModel.cs
src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
src/Stratis.Bitcoin.Features.RPC.Tests/Models/GetStakingInfoTest.cs

Currently this balance uses spendability as the criteria, which is incorrect, as candidates UTXOs for staking need to have a higher minimum number of confirmations.
Will also require a minor modification to Stratis Core to use the new field in its calculation.

[FN] Fix "Coins awaiting maturity" balance while staking

---

src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs
src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin/Controllers/Models/AddressBalancesResult.cs
src/Stratis.Features.FederatedPeg.IntegrationTests/NodeInitialisationTests.cs
src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs
src/Stratis.Features.FederatedPeg/Collateral/CollateralChecker.cs

Currently the `ConsensusTipHeight` is not being returned when there is no collateral requirement configured. This PR avoids the resultant strange behavior, such as the side chain tip not advancing.
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3998.

[FS] Ensure proper behavior when there is no collateral requirement configured

---

src/NBitcoin/ConsensusOptions.cs
src/NBitcoin/OpenAsset/CoinprismColoredTransactionRepository.cs
src/NBitcoin/QBitNinjaTransactionRepository.cs
src/Stratis.Bitcoin/Utilities/NetworkExtensions.cs

Determining network type by string comparisons is quite horrible.

Remove usages of network name

---

src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinViewRuleLogic.cs
src/Stratis.SmartContracts.Core.Tests/Receipts/PersistentReceiptRepositoryTests.cs
src/Stratis.SmartContracts.Core.Tests/Receipts/ReceiptSerializationTest.cs
src/Stratis.SmartContracts.Core/Receipts/Receipt.cs

Adds the MethodName to CALL receipts. This is not backwards compatible for existing receipts, so we add a check for this field when retrieving the receipt from storage.

[SC] Add method name to storage receipt

---

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
src/Stratis.Bitcoin.Features.Wallet/Helpers/SentTransactionItemModelComparer.cs
src/Stratis.Bitcoin.Features.Wallet/Models/WalletHistoryModel.cs

Found an original PR that added `Distinct()` to dedupe transactions: https://github.com/stratisproject/StratisBitcoinFullNode/pull/3362. Not sure why it was needed. Investigating why it was needed.

[FS] Removed dedupe code as it filters out legit transactions

---

src/Stratis.Bitcoin.Features.PoA/BasePoAFeatureConsensusRules/HeaderTimeChecksPoARule.cs

The proposed 5 seconds difference is in the relation to the reference clock as since two nodes could be at the opposite side of the spectrum (i.e. one node having time -5 second while the other + 5 sec) the maximum difference we can account for is 10 seconds.

Updated the MaxFutureDriftSeconds to 10 seconds

---

src/NBitcoin/DNSSeedData.cs
src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs

This looks like a bug, as it seems to me you could land up in a scenario where all peers retrieved from the seeds were non-responsive, and you would never ask the seeds again for more potential peers.

[FN] Peer discovery

---

Documentation/ImportantOnly_NLog.config

We already have the consensus logs which contains the logs for the CHT and CM, so the extra logs are just taking up space.
The CMB logs are also being duplicated but because that file contains other useful info I've left it for now.

Remove duplicated logs

---

src/Stratis.Bitcoin.Features.Dns/DnsSeedServer.cs

This sets the appropriate bit (`AA`) in the response header.

[DNS] Make DNS response authoritative

---

src/Stratis.Bitcoin.Features.Api/MvcBuilderExtensions.cs
src/Stratis.Bitcoin.Features.Api/Startup.cs
src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletFeature.cs
src/Stratis.Bitcoin/Base/BaseFeature.cs

We already automatically include feature assemblies (in `MvcBuilderExtensions.AddControllers`). Since these assemblies would also include the controllers of these features there are usually no issues with the framework discovering the controllers. However when a feature wants to include a controller from another feature that is not explicitly added to the builder, the controller's assembly needs to be included explicitly. This PR makes it possible to do that and fixes the SmartContract feature so that it causes the wallet's assembly to be included for use by the framework during controller discovery.
See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4201

[FN] Make foreign controllers visible to framework

---

src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
src/Stratis.Bitcoin.IntegrationTests/ConsensusManagerTests.cs

This test continuously fails the CI build. I've updated the wait loop helper that checks the height of the node to output some information when it fails. Once we know this I can investigate further.

Attempt to fix ConsensusManager_Fork_Occurs_When_Stake_Coins_Are_Spent_And_Found_In_Rewind_Data

---

src/Stratis.Bitcoin.Features.Consensus/Behaviors/ProvenHeadersReservedSlotsBehavior.cs
src/Stratis.Bitcoin.Tests/P2P/SelfEndpointTrackerTests.cs
src/Stratis.Bitcoin/Connection/ConnectionManager.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs
src/Stratis.Bitcoin/P2P/SelfEndpointTracker.cs

This tries to address a few things:
1. The externalip config setting defaults to loopback when it is not specified
2. This means that the self endpoint tracker was always regarding the loopback as the definitive external endpoint
3. So this has been corrected to not regard loopback as definitive ('final')
4. The matching of the endpoint seemed to have some inconsistencies in IPv4/IPv6 representation. For now, the endpoints are compared as addresses only (as ports reported by outbounds are always ephemeral) and are coerced to IPv6 representation when comparing
5. A `using` statement was removed & replaced with a try block; `using` statements can hide exceptions in some cases -> https://minddotout.wordpress.com/2012/12/27/the-c-using-statement-breaks-exception-handling/
6. Possibly as a …

[P2P] Attempt to fix self endpoint tracker

---

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingFeature.cs
src/Stratis.Bitcoin/Utilities/NodeStats.cs

The cold staking feature is now pulling in the wallet feature. So a few changes are needed:
1. Avoid printing help twice. CS should no longer print help on behalf of the wallet.
2. Don't display stats twice. CS displays all the stats so the wallet stats should be turned off.
3. Remove duplicated calls from CS. The wallet already calls `Start` or `Intitialize` on some dependencies. No need for CS to do it again.
See https://github.com/stratisproject/StratisBitcoinFullNode/pull/3860.

 ColdStaking feature no longer needs to print wallet help

---

src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs

This fixes an issue where transaction may have lots of inputs. For example, you could have sent 4 x 250 Strat to different addresses within 5 minutes. But you had thousands of small unspent funds. Your first transaction may combine more than 500 inputs together and the other 3 txs will never appear in the history. This PR fixes it by only looking at unique tx ids.

[FN] Fix for wallet TX history

---

src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs

Reported in https://github.com/stratisproject/StratisCore/issues/263
It seems that during the federation feature startup, the AddNode list is getting modified frequently and thus the exception is more likely to be hit.

[P2P] Fix for addnode list enumeration

---

src/Stratis.Features.Collateral/CollateralFeature.cs
src/Stratis.Features.FederatedPeg.IntegrationTests/NodeInitialisationTests.cs
src/Stratis.Features.FederatedPeg/FederatedPegFeature.cs

https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4264.

[FS] Fix null ref in periodic benchmark. Each daemon now only has 1 PoAConsensusRules

---

src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs

Throw error when mnemonic passed to enable-federation doesnt match the pub key for the member

Throw enable federation on pub key mismatch

---

src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs

This one is related to https://github.com/stratisproject/StratisBitcoinFullNode/pull/3905 
Scenario most likely happening in Fed Wallet:
- UTXO A used for Deposit1 to create WithdrawalTx1.
- WithdrawalTx1 (consuming UTXO A, fulfilling Deposit1) is partially signed.
- Reorg occurs, transactions to use as inputs for withdrawal txs are reordered.
- UTXO A now used for Deposit2 to create WithdrawalTx2. Removes duplicates for Deposit2.
- In the process, WithdrawalTx1 was never removed.

[FN] Added an extra handling for fed wallet orphan txs getting stuck

---

src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs

Currently, if we get full validation error we translate validation errors into `ConsensusException` which `PoAMiner` cannot handle. 
```
ConnectBlocksResult fullValidationResult = await this.FullyValidateLockedAsync(validationContext.ChainedHeaderToValidate, true).ConfigureAwait(false);
if (!fullValidationResult.Succeeded)
{
this.logger.LogDebug("Miner produced an invalid block, full validation failed: {0}", fullValidationResult.Error.Message);
this.logger.LogTrace("(-)[FULL_VALIDATION_FAILED]");
throw new ConsensusException(fullValidationResult.Error.Message);
}
```
Added a catch to handle consensus errors (similar to PoSMinting). Alternative approach would be to throw `ConsensusErrorException`

[FN] Fix for a FATAL exception when full validation fails

---

src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs

`indexPrev` would not get reset after the first loop iteration, so only the first deployment would ever show any vote data.

Only first deployment showed vote data

---

src/Stratis.Bitcoin.Features.RPC/RPCClient.cs
src/Stratis.Bitcoin.Features.RPC/RPCClientFactory.cs

This PR addresses an issue whereby the swagger call to the RPC method will fail if the RPC server is bound to listen on 0.0.0.0.
The solution will work in the case of the RPC binding to all interfaces or dedicated single interface.

Ensure that the RPCClient will work even if the server is listening on all interfaces

---

src/NBitcoin/TransactionBuilder.cs

This is just to lessen the perceived changes to TransactionBuilder in subsequent PRs:
To view view diff without whitespace:
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3955/files?w=1

Reformat TransactionBuilder [Whitespace Only Change]

---

src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs
src/Stratis.Bitcoin.Features.RPC/RPCRouteHandler.cs

When we write response using `JsonTextWriter` and then later on read the response using `JsonTextReader`, by default all floats are converted to double even if original value was decimal. This PR ensures values are converted to decimal so we don't get precision issues and scientific notation formats returns (i.e. 2e10-5) 
https://github.com/JamesNK/Newtonsoft.Json/issues/1904

[RPC] Fixed parsing of floats

---

src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs

Moved shuffle inside the retry and updated retry count.
I have performed 500 "transaction build" requests via swagger and PowerShell and all succeded.
Prior to the change, I was getting about 1 in 10 failures.

[FN] Fix for failing transaction build

---

src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletRepository.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepositoryExt.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDTransactionData.cs

6x speed improvement (`GetTransactionOnTransactionReceivedToMultipleAddressesAsync` context)
```
// 0.01885383474 sec
// 0.1129
long flagFall = DateTime.Now.Ticks;
for (int x = 0; x < 10000; x++)
rpcSendingNode.SendCommand(RPCOperations.gettransaction, txId.ToString());
long time = DateTime.Now.Ticks - flagFall;
```

First optimizations for RPC method "gettransaction"

---

src/Stratis.Bitcoin.Features.SignalR/Broadcasters/CirrusWalletInfoBroadcaster.cs
src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
src/Stratis.Bitcoin/Consensus/IConsensusManager.cs
src/Stratis.CirrusD/Program.cs

Update IConsensusManager to expose ChainTip from ChainHeaderTree for better representation of % Sync Complete when in IBD Mode.
This PR also adds separate CirrusWalletInfoBroadcaster for CirrusD and remove the Balance Calculation per address on StratisMain.

Fix Wallet Broadcast Performance + ChainTip Calculation

---

src/Stratis.Bitcoin.Features.RPC.Tests/RPCParametersValueProviderTest.cs
src/Stratis.Bitcoin.Features.RPC/RPCParametersValueProvider.cs

This fixes the case when controller action has all parameters optional with default values and RPC call parameter list is empty/null.
Currently, `NullReferenceException` is thrown. With this fix, the default value for the parameter is used.

[RPC] Fix for RPC ListUnspent default parameter binding

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs

This PR optimizes "getbalance" by utilizing the `GetBalances` method provided by the wallet manager. The `GetBalances` method is first upgraded to support the `confirmations` argument. It is also standardized to use the chain tip and not the wallet tip.

Optimize "getbalance"

---

src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs

When passing invalid hex for decoding transaction RPC should give you an appropriate error and not "Method not found"

[RPC] Fix RPC call for decoding transaction

---

src/Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeerCollection.cs

Inbound connections will be on an ephemeral port rather than the default port, and thus cannot be matched via endpoint

[P2P] Allow inbound connections to be whitelisted

---

src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractWalletFeature.cs

Should fix https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4465
I don't have a test that I can easily make to show the difference, but this change puts the SCWallet in line with the standard Wallet.
`GetSpendableTransactions` was taking up massive amounts of time because it needs to convert all the SQL data to readable data.

Use GetBalances in ComponentStats

---

src/Stratis.Bitcoin.IntegrationTests.Common/ReadyData/ReadyBlockchain.cs
src/Stratis.Bitcoin.IntegrationTests.Common/Stratis.Bitcoin.IntegrationTests.Common.csproj
src/Stratis.Bitcoin.IntegrationTests/Compatibility/StratisXTests.cs

- Test now only syncs 3500 blocks compared to 15000.
- Still syncs before and after last checkpoint.
- Still syncs both PoW and PoS blocks.
- No txindex on the Stratis node.
Should be a bit more reliable.

Gateway integration test improved

---

src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs
src/Stratis.Features.SQLiteWalletRepository/Commands/ProcessBlockCommands.cs
src/Stratis.Features.SQLiteWalletRepository/DBConnection.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepositoryExt.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDAddress.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDTransactionData.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/TempOutput.cs
src/Stratis.Features.SQLiteWalletRepository/TransactionsToLists.cs

Adds an `Address` field to the `HDAddress`. The field is for display purposes only and the idea is to avoid having to convert `ScriptPubKey`s to addresses for API's that require an address - i.e. for optimization.

Add Address to HDAddress table

---

src/Stratis.Bitcoin.Features.ColdStaking.Tests/ColdStakingManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Features.SQLiteWalletRepository/Commands/ProcessBlockCommands.cs
src/Stratis.Features.SQLiteWalletRepository/External/ITransactionsToLists.cs
src/Stratis.Features.SQLiteWalletRepository/TransactionsToLists.cs

Some SC-related payments details are not showing up in the HDPayments table.
This PR relaxes the constrains under which the outputs of spending transactions are recorded.

Add payment details unconditionally to HDPayments

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
src/Stratis.Bitcoin.Features.Wallet/AccountRoot.cs
src/Stratis.Bitcoin.Features.Wallet/HdAddress.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletRepository.cs
src/Stratis.Bitcoin.Features.Wallet/SpendingDetails.cs
src/Stratis.Bitcoin.Features.Wallet/TransactionData.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs
src/Stratis.Features.SQLiteWalletRepository.Tests/WalletRepositoryTests.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepositoryExt.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDPayment.cs

The purpose of this PR is to optimize the reading of transaction data. Currently payment details are included with the transaction data being read. We want to only read the payment details when the property associated with the payment details is accessed. This is achieved by creating a class that implements this behavior and by defining the payment (and change) property to be an instance of that class. Additional changes cascade out of this approach.

Postpone reading payment details when transaction data is read

---

src/Stratis.Features.SQLiteWalletRepository/Tables/HDTransactionData.cs

Pretty massive performance improvement.
These are PoA mining coinbases. They can be ignored.

[Wallet Performance] Only get transactions with amount > 0 for balance and spendable transactions

---

src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs

This PR improves performance of `GetHistory()` ~3x by using lookups for `txId`

Improve performance of GetHistory Request using lookups.

---

src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs

https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4515.
We are getting a constraint violation on inserting addresses. So the motivation for this change is that we should insert instead of replacing if there is a chance of encountering the same address twice. Also, as an added safety measure we add Guards to detect if we have a null or empty field - which would lead to a reduction in uniqueness of the key fields.

Constraint violation on HDAddress insert

---

src/Stratis.Features.SQLiteWalletRepository.Tests/DBParameterTests.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepositoryExt.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/DBParameter.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDAddress.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDPayment.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDTransactionData.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/TempOutput.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/TempPrevOut.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/TempTable.cs
src/Stratis.Features.SQLiteWalletRepository/TransactionsToLists.cs

SQLite's decimal type inaccuracies add up when summing over large numbers of values. Currently summation results can even be non-deterministic, being dependent on the order in which values arrived in the database.
At the root of this issue is SQLite's underlying use of floating point values in its decimal implementation.
As such we get rid of the decimal type and use integer values (satoshis) instead.
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4520.
This is the first change in what is currently expected to be a two-part fix.

Workaround for SQLite decimal precision issues

---

src/NBitcoin.Tests/pos_transaction_tests.cs
src/NBitcoin.Tests/transaction_tests.cs
src/NBitcoin/FeeRate.cs
src/NBitcoin/Transaction.cs
src/NBitcoin/TransactionBuilder.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/FeeTests.cs
src/Stratis.Bitcoin.Features.MemoryPool.Tests/MemoryPoolTransactionTests.cs
src/Stratis.Bitcoin.Features.MemoryPool/TxMemPoolEntry.cs
src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.Tests/Models/TransactionModelsTest.cs
src/Stratis.Bitcoin/Controllers/Models/TransactionModel.cs

Brings decoderawtransaciton  closer to the BTC client by removing hex property from the response to reduce size and adding `weight` field. 
where weight is `The transaction's weight (between vsize*4 - 3 and vsize*4)`
https://github.com/bitcoin/bitcoin/blob/048e456fc40821939e8becd2d53e0352d9451be2/src/rpc/rawtransaction.cpp#L438

[RPC] Fixes to bring decoderawtransaciton RPC call closer to BTC client

---

src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs

For https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_boards/board/t/StratisBitcoinFullNode%20Team/Stories/?workitem=4529
This code was nonsensical. The API calls that forwarded here required a password, but also cached secrets by default. So for the next 5 minutes it required a password and then did no validation on it. Incorrect passwords would still pass as correct.
I would rather remove this code so there is no ambiguity about the current functionality. Every operation requires a correct password.
At the point in the future when we might want to keep the wallet alive, we can do it correctly.

No caching wallet secrets

---

src/Stratis.Features.SQLiteWalletRepository.Tests/WalletRepositoryTests.cs
src/Stratis.Features.SQLiteWalletRepository/External/ITransactionsToLists.cs
src/Stratis.Features.SQLiteWalletRepository/SQLiteWalletRepository.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/TempTable.cs
src/Stratis.Features.SQLiteWalletRepository/TransactionsToLists.cs
src/Stratis.Features.SQLiteWalletRepository/WalletContainer.cs

https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4520/
Addresses created by the "address top-up trackers" are written to the database just before calling the scripts that process the data from a batch of blocks. However the tracker collection is being re-created for each block.
This PR also adds additional logging and extends a test case.

Update top-up tracker scope from block to batch

---

src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
src/Stratis.Features.SQLiteWalletRepository/Tables/HDTransactionData.cs

Fixes https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_boards/board/t/StratisBitcoinFullNode%20Team/Stories/?workitem=4553
The added check to the WalletTest, the 2nd file, fails before this change. Passes after.

Correct query for spendable balance

---

src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs

This is the fix for large request body which is getting truncated during the read.
Issue is that for large streams `Body.ReadAsync` reads request in chunks and returns the number of remaining bytes, which we are not utilizing. We need to wrap reading in a while loop and keep reading until we have no bytes remaining.

[RPC] Fix for decode rpc

---

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs

The current `PosMinting` implementation computes the immature balance by summing up all UTXO values that are determined to be immature while searching for staking candidates.
However, due to the implementation of the `GetSpendable*` methods in the wallet, the minter never sees immature UTXOs in the first place. So the balance is always 0. See #3778 for when the `immature` field was introduced.
For the current PR, it is less efficient retrieving UTXOs we know we can't stake from the coinview, but we need them for computation of the immature coin balance. In any case, for most wallets this will be a neglible quantity of UTXOs at any given point, as there can generally be at most 1 immature UTXO generated across the entire network per block, unless coinstake splitting is being used. …

Fix for immature coin balance

---

src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs

* Fix for immature coin balance
* Remove erroneous depth check
* Additional coinstake maturity tests
* Correct logic
* Comment clarification
Relates to https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4561/.

Fix for immature coin balance (#4051)

---

src/Stratis.Bitcoin/Consensus/ConsensusManager.cs

See the additional comment on the change.
This relates to situations where "unknown" ban reasons are shown in the logs.

[Consensus] Add ban time and ban reason to reconnect chain result.

---

src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs

Fix for `Could not save blocks to the block repository. Exiting due to 'Transaction commit failed on table "Common"!'`
We should synchronize all tables that are modified as part of the same transaction as per https://github.com/hhblaze/DBreeze/issues/15. Currently, we only sync `BlockTableName` and  `TransactionTableName` which can lead to IO exception. `SaveTipHashAndHeight` call modifies Common table and therefore should be added to a sync call.

[SC] Fix for IO Exception

---

src/NBitcoin.Tests/NetworkTests.cs
src/Stratis.Bitcoin.Networks/StratisMain.cs
src/Stratis.Bitcoin.Networks/StratisTest.cs
src/Stratis.Bitcoin.Tests/Consensus/CheckpointsTest.cs
src/Stratis.Sidechains.Networks/CirrusMain.cs
src/Stratis.Sidechains.Networks/CirrusTest.cs

This PR removes stale entries from the seeds for all networks and updates the Stratis seeder domains to stratisnetwork.com for all networks also.

Update Seeders and Seeds & Increase Checkpoint Heights

---

src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
src/Stratis.Bitcoin.IntegrationTests/Connectivity/ConnectivityTests.cs
src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
src/Stratis.Bitcoin.Tests.Common/ConsensusManagerHelper.cs
src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
src/Stratis.Bitcoin.Tests/P2P/NetworkPeerServerTests.cs
src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeerFactory.cs
src/Stratis.Bitcoin/P2P/Peer/NetworkPeerServer.cs

This fixes a long standing issue whereby the node would stop receiving inbound connections.
The bug is that we add the connected peer to the network peer disposer after it has been disconnected because of a ban. The result is that the connected peers collection in the network peer disposer constantly increases as we never have the peer in the collection by the time the other node has disconnected it due to a ban. Eventually the max inbound count is reached and the node stops incoming connections here:
```
if (this.networkPeerDisposer.ConnectedInboundPeersCount >= this.connectionManagerSettings.MaxInboundConnections)
{
this.logger.LogTrace("(-)[MAX_CONNECTION_THRESHOLD_REACHED]:false");
return (false, $"Inbound Refused: Max Inbound Connection Threshold Reached, inbounds: …
```

Fix the node blocking inbounds after an inordinate amount of disconnects due to a peer being banned

---

src/Stratis.Bitcoin.Features.PoA/PoAConsensusErrors.cs
src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoARuleRegistration.cs
src/Stratis.CirrusD/Program.cs
src/Stratis.CirrusDnsD/Program.cs
src/Stratis.CirrusDnsD/Stratis.CirrusDnsD.csproj
src/Stratis.CirrusMinerD/Program.cs
src/Stratis.CirrusPegD/Program.cs
src/Stratis.Features.Collateral/CheckCollateralCommitmentHeightRule.cs
src/Stratis.Features.Collateral/CheckCollateralFullValidationRule.cs
src/Stratis.Features.Collateral/CollateralFeature.cs
src/Stratis.Features.Collateral/CollateralPoAMiner.cs
src/Stratis.Features.Collateral/SmartContractCollateralPoARuleRegistration.cs
src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainFederationNodeRunner.cs
src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainMinerNodeRunner.cs
src/Stratis.Features.FederatedPeg.Tests/CheckCollateralFullValidationRuleTests.cs
src/Stratis.Features.FederatedPeg.Tests/CollateralHeightCommitmentEncoderTests.cs

CirrusD nodes also needs to validate whether blocks that they receive contain valid commitment height, otherwise they are potentially relaying invalid block. This is causing these nodes to get banned incorrectly.
So the approach here is the split the commitment height check into its own rule so that CirrusD and CirrusDnsD run just that and then the miners the full set of checks.

Split the Check Collateral Full Validation Rule

---

src/Stratis.Bitcoin.Features.Api/Stratis.Bitcoin.Features.Api.csproj
src/Stratis.Bitcoin.Features.SignalR/Stratis.Bitcoin.Features.SignalR.csproj
src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
src/Stratis.Features.Collateral/CheckCollateralCommitmentHeightRule.cs

The genesis block won't contain any height commitment data.

CheckCollateralCommitmentHeightRule should ignore the Genesis block

---

src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs
src/Stratis.Features.Collateral/CheckCollateralCommitmentHeightRule.cs
src/Stratis.Sidechains.Networks/CirrusTest.cs

The CirrusTest network only had collateral height commitment data written to it's block at height 25810 and onwards and as we check each block from Genesis we have to ignore everything before height.

Add CollateralHeightCheck to CirrusTest (PoANetwork)

---

src/Stratis.Bitcoin.Features.RPC.Tests/RPCMiddlewareTest.cs
src/Stratis.Bitcoin.Features.RPC/RPCFeature.cs
src/Stratis.Bitcoin.Features.RPC/RPCMiddleware.cs
src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs
src/Stratis.Bitcoin.Features.RPC/Startup.cs
src/Stratis.Bitcoin/Utilities/FileStorage.cs

Add adjustable RPC content type to be compatible with other services.
Our default Content Type is set to `application/json; charset=utf-8`
While e.g. ElectrumX only accepts `application/json`

Adjustable RPC Content Type

---

src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
src/Stratis.Bitcoin/Utilities/FileStorage.cs

I have carefully re-reviewed the logic around peer discovery; I do not actually see how a node with acceptable network connectivity can remain without peers for an extended period even if the `peers.json` somehow got corrupted.
Nevertheless, this traps for any exceptions (if the deserialisation of the JSON happens to throw any - this is somewhat doubtful), and initialises an empty list if the deserialised object is ever `null`.
The expected behaviour if this occurs is that the `PeerDiscoveryLoop` will in any case run almost immediately after startup and determine that there are no known peers. It will then add the DNS seeds & seed nodes as discovery candidates, which should elicit some connectable peers.

[FN] Additional handling for malformed peers.json

---

src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs

For larger OP_RETURN output values, insufficient coins would be added to the builder

Fix OP_RETURN value in transaction building
